### PR TITLE
Decrease allocation rate by making CacheOperation immutable

### PR DESCRIPTION
**Pull request by m5k10**
This is new PR after original one (https://github.com/spring-projects/spring-framework/pull/942) has been messed up.

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks.

**Comment by snicoll** [comment]
Thanks a lot for the PR, this is merged in master. I would like to add your full name to some classes in recognition of your work but I am not sure what it is. Can you share that? Thanks!

**Comment by soldierkam** [comment]
Thanks for merge! My name is 'Marcin Kamionowski'

**Comment by snicoll** [comment]
I've update the `@author` tag in https://github.com/spring-projects/spring-framework/commit/513c1ea3d96b09ddb8a256c3245c619ebfc063e2

**Pull request closed without merging**
