### PR TITLE
Polish: Replace this "Map.get()" and condition with a call to "Map.computeIfAbsent()"

### PR DESCRIPTION
**Pull request by andrey916**
Polish: Replace this "Map.get()" and condition with a call to "Map.computeIfAbsent()"

### CODE REVIEW

**Comment by jhoeller** [comment]
I'm keeping this one on hold for the time being: While the `computeIfAbsent` syntax is certainly appealing, it comes with different locking behavior, in particular regarding our double-checked locking approach with a quick `ConcurrentHashMap` check first and a second attempt within full synchronization. 

On review, I did uncover two minor oddities in the affected code which I've revised and prepared for backporting to 4.3.x. Even if we're not merging such a pull request immediately, I really appreciate the opportunity to review those code spots! I'll revisit the `computeIfAbsent` part for 5.1 a bit later.

**Comment by andrey916** [comment]
@jhoeller, thank you for taking your time for the review

**Comment by jhoeller** [comment]
A quick update: I've applied the use of computeIfAbsent for the lazy creation of nested collection structures in places where this fits with our locking assumptions, therefore selectively addressing a part of your pull request. This will make it into 5.0.5 for a start; thanks for helping to identify those spots!

**Comment by andrey916** [comment]
Always ready to help :-)

**Pull request closed without merging**
