### PR TITLE
Upgrade to Gradle 6.2

### PR DESCRIPTION
**Pull request by jjohannes**
- Build Scan plugin is now Gradle Enterprise plugin applied in settings
- Compile task dependencies are now defined through classpath
- Test fixture publication can be disabled through public API

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jjohannes Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24384)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24384) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jjohannes Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24384)!

**Comment by sbrannen** [comment]
Thanks for the PR!

We'll likely hold off on merging this until `master` represents the work for Spring Framework `5.3.x`.

**Comment by sbrannen** [comment]
Hi @jjohannes,

We've just branched for Spring Framework 5.3 work. So `master` is now for 5.3, and we can proceed with the Gradle upgrade. However...

1. Gradle 6.3 has been released since you last updated this PR.
2. There are merge conflicts in this PR now.

In light of that, would you be willing to update this PR against the current state of `master`?

**Comment by sbrannen** [comment]
@jjohannes, never mind: @bclozel already merged it and will take care of the 6.3 upgrade. 😉

**Pull request closed without merging**
