### PR TITLE
Do concatenation with String::substring instead of StringBuilder::append in short append chain

### PR DESCRIPTION
**Pull request by stsypanov**
Changed code is not only shorter and more simple, but also faster and consumes less memory, see measurements here: https://youtrack.jetbrains.com/issue/IDEA-205676

### CODE REVIEW

**Comment by jhoeller** [comment]
You have a point there. However, this code is a repackaged fork of https://gitlab.ow2.org/asm/asm/commits/master, so any such refactorings should really start there... and we'll automatically pick it up for our fork at our next sync point then.

**Comment by stsypanov** [comment]
oh, I wasn't aware of that. Should I then make similar pull-requests into that repo?

**Comment by jhoeller** [comment]
Indeed, ASM itself would certainly benefit from such fine-grained optimizations. They applied quite a few such refactorings last year already, and I'm sure they'll appreciate some further love for the detail there.

**Comment by stsypanov** [comment]
Done for both PRs.

**Pull request closed without merging**
