### PR TITLE
Simplify getCache() method in CaffeineCacheManager

### PR DESCRIPTION
**Pull request by bananayong**
I would like to make some contributions.

Current spring framework is based on JDK8. So, CaffeineCacheManager.getCache() method can be simplified with Map.computeIfAbsent

Thank you.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bananayong Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24376)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24376) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bananayong Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24376)!

**Comment by sbrannen** [comment]
Thanks for the PR!

I ended up implementing this slightly differently in 16e49bf0c92f9387ccf10426f77ba3b02f4c24fb.

**Comment by bananayong** [comment]
Thank you to reflect my contribution.
It looks simpler!

But, I would like to give an opinion.
```java
cacheName -> this.dynamic ? createCaffeineCache(cacheName) : null
```
This lambda expression accesses `this.dynamic` member field. It causes capturing variable.
`getCache` method will create new lambda instance whenever called.
It can be avoided if `this.dynamic` is checked outside lambda.

Please, ignore this comment if there is no big benefits.
Thank you!

**Pull request closed without merging**
