### PR TITLE
Add support for making MapAccessor read-only

### PR DESCRIPTION
**Pull request by quaff**
Align to `ReflectivePropertyAccessor`

### CODE REVIEW

**Comment by snicoll** [comment]
Before we can consider this PR, we'd need to understand the use case. You are talking about alignment but I don't see that as necessary (or inconsistent at the moment). Also, please refrain from doing unrelated changes. All those formatting in the tests should go away.

**Comment by quaff** [comment]
> Before we can consider this PR, we'd need to understand the use case.

I need `EvaluationContext` like `SimpleEvaluationContext.forReadOnlyDataBinding()` plus `MapAccessor`.

> Also, please refrain from doing unrelated changes. All those formatting in the tests should go away.

OK, I will revert those changes.

**Comment by sbrannen** [comment]
Hi @quaff,

> I need `EvaluationContext` like `SimpleEvaluationContext.forReadOnlyDataBinding()` plus `MapAccessor`.

In order to achieve your goal, you'll actually need to make use of `withAssignmentDisabled()` as well -- for example, something like the following.

```java
SimpleEvaluationContext context = SimpleEvaluationContext
		.forPropertyAccessors(new MapAccessor(false), DataBindingPropertyAccessor.forReadOnlyAccess())
		.withAssignmentDisabled()
		.build();
```

- see #33319

**Comment by quaff** [comment]
Thanks for your caution.

**Pull request closed without merging**
