### PR TITLE
Add tests for StringUtils matchesCharacter() method

### PR DESCRIPTION
**Pull request by springmonster**
Add tests for StringUtils matchesCharacter() method

### CODE REVIEW

**Comment by springmonster** [comment]
Dear @sbrannen , could you please help to review this？
Thank you very much!

**Comment by sbrannen** [comment]
> Dear @sbrannen , could you please help to review this？ Thank you very much!

Hi @springmonster,

Please refrain from mentioning individual maintainers of the project. The entire team sees all PRs, and somebody from the team will look at it in due time.

**Comment by springmonster** [comment]
> > Dear @sbrannen , could you please help to review this？ Thank you very much!
> 
> Hi @springmonster,
> 
> Please refrain from mentioning individual maintainers of the project. The entire team sees all PRs, and somebody from the team will look at it in due time.

OK, thanks for the kind reminder.

**Comment by sbrannen** [comment]
This has been merged into `5.3.x` and `main`.

Thanks

**Pull request closed without merging**
