### PR TITLE
Replacing netty-all with specific dependencies

### PR DESCRIPTION
**Pull request by suztomo**
As per @bclozel 's comment on the below:

> Spring Framework is sometimes depending on "-all.jar" variants for historical reasons, and doing so in an application or library is not advised. Arguably we should not do that in our build and this is something we should fix. But in the meantime this is incorrect/misleading information we're publishing

https://github.com/spring-projects/spring-framework/issues/23234#issuecomment-521153626

spring-framework/spring-web/src contains references to following netty packages covered by the artifacts:

- artifact netty-buffer
  - io.netty.buffer
- artifact netty-transport
  - io.netty.channel
  - io.netty.bootstrap
  - io.netty.channel.nio
- artifact netty-handler
  - io.netty.handler.ssl
  - io.netty.handler.ssl.util
  - io.netty.handler.timeout
- artifact netty-codec-http
  - io.netty.handler.codec.http

### CODE REVIEW

**Review by mentallurg — COMMENTED** [review]
I support the idea to use more precise libraries. But have you tested it? How about `netty-common`? Anything else?

**Comment by suztomo** [comment]
> But have you tested it?

It compiles successfully. I added the list of packages and artifacts relationship. I didn't find netty-common needed.

**Comment by rstoyanchev** [comment]
This has been rebased and merged 21d390a01860fc89856750dd6c836ea2205bb023.

**Comment by suztomo** [comment]
Thank you.

**Pull request closed without merging**
