### PR TITLE
Fix a typo in ValidationUtils.java

### PR DESCRIPTION
**Pull request by QBNemo**
javadoc typo

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@QBNemo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1354)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1354) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@QBNemo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1354)!

**Review by praveendandu — APPROVED** [review]
looks good

**Comment by snicoll** [comment]
Merged, thank you!

**Pull request closed without merging**
