### PR TITLE
Polishing 'Enhancer'

### PR DESCRIPTION
**Pull request by ijliym**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ijliym Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23146)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23146) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ijliym Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23146)!

**Comment by sbrannen** [comment]
Hi @ijliym,

Thanks for the PR.

Please note, however, that the `Enhancer` class is from our repackaged version of the original code from the CGLIB project. 

As such, we do not apply such changes to that repackaged code.

**Comment by ijliym** [comment]
Okay, I got it. Thanks for your advice!

**Pull request closed without merging**
