### PR TITLE
Use switch expression where feasible

### PR DESCRIPTION
**Pull request by quaff**

### CODE REVIEW

**Comment by sbrannen** [comment]
This has been merged into `main` in 490b5c77fc7bc504a03792f5690189c3429b4ff0 and revised in d71853f1054ff6b5e86e7c43db54ad955853bac6.

Thanks

----

FYI: I unfortunately had to revert two sets of changes due to bugs in the Eclipse compiler (see b69e5acfe3e16f282f2f5a7bbb04c624cf9e6df9). Once those bugs have been fixed we can consider reintroducing those changes.

**Comment by quaff** [comment]
> FYI: I unfortunately had to revert two sets of changes due to bugs in the Eclipse compiler (see [b69e5ac](https://github.com/spring-projects/spring-framework/commit/b69e5acfe3e16f282f2f5a7bbb04c624cf9e6df9)). Once those bugs have been fixed we can consider reintroducing those changes.

See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1394

**Comment by sbrannen** [comment]
> See [eclipse-jdt/eclipse.jdt.core#1394](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1394)

Thanks for the link, @quaff. 👍 

Unfortunately that seems slightly different from what I encountered, so I reported our use case separately.

- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1686

Note that the example I submitted for that Eclipse issue was based on an extremely simplified version of `SharedConnectionInvocationHandler#invoke(Object, Method, Object[])`.

**Comment by sbrannen** [comment]
> FYI: I verified that ControllerMethodInvocationInterceptor caused that issue I linked.

Thanks for confirming that! 👍 

Now we know that we're waiting on both of those issues to be resolved.

**Pull request closed without merging**
