### PR TITLE
SPR-14818 - Add exception MissingServletRequestHeaderException

### PR DESCRIPTION
**Pull request by AustinSong**
Reason : I am implementing a Restful API and needed to add a custom header value to all responses.  Some endpoint contained required request headers and wanted to customize the output for the specific situation of missing header values, by handling a more specific exception than ServletRequestBindingException.

General usage benefit: This is more consistent with the implementation of required request parameters.  There exists a MissingServletRequestParameterException for the specific situation of missing required request parameters.  A more specific exception is beneficial.

Issue: SPR-14818

I have agreed to the ICLA.

### CODE REVIEW

**Comment by mathieuales** [comment]
Great !
Which is the minimal release for this new feature ?

**Comment by snicoll** [comment]
@mathieuales the PR is still open (and so is [the Jira issue](https://jira.spring.io/browse/SPR-14818). In other words, it's not available yet.

**Comment by radarsh** [comment]
Why is this issue still unresolved?

**Comment by AustinSong** [comment]
https://jira.spring.io/browse/SPR-14818

The JIRA ticket seems to be tied to a different pull request, is that intentional?  Are we looking to go with a more generic message?

**Comment by FancyCoder0** [comment]
Dear Austin,

We are working on identifying redundant development and duplicated pull requests. We have found there is a pull request: https://github.com/spring-projects/spring-framework/pull/1653 which might be a potentially duplicate to this one. We would really appreciate if you could help us to validate and give us feedback.

Thank you very much for your time!

Sincerely,
Luyao

**Comment by AustinSong** [comment]
Hey Luyao,

These pull requests do appear to be duplicates, with some caveats.  The other [#1653](https://github.com/spring-projects/spring-framework/pull/1653) appears to be more of a generic exception covering several different missing header values.  While an improvement, it still leaves ambiguity.  This pull request specifically,  is only dealing with the case of missing headers.  I believe it would be beneficial to include specific exceptions being more explicit for common cases.  The fact that it's done for request parameters leads me to also believe this is the favorable approach.

Hope this helps!

Best,
Austin

**Comment by izeye** [comment]
[The referenced Jira issue](https://jira.spring.io/browse/SPR-14818) has been resolved, so this PR looks closable.

**Comment by snicoll** [comment]
Indeed, good catch again @izeye

**Pull request closed without merging**
