### PR TITLE
Small polish of code in spring-core

### PR DESCRIPTION
**Pull request by divcon**
This PR is to polish the code a bit.

### CODE REVIEW

**Comment by quaff** [comment]
The code originate from `asm` project not `springframework` self.

**Comment by divcon** [comment]
> The code originate from `asm` project not `springframework` self.

You mean that this pr is not valid in spring framework project?

**Comment by quaff** [comment]
> > The code originate from `asm` project not `springframework` self.
> 
> Does it mean that this pr is not valid in spring framework project?

I think so.

**Comment by divcon** [comment]
> > > The code originate from `asm` project not `springframework` self.
> > 
> > 
> > Does it mean that this pr is not valid in spring framework project?
> 
> I think so.

Thanks for your comment.
Then I will close this issue.

**Pull request closed without merging**
