### PR TITLE
Allow UriTemplate to be built with an empty template

### PR DESCRIPTION
**Pull request by bsgrd**
Fixes spring-cloud/spring-cloud-gateway#3201

### CODE REVIEW

**Comment by jhoeller** [comment]
@bsgrd has this been tried with Spring Cloud Gateway already? If this change is definitely sufficient for the purposes there, that would be great to know. Also, do you happen to have any unit tests for the empty template case, e.g. for `UriTemplateTests`?

Last but not least, it would be great to rebase this PR onto our 6.1.x branch since that is were it would get merged first.

**Comment by jhoeller** [comment]
Just added a few unit tests to `UriTemplateTests` locally, seems to work fine so far. No need to go to extra lengths on your side if you don't have any existing unit tests, I'd be happy to add mine then.

It would be great to know whether this works with Spring Cloud Gateway, in any case. And it would help to have the PR rebased onto 6.1.x, we could merge it for tomorrow's 6.1.5 release then.

**Comment by bsgrd** [comment]
@jhoeller Thank you for your feedback.
I have added the unittest I made when making the changes. If you have tests that are more comprehensive, feel free to push 😊
Regarding the rebase, can I just change the target branch in the PR to 6.1.x?

**Comment by jhoeller** [comment]
@bsgrd thanks that helps. As for the rebase, no worries, we'll handle that on our side.

**Comment by snicoll** [comment]
@bsgrd thanks very much for making your first contribution to Spring Framework.

**Pull request closed without merging**
