### PR TITLE
Inconsistent use of getInterfaceMethodIfPossible for init method invocation

### PR DESCRIPTION
**Pull request by AlexRenCN**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@AlexRenCN Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23323)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23323) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@AlexRenCN Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23323)!

**Comment by sbrannen** [comment]
Related to gh-22939

**Comment by sbrannen** [comment]
This has been merged into `5.1.x` in commit f92b60c08f462bb8867208d7d65b57f0623a6de9.

Thanks

**Comment by jhoeller** [comment]
I'm afraid this change is the wrong way round: `getInterfaceMethodIfPossible` needs to be consistently applied both with and without a `SecurityManager` since it is primarily there for visibility limitations in the Java 9 module system, just like the equivalent check in `DisposableBeanAdapter`. From that perspective, this is a bug that we need to fix, referring to `methodToInvoke` instead of plain `initMethod` in the `else` block as well. I'll change the title of this ticket accordingly.

**Pull request closed without merging**
