### PR TITLE
remove ignored files

### PR DESCRIPTION
**Pull request by Pankraz76**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@punkratz312 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1799)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1799) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@punkratz312 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1799)!

**Comment by snicoll** [comment]
@punkratz312 it looks like this was opened by mistake. Also, you can't really push a PR that you didn't authored (as it looks like the author of the commit is a different person).

**Comment by punkratz312** [comment]
@snicoll why do you think this was an mistake? The commit is actually from me, i just had some other git settings. Is this an problem?

**Comment by snicoll** [comment]
It's fine I suppose, we get a lot of PRs opened by mistake and when the commit didn't match the author of the PR, I thought maybe that was one more.

**Comment by punkratz312** [comment]
@snicoll ok, thanks.

**Pull request closed without merging**
