### PR TITLE
Stop the started LifeCycle when start any LifeCycle failed

### PR DESCRIPTION
**Pull request by wangkaish**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wangkaish Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26280)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26280) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wangkaish Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26280)!

**Comment by quaff** [comment]
You should  describe your purpose.

**Comment by wangkaish** [comment]
> You should describe your purpose.

I dont konw if there is a bug, but when some LifeCycle start failed, the others LifeCycle did not do stop. I will create a testcase in a while.

**Comment by wangkaish** [comment]
Hi @quaff, I create a project to show LifeCycle is not work as expect, Run `test.Main` to start the project, `test.StepOne` start first, `test.StepTwo` will start failed, but the `test.StepOne` did not stop, code at https://github.com/wangkaish/test-spring-lifecycle

**Comment by quaff** [comment]
> > You should describe your purpose.
> 
> I dont konw if there is a bug, but when some LifeCycle start failed, the others LifeCycle did not do stop. I will create a testcase in a while.

It make sense that application fail-fast if any `LifeCycle` start failed, I'm not sure started `LifeCycle` should be stopped if application start failed, waiting for @jhoeller's explanation.

**Comment by wangkaish** [comment]
> > > You should describe your purpose.
> > 
> > 
> > I dont konw if there is a bug, but when some LifeCycle start failed, the others LifeCycle did not do stop. I will create a testcase in a while.
> 
> It make sense that application fail-fast if any `LifeCycle` start failed, I'm not sure started `LifeCycle` should be stopped if application start failed, waiting for @jhoeller's explanation.

If `test.StepOne` start some `Thread`, the java process will not exit normally.

**Comment by snicoll** [comment]
Thanks for the PR but catching an exception on startup and calling stop is not something we should be doing. A failure to start should fail fast as @quaff mentioned. If you want us to explore a particular problem, please create a separate issue with a small sample we can run ourselves and we can have a look to it.

**Pull request closed without merging**
