### PR TITLE
Fix broken Javadoc related to `<` and `>`

### PR DESCRIPTION
**Pull request by izeye**

### CODE REVIEW

**Comment by sbrannen** [comment]
Hi @izeye,

Have you signed the [CLA](https://support.springsource.com/spring_committer_signup)?

**Comment by izeye** [comment]
@sbrannen I'm not sure I've done it before so I did it just now :smile:

**Comment by sbrannen** [comment]
OK. Thanks!

**Comment by izeye** [comment]
@sbrannen Done!

**Comment by sdeleuze** [comment]
Merged, thanks!

**Pull request closed without merging**
