### PR TITLE
Ensure pre-flight request does not return error code 401

### PR DESCRIPTION
**Pull request by rolaca11**
Based on issue: https://github.com/spring-projects/spring-framework/issues/23752

Provides a test, which shows exactly in what conditions does the issue arises and provides a fix to that issue.

### CODE REVIEW

**Comment by rstoyanchev** [comment]
If I understand correctly from the description under #23752 there is a 401 error during the pre-flight request, and then as part of error handling (in an ERROR dispatch) you want the `DefaultCorsProcessor` to reset the status to 200? 

It doesn't seem right that `DefaultCorsProcessor` should be overriding the response status unconditionally but I'll defer for an opinion from the Spring Security team.

**Comment by jgrandja** [comment]
@rolaca11 Did you see my [comment](https://github.com/spring-projects/spring-security-oauth/pull/1750#issuecomment-534095415)? The flow you are implementing has security issues. Please see my comment for alternative solution.

**Comment by rstoyanchev** [comment]
I'm closing this as I don't think it makes sense for DefaultCorsProcessor to be setting the response status.

**Comment by rolaca11** [comment]
I'm sorry, didn't really have time to respond, was busy. The reason why the
DefaultCorsProcessor should set the status code is because in some cases
preflight requests are sent to a resource that requires an authenticated
user to access. However, preflight requests are not sent with
Authentication headers.

In this case, the AffirmationVoter (or whichever is active) will of course
deny access and set the status code to 401. Understandable, since the
request is not authenticated.

But this status code is inherited, when the request gets to the cors
processor, so the sender of the preflight request sees that the given
resource is not accessible because of the status code, when in reality, the
client has a valid token, it just doesn't send it for a preflight request.

Maybe my solution is too cut in stone and would require a bit more
configurability tho. I'm down to helping you guys, I just have a busy week
behind and towards me.



Rossen Stoyanchev <notifications@github.com> ezt írta (időpont: 2019. nov.
8., P 16:37):

**Comment by rstoyanchev** [comment]
I do not consider this something to be resolved on the Spring Framework side at this point. Please, see the comment and link by @jgrandja above and follow through on that discussion rather than opening additional tickets.

**Pull request closed without merging**
