### PR TITLE
Use Collection.removeIf() where possible

### PR DESCRIPTION
**Pull request by dreis2211**
Issue: https://jira.spring.io/browse/SPR-16622

### CODE REVIEW

**Comment by jhoeller** [comment]
This looks good to me in general. However, there's a dangling ` import java.util.Objects` in the otherwise unmodified `DefaultSubscriptionRegistry`; was this meant to be used or simply an accident?

**Comment by dreis2211** [comment]
Sorry, my mistake. Was added by accident.

**Comment by jhoeller** [comment]
No worries... could you just drop that `DefaultSubscriptionRegistry` change from the pull request maybe? That would allow for merging your PR right away.

**Comment by dreis2211** [comment]
Done. I also found two additional occurences in the meanwhile - not sure why I missed those before :/

**Comment by jhoeller** [comment]
Alright, thanks for spotting those!

**Pull request merged**
