### PR TITLE
Provide Go-style interface and implement independent type conversion …

### PR DESCRIPTION
**Pull request by cshijiel**
…strategy, for bean injection in different type.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cshijiel Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25114)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25114) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@cshijiel Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25114)!

**Comment by quaff** [comment]
It make no sense and error prone.

**Comment by cshijiel** [comment]
> It make no sense and error prone.

Go provides this style, Maybe Java user also need it.

**Comment by quaff** [comment]
> > It make no sense and error prone.
> 
> Go provides this style, Maybe Java user also need it.

Duck typing is not accepted in java world, use lambda expression with method reference instead.

**Comment by cshijiel** [comment]
> > > It make no sense and error prone.
> > 
> > 
> > Go provides this style, Maybe Java user also need it.
> 
> Duck typing is not accepted in java world, use lambda expression with method reference instead.

Got it. Thanks a lot!
"Duck typing" so interesting!

**Comment by bclozel** [comment]
Thanks for your contribution, but this style is not currently widely adopted in the Java ecosystem and we're not considering this right now.

**Pull request closed without merging**
