### PR TITLE
section 3.2.5 : typo correction

### PR DESCRIPTION
**Pull request by akmalick**
Kindly review:
Corrected a typo for section 3.2.5.
 Was : each **entry** in the map 
 Should be : each **key** in the map

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@akmalick Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1874)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1874) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@akmalick Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1874)!

**Comment by sbrannen** [comment]
Thanks for submitting the PR.

I've addressed this slightly differently in 8d092227993f5a7ab3149e4c5fd9b379772d7d15.

**Comment by akmalick** [comment]
@sbrannen 
This was my first PR, though a quite small contribution. :) Thank you so much for your kind attention.
This is quite motivating for me.

**Pull request closed without merging**
