### PR TITLE
SPR-17600 Vararg based methods in MessageSource

### PR DESCRIPTION
**Pull request by ankurpathak**
It adds a vararg based getMessage methods
in MessageSource. The methods are added using
Java 8 Interface Default Methods so doesn't
need any implementation in any concrete
MessageSource.

### CODE REVIEW

**Comment by ankurpathak** [comment]
Pull request for Jira issue:
https://jira.spring.io/browse/SPR-17600

**Comment by ankurpathak** [comment]
@jhoeller Can we merge it as it will make useing MessageSource much more elegant.

**Comment by ankurpathak** [comment]
@jhoeller Can you please review this request, as its a long pending issue.

**Comment by bclozel** [comment]
I don't think we should add those variants as it will make IDE auto-completion noisy.
Thanks!

**Pull request closed without merging**
