### PR TITLE
Feauture 20191009 fix log

### PR DESCRIPTION
**Pull request by wycm**
optimize the info log

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wycm Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23773)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23773) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wycm Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23773)!

**Comment by wycm** [comment]
> What's the point?

Determine whether the info level log is enabled

**Comment by rstoyanchev** [comment]
We only check the log level explicitly when Object creation can be avoided but in this case the message is a constant. The log level is still checked internally.

**Pull request closed without merging**
