### PR TITLE
Spr 15950 PathMatchingResourcePatternResolver.java cannot find any resources in jar file in weblogic and websphere

### PR DESCRIPTION
**Pull request by kk580kk**
In my project, I used this code to find resources in jar file. It works nice in tomcat and spring-boot:run but cannot find any resources in jar file in weblogic and websphere . So by read this stackoverflow https://stackoverflow.com/questions/17429736/spring-configuration-files-loading-not-working-on-websphere-7 I think rewrite PathMatchingResourcePatternResolver() maybe the best answer. Issue: SPR-15950 huangjie 2017/9/11 09:29

### CODE REVIEW

**Comment by kk580kk** [comment]
https://jira.spring.io/browse/SPR-15950

**Comment by rstoyanchev** [comment]
The entire source file is modified to use spaces. Can you fix your pull request to use tabs (as it was before) so it is possible to see what actually changed?

**Comment by kk580kk** [comment]
@rstoyanchev 
I'll try  to use tabs

**Comment by kk580kk** [comment]
@rstoyanchev I have formatted the code now

**Review by lqjack — COMMENTED** [review]
the exception should be throw and not swallow .

file scan can reuse the function framework provided

**Comment by kk580kk** [comment]
In this situation catch the MalformedURLException  and fall back to normal function is the best choice. This change only for websphere and weblogic. @lqjack 
Reuse the function framework provided maybe better answer. But could you tell me which function?

**Comment by snicoll** [comment]
Closing as discussed in the related issue, https://github.com/spring-projects/spring-framework/issues/20502#issuecomment-981779101

**Pull request closed without merging**
