### PR TITLE
Optimize PostProcessorRegistrationDelegate's invokeBeanFactoryPostProcessors()

### PR DESCRIPTION
**Pull request by zhuyuehui**
#26177
opt invokeBeanFactoryPostProcessors

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@zhuyuehui Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26198)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26198) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@zhuyuehui Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26198)!

**Comment by pivotal-issuemaster** [comment]
@zhuyuehui Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26198)!

**Comment by sbrannen** [comment]
Thanks for PR.

Unfortunately, the proposal changes the order in which the `PriorityOrdered` and `Ordered` `BeanDefinitionRegistryPostProcessor`s are instantiated which constitutes a breaking change.

In light of that, I am closing this PR.

For additional information, please see https://github.com/spring-projects/spring-framework/pull/26273#issuecomment-751179375.

**Pull request closed without merging**
