### PR TITLE
 Update documentation according to Testcontainers example

### LINKED ISSUE #29936: Update documentation according to testcontainer example
According to the testcontainer example the container should be started first. Otherwise it could lead to container port mapping problems.
See: https://github.com/testcontainers/testcontainers-java/blob/main/examples/spring-boot/src/test/java/com/example/AbstractIntegrationTest.java

### PR DESCRIPTION
**Pull request by samuelstein**
Update documentation according to testcontainer example. Fix #29936

### CODE REVIEW

**Comment by sbrannen** [comment]
The container in the example does not need to be manually started since the JUnit Jupiter extension behind the `@Testcontainers` annotation handles that for you. In light of that, I am closing this PR.

However, this PR did inspire me to review the examples which resulted in #29940.

Thanks,

Sam

**Comment by samuelstein** [comment]
The thing is, that if you don't start the container explicitly in the DynamicPropertySource hook it's possible that you run in an timing issue when the hook will be called earlier than the container is started by the JUnit extension and this will result in an "Mapped port can only be obtained after the container is started" error.
The start method of the container will check anyway if the container is already started.
So calling the start method explicit will only make the process more robust and has no negative consequences i would say.
What do you think?

**Comment by sbrannen** [comment]
@eddumelendez, what are your thoughts on the matter?

**Comment by eddumelendez** [comment]
Hi, the javadoc is using `Testcontainers` and `Container` annotations. Those are part of the junit-jupiter integration and the container will start without calling `start()` method. So, the change doesn't apply.

**Comment by sbrannen** [comment]
Thanks for confirming that, @eddumelendez.

**Pull request closed without merging**
