### PR TITLE
Switch data sources smoothly

### PR DESCRIPTION
**Pull request by TurboTurn**
If we have thousands of DataSources, when resolvedDefaultDataSource is putting DataSource to map, other threads cannot get the DataSources from previous map

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@TurboTurn Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25583)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25583) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@TurboTurn Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25583)!

**Comment by quaff** [comment]
Bean will not be available until `afterPropertiesSet` called, so It's safe already.

**Comment by TurboTurn** [comment]
> Bean will not be available until `afterPropertiesSet` called, so It's safe already.

**Comment by TurboTurn** [comment]
> Bean will not be available until `afterPropertiesSet` called, so It's safe already.

How do you guarantee it? My project has encountered this problem.

**Comment by quaff** [comment]
> > Bean will not be available until `afterPropertiesSet` called, so It's safe already.
> 
> How do you guarantee it? My project has encountered this problem.

Spring will guarantee it, please show your code snippet

**Comment by TurboTurn** [comment]
> > > Bean will not be available until `afterPropertiesSet` called, so It's safe already.
> > 
> > 
> > How do you guarantee it? My project has encountered this problem.
> 
> Spring will guarantee it, please show your code snippet

I need to add and delete DataSources dynamically at runtime, and I call the 'afterPropertiesSet' manually. How will Spring 
 guarantee it

**Comment by quaff** [comment]
> > > > Bean will not be available until `afterPropertiesSet` called, so It's safe already.
> > > 
> > > 
> > > How do you guarantee it? My project has encountered this problem.
> > 
> > 
> > Spring will guarantee it, please show your code snippet
> 
> I need to add and delete DataSources dynamically at runtime, and I call the 'afterPropertiesSet' manually. How will Spring
> guarantee it

You should create your own implementation extends this class, add a new method such as `public void rebuild(){}`.

**Comment by TurboTurn** [comment]
> > > > > Bean will not be available until `afterPropertiesSet` called, so It's safe already.
> > > > 
> > > > 
> > > > How do you guarantee it? My project has encountered this problem.
> > > 
> > > 
> > > Spring will guarantee it, please show your code snippet
> > 
> > 
> > I need to add and delete DataSources dynamically at runtime, and I call the 'afterPropertiesSet' manually. How will Spring
> > guarantee it
> 
> You should create your own implementation extends this class, add a new method such as `public void rebuild(){}`.


> > > > > Bean will not be available until `afterPropertiesSet` called, so It's safe already.
> > > > 
> > > > 
> > > > How do you guarantee it? My project has encountered this problem.
> > > 
> > > 
> > > Spring will guarantee it, please show your code snippet
> > 
> > 
> > I need to add and delete DataSources dynamically at runtime, and I call the 'afterPropertiesSet' manually. How will Spring
> > guarantee it
> 
> You should create your own implementation extends this class, add a new method such as `public void rebuild(){}`.

I have extends `AbstractRoutingDataSource`, but `resolvedDataSources` is private, I can only call `setTargetDataSources` and `afterPropertiesSet`, even if i add method rebuild(), i can not access to `resolvedDataSources`.

**Comment by quaff** [comment]
> > > > > > Bean will not be available until `afterPropertiesSet` called, so It's safe already.
> > > > > 
> > > > > 
> > > > > How do you guarantee it? My project has encountered this problem.
> > > > 
> > > > 
> > > > Spring will guarantee it, please show your code snippet
> > > 
> > > 
> > > I need to add and delete DataSources dynamically at runtime, and I call the 'afterPropertiesSet' manually. How will Spring
> > > guarantee it
> > 
> > 
> > You should create your own implementation extends this class, add a new method such as `public void rebuild(){}`.
> 
> > > > > > Bean will not be available until `afterPropertiesSet` called, so It's safe already.
> > > > > 
> > > > > 
> > > > > How do you guarantee it? My project has encountered this problem.
> > > > 
> > > > 
> > > > Spring will guarantee it, please show your code snippet
> > > 
> > > 
> > > I need to add and delete DataSources dynamically at runtime, and I call the 'afterPropertiesSet' manually. How will Spring
> > > guarantee it
> > 
> > 
> > You should create your own implementation extends this class, add a new method such as `public void rebuild(){}`.
> 
> I have extends `AbstractRoutingDataSource`, but `resolvedDataSources` is private, I can only call `setTargetDataSources` and `afterPropertiesSet`, even if i add method rebuild(), i can not access to `resolvedDataSources`.

I think changing the modifier of `resolvedDataSources` from `private` to `protected` is much better.

**Comment by TurboTurn** [comment]
spring team may not

**Comment by snicoll** [comment]
thanks for the PR but we can't accept a code change that has no additional tests to exercise what was changed. Thanks anyway.

**Pull request closed without merging**
