### PR TITLE
Fix typo in core-beans.adoc (Obvious Fix)

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@PascalSchumacher Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2036)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2036) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by bclozel** [comment]
Hello @PascalSchumacher , this looks like [an obvious fix](https://cla.pivotal.io/about) so you don't need to sign the CLA if your PR comment mentions that.

**Comment by pivotal-issuemaster** [comment]
@PascalSchumacher This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by snicoll** [comment]
@pivotal-issuemaster this is an obvious fix

**Pull request merged**
