### PR TITLE
Create XML NamespaceHandler as singleton

### PR DESCRIPTION
**Pull request by y987425112**
In some cases, the existing mechanism for creating a `NamespaceHandler` may result in repeated creation of the handler.

This PR changes the mechanism so that each `NamespaceHandler` is created as a singleton.

### CODE REVIEW

**Comment by sbrannen** [comment]
> In some cases, the existing mechanism for creating a `NamespaceHandler` may result in repeated creation of the handler.

Do you have a concrete use case where this is problematic?

In other words, what is the rationale for your proposed change?

**Comment by y987425112** [comment]
This is old code

`public NamespaceHandler resolve(String namespaceUri) {
		Map<String, Object> handlerMappings = getHandlerMappings();
		Object handlerOrClassName = handlerMappings.get(namespaceUri);
		if (handlerOrClassName == null) {
			return null;
		}
		else if (handlerOrClassName instanceof NamespaceHandler) {
			return (NamespaceHandler) handlerOrClassName;
		}
		else {
			String className = (String) handlerOrClassName;
			try {
				Class<?> handlerClass = ClassUtils.forName(className, this.classLoader);
				if (!NamespaceHandler.class.isAssignableFrom(handlerClass)) {
					throw new FatalBeanException("Class [" + className + "] for namespace [" + namespaceUri +
							"] does not implement the [" + NamespaceHandler.class.getName() + "] interface");
				}
				NamespaceHandler namespaceHandler = (NamespaceHandler) BeanUtils.instantiateClass(handlerClass);
				namespaceHandler.init();
				handlerMappings.put(namespaceUri, namespaceHandler);
				return namespaceHandler;
			}
			catch (ClassNotFoundException ex) {
				throw new FatalBeanException("Could not find NamespaceHandler class [" + className +
						"] for namespace [" + namespaceUri + "]", ex);
			}
			catch (LinkageError err) {
				throw new FatalBeanException("Unresolvable class definition for NamespaceHandler class [" +
						className + "] for namespace [" + namespaceUri + "]", err);
			}
		}
	}`

When the type of handlerOrClassName is NamespaceHandler, end the method and no new NamespaceHandler will be created. However, if two threads run at the same time and both determine that the type of handlerOrClassName is not NamespaceHandler, the following code will run at the same time and create namespacehandler twice
`else {
			String className = (String) handlerOrClassName;
			try {
				Class<?> handlerClass = ClassUtils.forName(className, this.classLoader);
				if (!NamespaceHandler.class.isAssignableFrom(handlerClass)) {
					throw new FatalBeanException("Class [" + className + "] for namespace [" + namespaceUri +
							"] does not implement the [" + NamespaceHandler.class.getName() + "] interface");
				}
				NamespaceHandler namespaceHandler = (NamespaceHandler) BeanUtils.instantiateClass(handlerClass);
				namespaceHandler.init();
				handlerMappings.put(namespaceUri, namespaceHandler);
				return namespaceHandler;
			}
			catch (ClassNotFoundException ex) {
				throw new FatalBeanException("Could not find NamespaceHandler class [" + className +
						"] for namespace [" + namespaceUri + "]", ex);
			}
			catch (LinkageError err) {
				throw new FatalBeanException("Unresolvable class definition for NamespaceHandler class [" +
						className + "] for namespace [" + namespaceUri + "]", err);
			}
		}`

**Comment by y987425112** [comment]
No one responded??

**Comment by snicoll** [comment]
There's no indication that I can see that it would be problematic to create two instances. While not ideal, the complexity that the PR brings is not worth covering for this case. Thanks for the PR, in any case.

**Pull request closed without merging**
