### PR TITLE
Reduce unnecessary loops in PostProcessorRegistrationDelegate

### LINKED ISSUE #25061: i want to know how this code is designed about register BeanPostProcessors
### The code in PostProcessorRegistrationDelegate.registerBeanPostProcessors

```java
List<BeanPostProcessor> priorityOrderedPostProcessors = new ArrayList<>();
List<BeanPostProcessor> internalPostProcessors = new ArrayList<>();
List<String> orderedPostProcessorNames = new ArrayList<>();
List<String> nonOrderedPostProcessorNames = new ArrayList<>();
for (String ppName : postProcessorNames) {
    if (beanFactory.isTypeMatch(ppName, PriorityOrdered.class)) {
        BeanPostProcessor pp = beanFactory.getBean(ppName, BeanPostProcessor.class);
        priorityOrderedPostProcessors.add(pp);
        if (pp instanceof MergedBeanDefinitionPostProcessor) {
            internalPostProcessors.add(pp);
        }
    }
    else if (beanFactory.isTypeMatch(ppName, Ordered.class)) {
        orderedPostProcessorNames.add(ppName);
    }
    else {
        nonOrderedPostProcessorNames.add(ppName);
    }
}

// First, register the BeanPostProcessors that implement PriorityOrdered.
sortPostProcessors(priorityOrderedPostProcessors, beanFactory);
registerBeanPostProcessors(beanFactory, priorityOrderedPostProcessors);

// Next, register the BeanPostProcessors that implement Ordered.
List<BeanPostProcessor> orderedPostProcessors = new ArrayList<>(orderedPostProcessorNames.size());
for (String ppName : orderedPostProcessorNames) {
    BeanPostProcessor pp = beanFactory.getBean(ppName, BeanPostProcessor.class);
    orderedPostProcessors.add(pp);
    if (pp instanceof MergedBeanDefinitionPostProcessor) {
        internalPostProcessors.add(pp);
    }
}
sortPostProcessors(orderedPostProcessors, beanFactory);
registerBeanPostProcessors(beanFactory, orderedPostProcessors);
```
I want to know how this code is designed，can i get the Ordered beans in the for loop and add them to the list, just like the way handler PriorityOrdered type.

So we can reduce more then one cycle.

### My example is as follow:

```java
List<BeanPostProcessor> priorityOrderedPostProcessors = new ArrayList<>();
List<BeanPostProcessor> orderedPostProcessors = new ArrayList<>();
List<BeanPostProcessor> nonOrderedPostProcessors = new ArrayList<>();
List<BeanPostProcessor> internalPostProcessors = new ArrayList<>();
for (String ppName : postProcessorNames) {
    BeanPostProcessor pp = beanFactory.getBean(ppName, BeanPostProcessor.class);
    if (beanFactory.isTypeMatch(ppName, PriorityOrdered.class)) {
        priorityOrderedPostProcessors.add(pp);
    }
    else if (beanFactory.isTypeMatch(ppName, Ordered.class)) {
        orderedPostProcessors.add(pp);
    }
    else {
        nonOrderedPostProcessors.add(pp);
    }
    if (pp instanceof MergedBeanDefinitionPostProcessor) {
        internalPostProcessors.add(pp);
    }
}

// First, register the BeanPostProcessors that implement PriorityOrdered.
sortPostProcessors(priorityOrderedPostProcessors, beanFactory);
registerBeanPostProcessors(beanFactory, priorityOrderedPostProcessors);

// Next, register the BeanPostProcessors that implement Ordered.
sortPostProcessors(orderedPostProcessors, beanFactory);
registerBeanPostProcessors(beanFactory, orderedPostProcessors);

// Now, register all regular BeanPostProcessors.
registerBeanPostProcessors(beanFactory, nonOrderedPostProcessors);

// Finally, re-register all internal BeanPostProcessors.
sortPostProcessors(internalPostProcessors, beanFactory);
registerBeanPostProcessors(beanFactory, internalPostProcessors);
```

### PR DESCRIPTION
**Pull request by diguage**
Fix for #25061

### CODE REVIEW

**Comment by hzmpay** [comment]
About invokeBeanFactoryPostProcessors methods of refactor in #22810 has been rejected

**Comment by hzmpay** [comment]
I want to reply registerBeanPostProcessors methods  of refactor  should be the same.

**Comment by hzmpay** [comment]
I think to reply registerBeanPostProcessors methods  of refactor  should be the same.

**Comment by sbrannen** [comment]
Thanks for PR.

Unfortunately, the proposal constitutes breaking changes.

In light of that, I am closing this PR.

For additional information, please see https://github.com/spring-projects/spring-framework/pull/22810#issuecomment-485730890 and https://github.com/spring-projects/spring-framework/pull/26273#issuecomment-751179375.

**Pull request closed without merging**
