### PR TITLE
SPR-16690 - Remove duplicate RestTemplate headers

### PR DESCRIPTION
**Pull request by geo-m**
Remove duplicate accept header information.

https://jira.spring.io/browse/SPR-16690

### CODE REVIEW

**Comment by snicoll** [comment]
@geo-m we need a Jira issue to discuss this change. Can you please [create  one](https://jira.spring.io/browse/SPR)?

**Comment by geo-m** [comment]
@snicoll , @jhoeller  If i understand correctly by your comments, existing Jira issues are reserved for the team, and any PR by the community has to be a new suggested change? Wanted to familiarize myself with the code by starting with something trivial, my bad.

**Comment by rstoyanchev** [comment]
@geo-m, you did nothing wrong.

**Comment by sbrannen** [comment]
@geo-m, please have a look at the [CONTRIBUTING guidelines](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md) to see if that document answers your questions. 

If it doesn't, feel free to ask for clarifications.

**Comment by geo-m** [comment]
@sbrannen , the guidelines were crystal clear. I was just initially confused by the 2 comments, but all seems to be fine. Thanks for linking the PR in Jira.

**Comment by snicoll** [comment]
@geo-m your original PR had no reference to a Jira issue and no indication you had created one. I just mentioned that we need one as we prefer to keep track of changes (and discussion) on Jira. Turns out that an issue already existed that I wasn't aware of.

I hope that clarifies. Thank you.

**Comment by luyuanwan** [comment]
How can I contribute to the Project? What should I do first ?

**Comment by bclozel** [comment]
I've solved this with a more comprehensive revision of that part of the codebase (see 69e3fde295).

Thanks for your contribution @geo-m, don't hesitate to send more PRs our way!

**Pull request closed without merging**
