### PR TITLE
Fix for ScriptUtils failure when '--' occurs inside a multi-line comment on the same line as '*/'

### PR DESCRIPTION
**Pull request by mmustaquim**
Pull request against issue #22388

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mmustaquim Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22392)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22392) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mmustaquim Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22392)!

**Comment by jhoeller** [comment]
Merged and therefore part of 5.1.5 :-) Thanks for the PR!

**Comment by mmustaquim** [comment]
Cool. I didn't expect to move this quickly from issue to submission. Looking forward to the 5.1.5 release. Cheers!

**Pull request merged**
