### PR TITLE
Fix interface and class names in examples in core-aop doc

### PR DESCRIPTION
**Pull request by maksimkoniukhau**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@MaksimKoniukhov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25351)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25351) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@MaksimKoniukhov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25351)!

**Comment by MaksimKoniukhov** [comment]
This PR for #25347 issue

**Comment by sbrannen** [comment]
This has been merged into `5.x.2` and `master`.

Thanks

**Pull request closed without merging**
