### PR TITLE
Simplify BeanUtils.findPrimaryConstructor()

### PR DESCRIPTION
**Pull request by 1993heqiang**
Simplified code.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@1993heqiang Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26519)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26519) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@1993heqiang Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26519)!

**Comment by sbrannen** [comment]
This has been merged into `master`.

Thanks

**Comment by xhd731568849** [comment]
good

**Pull request merged**
