### PR TITLE
SPR-17402: Support list in IN clause in NamedParameterJdbcTemplate.batchUpdate

### PR DESCRIPTION
**Pull request by Fuud**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Fuud Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1997)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1997) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Fuud Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1997)!

**Comment by jhoeller** [comment]
As mentioned on JIRA, I went with a more extensive refactoring of the affected code, inspired by your proposal. Thanks for the PR, in any case!

**Comment by Fuud** [comment]
Just for history: functionality was committed as a3d763d1

**Pull request closed without merging**
