### PR TITLE
JDK 11 HttpClient integration with WebClient

### LINKED ISSUE #21014: JDK 11 HttpClient integration with WebClient [SPR-16469]
**[Rossen Stoyanchev](https://jira.spring.io/secure/ViewProfile.jspa?name=rstoya05-aop)** opened **[SPR-16469](https://jira.spring.io/browse/SPR-16469?redirect=false)** and commented

According to this [blog post](http://openjdk.java.net/groups/net/httpclient/intro.html) the HttpClient "handles request and response bodies as reactive-streams", and it is currently in [incubation status](http://http://openjdk.java.net/jeps/11), but will be made official in JDK 11 when it will switch to `java.net` from `jdk.incubator`.

Given the JDK 11 release dates, this is probably a 5.2 target. However, at present, we need to experiment with the proposed API to see if there any issues in adapting it through a `ClientHttpConnector`, and raise issues if necessary.

[JDK HTTP Client - JEP 321 - Update](http://mail.openjdk.java.net/pipermail/net-dev/2018-February/011155.html)

---

**Affects:** 5.0.3

**Issue Links:**
- #21016 JDK 11 WebSocket integration with WebSocketClient
- #19658 Jetty HTTP client integration with WebClient

0 votes, 6 watchers

### PR DESCRIPTION
**Pull request by Julien-Eyraud**
This a simple implementation of ClientHttpResponse that levrage
JDK 11 HttpClient.

Closes gh-21014

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Julien-Eyraud Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23432)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23432) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Julien-Eyraud Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23432)!

**Comment by rstoyanchev** [comment]
Cross-linking to #17778 that this issue depends on.

**Comment by rdsubhas** [comment]
@Julien-Eyraud amazing feature :) would be awesome to resolve conflicts and see this merged...

**Comment by Julien-Eyraud** [comment]
@rdsubhas I won't fix merge until https://github.com/spring-projects/spring-framework/issues/17778 is fixed

**Comment by candrews** [comment]
I've created a Spring Boot starter using the code from this PR: https://github.com/candrews/java-httpclient-webclient-spring-boot-starter.

It provides a really simple way to configure WebClient to use Java 11's HttpClient; just add the dependency (which I've published to [Maven Central](https://search.maven.org/artifact/com.integralblue/java-httpclient-webclient-spring-boot-starter)) to your project and you're done.

Hopefully, it helps those of us who really would like this feature hold out until it lands in Spring itself :)

**Comment by curena** [comment]
So, is this still happening?

**Comment by Julien-Eyraud** [comment]
I don't know I can update the PR to fix conflict and change the target branch. It's up to the maintainer now.

**Comment by rstoyanchev** [comment]
The `main` branch is on JDK 17 now, so we can move forward with this.

**Comment by Julien-Eyraud** [comment]
I've rebase my branch on main. I've updated the JdkClientHttpResponse#getCookies with a duplicate from JettyClientHttpResponse#parseSameSite. I didn't know where to but it to use a common code. I also updated the documentation.

**Comment by rk99d339** [comment]
I just saw your JdkClientHttpConnector pullrequest. 
Please add it here as default if no other is on the classpath org.springframework.web.reactive.function.client.DefaultWebClientBuilder.initConnector()
instead of throwing an Exception
 throw new IllegalStateException("No suitable default ClientHttpConnector found");

A problem is that child classes of AbstractWebClientReactiveOAuth2AccessTokenResponseClient
Always creates a new Webclient with: 
private WebClient webClient = WebClient.builder().build(); 
which invokes the DefaultWebClientBuilder.initConnector() leading to the IllegalStateException. 

Sincerely
Rolf

**Comment by Julien-Eyraud** [comment]
It's an interesting point @rk99d339. I'll wait for maintainer feedback. I hope I'll be able to merge soon.

**Comment by Julien-Eyraud** [comment]
Hi @rstoyanchev do you think I can have a review soon ? Or this will be discard ? What do you think about rk99d339's comment ?

**Comment by rstoyanchev** [comment]
Yes, I'm reviewing this and should have an update soon.

**Comment by rstoyanchev** [comment]
This is now in `main`. I've also made sure the JDK client is used by default when no others are present.

**Pull request closed without merging**
