### PR TITLE
Improve exception handling when clients disconnect.

### PR DESCRIPTION
**Pull request by violetagg**
Issue: SPR-14538

### CODE REVIEW

**Comment by rstoyanchev** [comment]
@violetagg regarding the logging and handling of error signals in the HttpHandler adapters (like `ServletHttpHandlerAdapter` and `UndertowHttpHandlerAdapter`), it's true that won't ever be used if an `ExceptionHandlingWebHandler` is installed which is the case by default with the `WebHttpHandlerBuilder`. However in theory one may not use that builder or may install other exception handlers and so the presence of `ExceptionHandlingWebHandler` is not 100% guaranteed.

Unless there is an issue with keeping that logic in place as a stop-gap measure, also at ERROR level since it really should not happen. I would even go add similar logging and 500 response status to the adapters for Reactor and RxNetty.

WDYT?

**Comment by violetagg** [comment]
Hi,

I reverted the changes in ```ServletHttpHandlerAdapter ``` and ```UndertowHttpHandlerAdapter ```. Should we track the changes in Reactor and RxNetty here or in another issue?

Thanks,
Violeta

**Comment by rstoyanchev** [comment]
Thanks. Fine by me to do it here. Minor in terms of changes and very closely related.

**Comment by violetagg** [comment]
Can you check the new changes?

Thanks,
Violeta

**Comment by rstoyanchev** [comment]
This is now merged in. Thank!

**Pull request closed without merging**
