### PR TITLE
Polish AbstractAspectJAdvisorFactory

### PR DESCRIPTION
**Pull request by Inmord**
Left out invoke the native method.

### CODE REVIEW

**Comment by sbrannen** [comment]
This has been merged into `main`.

Thanks for submitting your first PR to the Spring Framework! 👍

**Comment by sbrannen** [comment]
@Inmord, for future PRs, please make sure you create your PR against the `main` branch instead of the `5.2.x` branch.

Thanks

**Comment by Inmord** [comment]
Okay, thanks.

**Comment by Inmord** [comment]
> @Inmord，对于未来的 PR，请确保您针对`main`分支而不是分支创建 PR `5.2.x`。
> 
> 谢谢

Okay, thanks.

**Pull request merged**
