### PR TITLE
SPR-15742 - Add Mediatype for Nottingham Problem

### PR DESCRIPTION
**Pull request by simplicii**
Nottingham Problem Media type: application/problem+json
https://tools.ietf.org/html/rfc7807

### CODE REVIEW

**Comment by snicoll** [comment]
@simplicii please create a Jira issue for this change.

**Comment by simplicii** [comment]
SPR-15742 [https://jira.spring.io/browse/SPR-15742]

**Comment by simplicii** [comment]
@rstoyanchev Hi, why did you close with unmerged commits?

**Comment by izeye** [comment]
@simplicii Merged in https://github.com/spring-projects/spring-framework/commit/3dd6069578a2aea3f87bcfeec10d9156e038c4f5

**Comment by rstoyanchev** [comment]
The commit is in master https://github.com/spring-projects/spring-framework/commit/3dd6069578a2aea3f87bcfeec10d9156e038c4f5 and has been since July 7.

**Pull request closed without merging**
