### PR TITLE
Use StringJoiner where possible to simplify String joining

### PR DESCRIPTION
**Pull request by stsypanov**
I think this is the last change of this kind in Spring's code base

### CODE REVIEW

**Review by sbrannen — CHANGES_REQUESTED** [review]
Before we introduce these changes, we really should have some regression tests in place for the refactored functionality.

Can you please introduce unit tests for `DefaultValueStyler` that pass against the status quo and after the changes?

**Comment by stsypanov** [comment]
@sbrannen sure, I'll do it in a couple of days.

**Comment by stsypanov** [comment]
@sbrannen I've added the test

**Review by sbrannen — APPROVED** [review]

**Comment by sbrannen** [comment]
> @sbrannen I've added the test

Thanks! It's great to have those in place.

A few tips...

- test classes must end with `*Tests`
- test classes need copyright headers as well
- updated classes need to have their copyright dates updated
- import order is important
- execute `./gradlew check` to see Checkstyle violations, etc.

I've already made these changes locally and will merge soon.

**Comment by sbrannen** [comment]
This has been merged into `master` in 1d6e44ab04cc007e34c09191cd77517795cbd8ca and refined in a3c7ae2c58dc932be4f576ebbad007442aff2cff.

Thanks

**Pull request closed without merging**
