### PR TITLE
Add necessary semicolons

### PR DESCRIPTION
**Pull request by diguage**

### CODE REVIEW

**Comment by quaff** [comment]
Semicolon is not required by java enum and groovy.

**Comment by diguage** [comment]
> Semicolon is not required by java enum and groovy.

I tried it on the IDEA. It is necessary for Java enum.

**Comment by quaff** [comment]
https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html#PageContent
```java
public enum Day {
    SUNDAY, MONDAY, TUESDAY, WEDNESDAY,
    THURSDAY, FRIDAY, SATURDAY 
}
```

**Comment by diguage** [comment]
> https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html#PageContent
> 
> ```java
> public enum Day {
>     SUNDAY, MONDAY, TUESDAY, WEDNESDAY,
>     THURSDAY, FRIDAY, SATURDAY 
> }
> ```

You are right. Thanks a lot.

This is my code:

```java
public enum  Day {
	SUNDAY, MONDAY, TUESDAY, WEDNESDAY,
	THURSDAY, FRIDAY, SATURDAY

	Day() {
	}

	public static void main(String[] args) {
		System.out.println(Day.SATURDAY);
	}
}

// Then throw an error:
 error: ',', '}', or ';' expected
	Tesssst() {
	^
```

**Comment by quaff** [comment]
You should close this since semicolon is optional in groovy.

**Comment by diguage** [comment]
> You should close this since semicolon is optional in groovy.

The source blocks are Java source. So semicolons should be added.

**Comment by sbrannen** [comment]
> Semicolon is not required by java enum and groovy.

Closing this in light of the above.

**Comment by diguage** [comment]
> Closing this in light of the above.

I have removed the enum source block. 

The change is Java source block. So maybe the semicolons are necessary.

**Comment by sbrannen** [comment]
The remaining changes are in Groovy source code examples.

The fact that `java` is listed as the source type is only for syntax highlighting purposes.

**Pull request closed without merging**
