### PR TITLE
Fix typo in asciidoc

### PR DESCRIPTION
**Pull request by nkjackzhang**
Change servlet name in the code to "example", because the servlet name "example" is mentioned below.

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the PR but that's not a typo (look at the type of the servlet). `/example` is the mapping of the custom `DispatcherServlet`.

**Comment by sbrannen** [comment]
@snicoll, @nkjackzhang is correct.

Look at the subsequent text:

>  In the preceding example, all requests starting with `/example` will be handled by the
`DispatcherServlet` instance named `example`.

The instance is currently named "dispatcher" (via the `servletName` parameter to `ServletContext.addServlet(String, Servlet)`), and @nkjackzhang's PR changes it to "example" to fix the inconsistency.

**Comment by kazuki43zoo** [comment]
@snicoll, i vote @sbrannen 's comment.

Explanation for xml based configuration at under about 10 lines says as follow:

> Below is the web.xml equivalent of the above code based example:
>
> ```xml
> <web-app>
>     <servlet>
>         <servlet-name>example</servlet-name>
>         <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
>         <load-on-startup>1</load-on-startup>
>     </servlet>
> 
>     <servlet-mapping>
>         <servlet-name>example</servlet-name>
>         <url-pattern>/example/*</url-pattern>
>     </servlet-mapping>
> 
> </web-app>
> ```

**Comment by snicoll** [comment]
@kazuki43zoo sorry, I missed that context. This has been merged in `master` and `4.3.x`. Thanks!

**Pull request closed without merging**
