### PR TITLE
SPR-16957 - Shared ByteBufferPool for Undertow WebSocket sessions

### PR DESCRIPTION
**Pull request by schnapster**
Issues: SPR-16957

https://jira.spring.io/browse/SPR-16957

### CODE REVIEW

**Comment by napstr** [comment]
UndertowWebSocketClient#setPoolBufferSize becoming a (deprecated) noop might be problematic for existing code. Not sure how to solve that in the best backwards compatible manner, input or changes very much welcome.

**Comment by rstoyanchev** [comment]
In the 5.0.x branch those would be marked `@Deprecated`. You can remove them here in master, for 5.1.

**Comment by napstr** [comment]
Removed the getter and setter for byte buffer pool size.

**Comment by rstoyanchev** [comment]
Thanks, I've updated both branches.

**Pull request closed without merging**
