### PR TITLE
Polish: map entries should be iterated when both the key and value are needed

### PR DESCRIPTION
**Pull request by igor-suhorukov**
use java 8 language features to iterate on maps and transform data set by streams

### CODE REVIEW

**Comment by jhoeller** [comment]
Inspired by this PR, I've taken a broad sweep over existing `Map.Entry` iteration cases as well: https://jira.spring.io/browse/SPR-16646, rolling your changes into it in a slightly revised fashion.

Once again, thanks for your efforts there!

**Comment by igor-suhorukov** [comment]
@jhoeller thank you for your great work!
Could you please talk two words about Russian community contribution and my PRs on JPoint conference Moscow?

  Regards,
      Igor

**Comment by jhoeller** [comment]
Absolutely, my JPoint keynote is about Spring Framework 5 and our JDK 8/9 specific work, and many of your contributions were related to Java 8+ API usage... a fine example for how community contributions make our ongoing theme much more complete that we initially shipped it, and how those contributions provide direct triggers for follow-up work on our side. It'll be my pleasure to explicitly mention your PRs!

**Comment by sbrannen** [comment]
👏

**Comment by igor-suhorukov** [comment]
@jhoeller thanks a lot for your time because of sometimes my pull requests are too noisy)))
I am waiting for your keynote in Moscow!

**Comment by igor-suhorukov** [comment]
@sbrannen thanks) [to be continued...](https://github.com/spring-projects/spring-framework/pull/1755)

**Pull request closed without merging**
