### PR TITLE
Set thread interrupt flag on InterruptedException

### PR DESCRIPTION
**Pull request by igor-suhorukov**

### CODE REVIEW

**Comment by jhoeller** [comment]
Indeed, looks like we're missing a few `interrupt()` calls there which is also inconsistent with other places in the framework codebase. Could you please create a JIRA issue for this? I'll merge this into 5.0.4 and 4.3.15 then.

**Comment by igor-suhorukov** [comment]
@jhoeller thank you for assistance. I create ticket [SPR-16479](https://jira.spring.io/browse/SPR-16479) as you wish

**Comment by jhoeller** [comment]
@igor-suhorukov, could you please refer to SPR-16479 in your commit (we usually add a line "Issue: SPR-16479") at the end of the commit message) and switch to upper-case "Set..." at the beginning while you're at it? This would allow for a direct merge to master, making it easier to backport to the 4.3.x branch.

**Comment by igor-suhorukov** [comment]
@jhoeller sorry I deleted their fork from my repo

**Comment by jhoeller** [comment]
No worries, I've gone through those six places manually and also made the exception wrapping consistent. Thanks for the pull request, in any case! And of course, also for your others - all well spotted and very welcome. I'll selectively backport some of those refinements to 4.3.x as well but since they don't constitute a behavioral bug we don't really need a JIRA ticket for those others (just for this one here).

**Comment by igor-suhorukov** [comment]
Thank you @jhoeller

**Pull request closed without merging**
