### PR TITLE
PropertyResolver extension getProperty with default value

### PR DESCRIPTION
**Pull request by kkocel**
This convenient metod will return non null value with reified type

### CODE REVIEW

**Comment by kkocel** [comment]
@sdeleuze I've created a tiny PR with PropertyResolver extension - can you take a look?

**Comment by kkocel** [comment]
@snicoll Hey, I deduct that `PropertyResolverExtensions.kt` was (re)moved? Was it moved somewhere?

**Comment by snicoll** [comment]
@kkocel apologizes for this. We used GitHub's branch renaming feature and it wasn't supposed to close this PR. It would be nice to get a review from @sdeleuze before asking you to submit that code again.

**Comment by sdeleuze** [comment]
I intentionally did not provide the proposed extension because Kotlin provide an idiom for that use case : `propertyResolver.getProperty<String>("name") ?: "foo"`. So I don't think it is necessary to provide a new PR, and I will fix myself the documentation typo.

**Comment by sdeleuze** [comment]
See d7f67b3dc3bd989940ced850f3375474e57560f3 for the typo fix.

**Comment by kkocel** [comment]
@sdeleuze @snicoll  thanks! I'm glad that it got resolved

**Pull request closed without merging**
