### PR TITLE
Improve SpEL inline collection caching

### PR DESCRIPTION
**Pull request by SammyVimes**
This is a fix for https://github.com/spring-projects/spring-framework/issues/22146

### CODE REVIEW

**Comment by sbrannen** [comment]
For future reference, there was no need to close #25047.

If you need to make changes to a PR, you can push additional commits to the PR branch and rebase on the latest `master` if necessary.

**Comment by sbrannen** [comment]
@aclement, do you have time to review the proposal?

**Comment by aclement** [comment]
It looks reasonable to me @sbrannen . The only concern I'd have is that we do allowable SpEL compilation of inline lists (not inline maps yet):

In InlineList:
```
	public boolean isCompilable() {
		return isConstant();
	}
```

So maybe a few tests verifying compiled expressions using inline lists are still OK with the constant computation extended to include OpMinus nodes. I *think* it'll be ok from browsing the code, but worth testing.

**Comment by SammyVimes** [comment]
@aclement I added tests verifying compilation, looks like it's still OK

**Comment by SammyVimes** [comment]
Hello! I wonder if we can proceed with the review and merge this? :)

**Comment by sdeleuze** [comment]
Rebased and merged, thanks for your contribution and sorry for the delay.

**Comment by sbrannen** [comment]
Indeed, thanks for the PR, @SammyVimes! 👍 

I unfortunately forgot about this PR and so only got around to reviewing it after it had been merged.

You can see the result of my _belated review_ in e7cf54d4e236ac1e5e5dd59899aae268bcace21d.

**Pull request closed without merging**
