### PR TITLE
Separate java tokens by a single space

### PR DESCRIPTION
**Pull request by robertwhitebit**
Replacing multiple spaces and tabs, which separates java tokens, by a
single space.

I have signed and agree to the terms of the Spring Individual Contributor
License Agreement.

### CODE REVIEW

**Comment by sbrannen** [comment]
@robertwhitebit, out of curiosity, how did you achieve this?

Do you have a script that automates this? If so, we'd be interested in getting access to it.

**Comment by robertwhitebit** [comment]
Hi! :smile:

> how did you achieve this?

There is going to be a new check in the [sevntu.checkstyle](https://github.com/sevntu-checkstyle/sevntu.checkstyle) project (very soon!). This check...

> "Checks that if tokens are separated by whitespaces, it has to be a single space. Separating tokens by tabs or multiple spaces will be reported. Currently the check doesn't support [horizontal alignment](https://google.github.io/styleguide/javaguide.html#s4.6.3-horizontal-alignment)."

So, I just used the new [sevntu.checkstyle](https://github.com/sevntu-checkstyle/sevntu.checkstyle) check `SingleSpaceSeparator`, which reported all violations, and also a very simple/primitive python script which fixed them automatically. Here is the [checkstyle configuration](https://gist.github.com/robertwhitebit/692c954da71c8b76260c#file-checkstyle-xml) and the [python script](https://gist.github.com/robertwhitebit/692c954da71c8b76260c#file-p-py) (tested and used on Ubuntu only).

First, you have to run Checkstyle to generate the `checkstyle-result.xml` file and then you run the python script. Adapt the path to the `checkstyle-result.xml` file if necessary in the python script. You should definitively rerun Checkstyle to check if there are still violations.

I'll let you know when the new check has been merged into the sevntu.checkstyle project, so you can also use the new Checkstyle check.

**Comment by romani** [comment]
after some period of testing on real opensource and close projects , this Check will be merged to main project - [checkstyle](https://github.com/checkstyle/checkstyle).

**Comment by sbrannen** [comment]
@romani,

> after some period of testing on real opensource and close projects , this Check will be merged to main project - checkstyle.

Any idea when this will happen?

**Comment by romani** [comment]
I do not know :( , we need smb to move this Check to main project.
We are still in moratorium period, new check is allowed only if smb fix 5 functional bugs before introduction of new Check. Details - https://groups.google.com/d/msg/checkstyle-devel/JbhfiiSqKsQ/2vkapmxkDgAJ

What is a problem to use Check from sevntu-checkstyle project ?

**Comment by sbrannen** [comment]
> What is a problem to use Check from sevntu-checkstyle project?

Well, I was hoping to be able to use the `SingleSpaceSeparator` without having to add an additional dependency on the `sevntu-checkstyle` project.

**Comment by romani** [comment]
@rnveach ,  looks like you have a enough bug fixes for checkstyle. 
Can you move this Check to main project ?

**Comment by sbrannen** [comment]
@romani, looks like you commented on the wrong issue / in the wrong repository.

**Comment by rnveach** [comment]
@sbrannen Romani is pinging me for the CS project from here.
@romani I will start it.

**Comment by robertwhitebit** [comment]
@sbrannen, I guess this pull request can be closed now.
The SingleSpaceSeparator check has been included into Checkstyle a long time ago.

**Comment by pivotal-issuemaster** [comment]
@robertwhitebit Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=898)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=898) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Pull request closed without merging**
