### PR TITLE
SPR-15054: Add Kotlin extensions for function Web API

### PR DESCRIPTION
**Pull request by sdeleuze**
PR ready to be merged after @jhoeller approval.

### CODE REVIEW

**Comment by lqjack** [comment]
why introduce kotlin to the spring framework ? just for simpility?

**Comment by sdeleuze** [comment]
@lqjack Kotlin allows to write more efficient code, and is also relevant for both object-oriented and functional programming. Notice that Kotlin support is like any other technology supported in Spring Framework, it is available optionally if you are using it, but if you don't use Kotlin you won't notice any change.

**Comment by sdeleuze** [comment]
Merged

**Comment by geoand** [comment]
I love the way Kotlin is being introduced in a non-intrusive manner into Spring!
Two awesome technologies working together seamlessly just makes our lives simpler :)

**Pull request closed without merging**
