### PR TITLE
Update import-into-idea.md

### PR DESCRIPTION
**Pull request by neetkee**
Update tutorial for import and build project in IntelliJ IDEA 2016.2.2. Steps are outdated and existing issues is not applicable in new versions.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@neetkee Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1150)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1150) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@neetkee Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1150)!

**Comment by bclozel** [comment]
Merged with e7aecb44bb9c08f63b
Thanks!

**Comment by rstoyanchev** [comment]
@neetkee just wondering if these updates were based on specific issues that you know of that were addressed in IntelliJ or just based on trying the latest?

My experience is very different using both 2016.1.4 and 2016.2.2. It all started with running into this issue https://jira.spring.io/browse/SPR-14650 which @rwinch will commit a fix for shortly. Beyond that, on a fresh clone of the spring-framework and with no CLI activity, just a straight-up import into Idea, I get all of the issues that are now listed as "known issues" for 13.1. In other words I get compilation issues related to CGLIB repackaging, OXM generated test sources, and spring-aspects. Is it possible you didn't try with a completely new clone of the repository? I can't explain otherwise why the difference.

As far as I can tell based on my experience (and I think @rwinch had the same while testing) the instructions at present should be -- clone the repository, run the tests with Gradle from the command line once, then import, and during the import exclude spring-aspects. @rwinch is also planning to open a ticket with IntelliJ to allow running gradle tasks on import which would give us an opportunity to improve on this status quo but aside from that it'd be useful to know if you have references as to why these are issues in 13.1 but no any more.

Thanks for helping to clear this up.

**Comment by rwinch** [comment]
I typically don't actually run the tests before import as this takes more time. I just compile the tests which triggers all the repack tasks.

I created https://youtrack.jetbrains.com/issue/IDEA-160605 for making this easier.

**Comment by rstoyanchev** [comment]
> I typically don't actually run the tests before import as this takes more time

Indeed just spring-core and spring-oxm suffices. It's a little simpler in the instructions to just have `gradlew test` but we can qualify with a clarification saving a little time. Hopefully that step can go away eventually based on Idea ticket you created.

**Comment by rwinch** [comment]
@rstoyanchev Perhaps just use `./gradlew tCG` which should suffice (it triggers `testCompileGroovy`)?

**Comment by rwinch** [comment]
Hmmm...I thought that had worked, but apparently it doesn't since the root project doesn't have that task

**Comment by neetkee** [comment]
I checked it again, without workarounds. It's not working now, looks like at first time I invoked gradle build from IDEA's gradle window. So checked it **with**  workarounds and got this from Build -> Rebuild Project:
```
Error:(80, 51) java: cannot access io.netty.util.ReferenceCounted
  class file for io.netty.util.ReferenceCounted not found
Error:(84, 36) java: cannot access io.netty.util.ByteProcessor
  class file for io.netty.util.ByteProcessor not found
Error:(214, 36) java: cannot find symbol
  symbol:   method release()
  location: variable byteBuf of type io.netty.buffer.ByteBuf
/spring-framework/spring-core/src/main/java/org/springframework/core/io/buffer/NettyDataBuffer.java
```
Then I tried to build it from CLI and got another error:
```
 /spring-framework/spring-web/src/main/java/org/springframework/http/server/reactive/AbstractRequestBodyPublisher.java:109: error: cannot find symbol
                                Operators.getAndSub(this.demand, 1L);
                                         ^
```
It can't find this method in reactor, I guess.

Sorry in advance for this confusion.

**Comment by rstoyanchev** [comment]
No worries, good to know. I do see the issue with with the Netty ReferenceCount as well. That seems to be something new.. At any rate thanks for confirming. I guess we should at least update the instructions for now and take it from there.

**Comment by neetkee** [comment]
Turns out, that almost no changes needed in this instruction, at least until JetBrains resolve issues?

**Comment by rstoyanchev** [comment]
I've updated the instructions slighted and merged. On import you can pick the build.gradle file directly and that saves a couple of screens. Also during the import a prompt comes up where you can deselect spring-aspects already. Thanks for the updates.

**Pull request closed without merging**
