### PR TITLE
Add a way to set the timeout to reactive jdk client

### PR DESCRIPTION
**Pull request by m4tt30c91**
Add a setTimeout method to the http reactive jdk native connector

### CODE REVIEW

**Comment by jhoeller** [comment]
Thanks for the suggestion! We should name that method `setReadTimeout`, aligned with ´JdkClientHttpRequestFactory`, and possibly pass the `Duration` straight into an extended `JdkClientHttpRequest` constructor (since the request class is not public anyway, we can flexibly change the constructor signature to accept a `Duration` parameter that we can directly apply there).

Feel free to revise the PR accordingly, otherwise we can also implement it directly.

**Comment by matteocristoforo-fabrick** [comment]
Sure, gonna review the pull request accordingly; is it ok if I add a commit on top, or would you prefer a single one to keep it cleaner?

**Comment by m4tt30c91** [comment]
Sure, gonna review the pull request accordingly; is it ok if I add a commit on top, or would you prefer a single one to keep it cleaner?

**Comment by snicoll** [comment]
Both are fine but if you can squash that’s better.

**Comment by m4tt30c91** [comment]
I did review the pull request, let me know if that is ok.

**Comment by snicoll** [comment]
Thanks for making your first contribution to Spring Framework, @m4tt30c91.

**Pull request closed without merging**
