### PR TITLE
SPR-16340 - Added a new param separator for NamedParameterUtils

### PR DESCRIPTION
**Pull request by KitHat**
Added '[' and ']' as param separator and test for this case

Closes SPR-16340

### CODE REVIEW

**Comment by snicoll** [comment]
@KitHat we need a Jira issue in the framework issue tracker to discuss this change. Can you please [create  one](https://jira.spring.io/browse/SPR)?

**Comment by KitHat** [comment]
@snicoll there is one already https://jira.spring.io/browse/SPR-16340

**Comment by snicoll** [comment]
You referenced DATAJDBC which is not the spring framework's isssue tracker key. I can see now that the issue has been moved.

**Comment by jhoeller** [comment]
Closed in favor of a slightly different implementation (see SPR-16340). Thanks for the pull request!

**Pull request closed without merging**
