### PR TITLE
Enhanced MockRestResponseCreators by a withStatus with body and media type

### PR DESCRIPTION
**Pull request by hadjiski**
Otherwise one have to do something like this:
```
    private static class SomeResponseCreator extends DefaultResponseCreator {

        SomeResponseCreator(HttpStatus statusCode) {
            super(statusCode);
        }
    }
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hadjiski Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1608)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1608) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hadjiski Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1608)!

**Comment by hadjiski** [comment]
What is the process now, just waiting or am I missing something?

**Comment by snicoll** [comment]
@hadjiski sorry, this one got overlooked. We need a Jira issue for this change, can you please [create one](https://jira.spring.io/browse/SPR)?

**Comment by hadjiski** [comment]
Hey, can you please create the jira ticket for me and link it to the PR, I don't have the time right now to create a jira account to the spring project. Thanks

 

 

Gesendet: Freitag, 15. Dezember 2017 um 18:38 Uhr
Von: "Stéphane Nicoll" <notifications@github.com>
An: spring-projects/spring-framework <spring-framework@noreply.github.com>
Cc: hadjiski <radi_freiburg@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [spring-projects/spring-framework] Enhanced MockRestResponseCreators by a withStatus with body and media type (#1608)


@hadjiski sorry, this one got overlooked. We need a Jira issue for this change, can you please create one?

**Comment by rstoyanchev** [comment]
The description "Otherwise I have to..." does not match the actual change. 

As far as I can see the actual change creates an overloaded `withStatus` method that also takes body and contentType. However the expected syntax for that is `withStatus(...).body(..).conentType(..)`. If you really want such a shortcut simply create your own static method and use it.

**Comment by hadjiski** [comment]
What's the point of having other withStatus methods, but not this generic one, never mind, as u like.

Gesendet von meinem Windows 10 Phone

Von: Rossen Stoyanchev
Gesendet: Montag, 18. Dezember 2017 15:55
An: spring-projects/spring-framework
Cc: hadjiski; Mention
Betreff: Re: [spring-projects/spring-framework] Enhanced MockRestResponseCreators by a withStatus with body and media type (#1608)

The description "Otherwise I have to..." does not match the actual change.
As far as I can see the actual change creates an overloaded withStatus method that also takes body and contentType. However the expected syntax for that is withStatus(...).body(..).conentType(..). If you really want such a shortcut simply create your own static method and use it.

**Comment by rstoyanchev** [comment]
The methods provided in `MockRestResponseCreators` cover the most common scenarios. For anything else you still have a way, just no shortcut. Like I said it's trivial to create your own shortcut.

**Pull request closed without merging**
