### PR TITLE
SPR-17540 JavaMailSenderImpl does not show proper message when recipient list is empty

### PR DESCRIPTION
**Pull request by Jebil**
https://jira.spring.io/browse/SPR-17540

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Jebil Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2029)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2029) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Jebil Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2029)!

**Review by vrnsky — CHANGES_REQUESTED** [review]

**Review by vrnsky — APPROVED** [review]

**Comment by Jebil** [comment]
Ok @jhoeller , would  you be kind enough to let me know, what I could have done better ?

**Comment by snicoll** [comment]
@Jebil there is a [comment in the issue](https://jira.spring.io/browse/SPR-17540?focusedCommentId=163859&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-163859) and the [commit shows concretely](https://github.com/spring-projects/spring-framework/commit/191a2d3f2555c58a82bbe14ea7d1ec627a7a3e38) the strategy that we preferred.

Thank you very much for your contribution in any case!

**Pull request closed without merging**
