### PR TITLE
Use System.currentTimeMillis() in AbstractSockJsService

### PR DESCRIPTION
**Pull request by XenoAmess**
as title

### CODE REVIEW

**Comment by sbrannen** [comment]
Can you please briefly explain the rationale for the proposed change?

**Comment by XenoAmess** [comment]
> Can you please briefly explain the rationale for the proposed change?

@sbrannen https://stackoverflow.com/questions/368094/system-currenttimemillis-vs-new-date-vs-calendar-getinstance-gettime

**Comment by XenoAmess** [comment]
image

**Comment by sbrannen** [comment]
This has been merged into `master`.

Thanks for the PR and for providing the rationale.

**Comment by sbrannen** [comment]
In future PRs, please make sure to delete unused imports (see 24f9b1d966c9eb0af683ef8382c0ff8a23d526bd) and run `./gradlew check` before submitting the PR.

**Pull request merged**
