### PR TITLE
Minor grammatical changes

### PR DESCRIPTION
**Pull request by logicg8**
Removed article and capitalized class name

### CODE REVIEW

**Comment by snicoll** [comment]
Your other commit got merged so could you please rework your PR to only include the new changes? I can see that you are pushing from master: usually a PR should be made against a branch.

Minor grammatical changes do not need paperwork but to be on the safe side, please confirm that you've signe the CLA. Thanks!

**Comment by snicoll** [comment]
Ping?

**Comment by logicg8** [comment]
I apologize for the delay. I have not signed the CLA. I read the CONTRIBUTING-DOCUMENTATION.adoc but did not see reference to signing the CLA for documentation contribution. Based on your comment, I was going to sign the CLA, but the form advises to get authorization from my employer. I can check into that. In the interim, should I rework my PR to only include the new changes? Or can this PR even be accepted without a CLA?

**Comment by snicoll** [comment]
Such small typo change is fine but please do sign the CLA first.

**Comment by snicoll** [comment]
ping?

**Comment by snicoll** [comment]
I went ahead and added those changes myself. Thanks for the PR

**Pull request closed without merging**
