### PR TITLE
add some utility methods for StringUtils

### PR DESCRIPTION
**Pull request by SympathyForTheDev**
this PR add some useful method in StringUtils like "isNotEmpty", 
this kind of method is more readable and avoid thing like this 

> import static org.springframework.util.StringUtils.isEmpty;
> (...)
> if (!isEmpty(someString)) {
> // some code with this string
> }

OR 

> import static org.springframework.util.StringUtils.isEmpty;
> import static org.springframework.util.StringUtils.trimWhiteSpace;
> (...)
> if (!isEmpty(trimWhiteSpace(someString))) {
> // some code with this string
> }

Also I have update the StringUtils unit test

### CODE REVIEW

**Comment by DevWantJustHaveFun** [comment]
@snicoll  it's necessary to create a jira ticket for this PR ?

**Comment by snicoll** [comment]
We prefer to have things to other way around: discussion for non trivial changes in Jira and then a PR. This avoid you spending time on something we wouldn't ultimately include. 

Can you please create a Jira issue?

**Comment by snicoll** [comment]
On a second look on the framework and having double check with @jhoeller we won't accept that change unfortunately. We have several shorter options for those and we don't think it's worth adding them in the core framework. Thanks for the PR though!

**Comment by DevWantJustHaveFun** [comment]
@snicoll  thanks for your response, just out of curiosity what is the shorter options ?

**Comment by snicoll** [comment]
`isNotEmpty is longer than `!isEmpty`. As for ` isBlank`, we got `hasText` vs `!hasText` already.

**Pull request closed without merging**
