### PR TITLE
Fix findAnnotationOnBean Kotlin extension return type

### PR DESCRIPTION
**Pull request by danthonywalker**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@danthonywalker Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26908)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26908) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by danthonywalker** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@danthonywalker This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Review by sdeleuze — CHANGES_REQUESTED** [review]
Hi thanks for this PR and sorry for the delay, could you please add related tests in `ListableBeanFactoryExtensionsTests` to exercise the use case that was not covered previously?

**Pull request closed without merging**
