### PR TITLE
Remove unnecessary semicolon

### PR DESCRIPTION
**Pull request by andrey4623**
Remove unnecessary semicolon after the nested class.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@andrey4623 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23477)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23477) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by sbrannen** [comment]
@pivotal-issuemaster this is an obvious fix.

**Comment by pivotal-issuemaster** [comment]
@andrey4623 This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by sbrannen** [comment]
This has been merged into `master`.

Thanks

**Comment by pivotal-issuemaster** [comment]
@andrey4623 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23477)!

**Pull request merged**
