### PR TITLE
Ensure that the ExposeInvocationInterceptor is first in the interceptor chain

### PR DESCRIPTION
**Pull request by wisty**
check the ExposeInvocationInterceptor is front in the interceptor chain
issue #26743

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wisty Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26752)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26752) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wisty Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26752)!

**Comment by wisty** [comment]
what happening lead to this pr in:core state

**Comment by sbrannen** [comment]
According to the Javadoc for `ExposeInvocationInterceptor`:

> If used, this interceptor will normally be the first in the interceptor chain.

Thus, I don't think there is any guarantee that the `ExposeInvocationInterceptor` is first in the interceptor chain, which your proposed change checks for.

If you feel that you have encountered a bug, please introduce a test that fails before the fix and passes after the fix.

**Comment by snicoll** [comment]
closing due to lack of feedback.

**Pull request closed without merging**
