### PR TITLE
Support "*" catch-all mappings for MockMvc Filter registrations

### LINKED ISSUE #28017: `PatternMappingFilterProxy#addUrlPattern` not support `*` url pattern
**Affects:** 5.4.15

---
Does not work in MockMvc when `FilterRegistrationBean` url pattern is `*`.

See [demo](https://github.com/Deycoesr/SPR28017)

### PR DESCRIPTION
**Pull request by funky-eyes**
I believe most business developers think * is equivalent to /*

fixes #28017

### CODE REVIEW

**Comment by bclozel** [comment]
The intent behind #28017 so far is documentation only. This PR changes the behavior and we didn't come to that conclusion yet. Would you like to amend this PR address the original issue?

**Comment by a364176773** [comment]
> 

Could you please tell me exactly how to do that?

**Comment by a364176773** [comment]
> The intent behind #28017 so far is documentation only. This PR changes the behavior and we didn't come to that conclusion yet. Would you like to amend this PR address the original issue?

I think the #28017 solution is more than just documentation, it should be supported at the code level

**Comment by a364176773** [comment]
@bclozel When can you review the PR, please?

**Comment by bclozel** [comment]
Thanks @funky-eyes for your contribution, this is now merged.

**Pull request closed without merging**
