### PR TITLE
(refactoring) Use of lambda expressions instead of foreach (exist pattern)

### PR DESCRIPTION
**Pull request by rbonifacio**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rbonifacio Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1460)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1460) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by rbonifacio** [comment]
@pivotal-issuemaster thanks for message. I've just signed the Contributor License Agreement.

**Comment by pivotal-issuemaster** [comment]
@rbonifacio Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1460)!

**Comment by snicoll** [comment]
@rbonifacio thanks for submitting your first pull request! Unfortunately, please note that we're not usually doing such code style refinements via pull requests. If you'd like to provide further pull requests, please focus on feature tickets. For code style issues, you might simply create a JIRA task pointing out the refinement (or a whole range of refinements), with us sorting it out on our end and no pull request needed.

**Pull request closed without merging**
