### PR TITLE
Sorry,my mistake

### PR DESCRIPTION
**Pull request by itcrazy0717**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@morewindows0 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1852)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1852) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by quaff** [comment]
你在瞎搞

**Comment by snicoll** [comment]
Looks like it has been opened by mistake.

**Comment by morewindows0** [comment]
@snicoll i'm so sorry,it's my mistake,and the next time,i'll pay attention to it.i'm so sorry again.

**Comment by morewindows0** [comment]
@quaff 一不小心看错分支了，有点尴尬

**Pull request closed without merging**
