### PR TITLE
Fix typo in package-info.java

### PR DESCRIPTION
**Pull request by chenqimiao**
fix SImple -> Simple

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@chenqimiao Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22941)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22941) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
@spring-buildmaster this is an obvious fix

**Comment by pivotal-issuemaster** [comment]
@chenqimiao This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by snicoll** [comment]
@chenqimiao thank you for making your first contribution to Spring Framework. This is now merged in `5.1.x` and `master`.

**Pull request closed without merging**
