### PR TITLE
SPR-17364 - Give timeout result supplier in DeferredResult

### PR DESCRIPTION
**Pull request by chenlingmin**
[SPR-17364](https://jira.spring.io/browse/SPR-17364)

```
value:          A           | B
                            |
Time line: -----+-----------+------------------------>
                t1          t2
```

The value at t1 time is A, and t2 time is B.
If t2 time is timeout time, I want return value of t2.
like this

```
new DeferredResult(2000, () -> valueService.get(now));
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@chenlingmin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1988)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1988) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@chenlingmin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1988)!

**Comment by bclozel** [comment]
@chenlingmin Thanks for this contribution!
Could you create an issue on jira.spring.io on the Spring Framework project so that we can discuss this contribution and maybe schedule it for a release?

Thanks!

**Comment by chenlingmin** [comment]
@bclozel   Ok?

**Comment by rstoyanchev** [comment]
This is now merged.

**Pull request closed without merging**
