### PR TITLE
Improve so that KotlinSerialization can be applied before Jackson2

### PR DESCRIPTION
**Pull request by meloning**
Reference Issue: [Issue-29008](https://github.com/spring-projects/spring-framework/issues/29008)

I expect to need test code, but I can't find the previously written test code. Can you give me a guide on writing test code?

### CODE REVIEW

**Comment by sdeleuze** [comment]
That would be consistent with what we do in `WebMvcConfigurationSupport` [here](https://github.com/spring-projects/spring-framework/blob/d16fa82888681e5de1753387a1b499dbe35a9cfe/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.java#L916-L918) which does that because Kotlin serialization require an explicit signal (the class should be annotated with `@Serializable`) otherwise serialization is delegated to Jackson.

@rstoyanchev Are you ok with doing that on `5.3.x` even if we are late in the patch release cycle? It will be a slight change of behavior but should impact very few people and I think it could be considered as a bug and a lack of consistency.

**Comment by meloning** [comment]
Also, parts [AbstractMessageBrokerConfiguration](https://github.com/spring-projects/spring-framework/blob/d16fa82888681e5de1753387a1b499dbe35a9cfe/spring-messaging/src/main/java/org/springframework/messaging/simp/config/AbstractMessageBrokerConfiguration.java#L477) and [AllEncompassingFormHttpMessageConverter](https://github.com/spring-projects/spring-framework/blob/d16fa82888681e5de1753387a1b499dbe35a9cfe/spring-web/src/main/java/org/springframework/http/converter/support/AllEncompassingFormHttpMessageConverter.java#L99) are in the same situation, can I fix it in the PR and upload it?

**Comment by meloning** [comment]
Hello @sdeleuze @rstoyanchev 
I added kotlinSerialization test case in RestTemplateTests and fixed the case where MessageBrokerConfigurationTests that test AbstractMessageBrokerConfiguration fails.

Please check and review.

**Comment by meloning** [comment]
Hi @rstoyanchev @sdeleuze 
There is no answer yet, so I'm leaving a comment again.
Please let me know if there are any errors or if there are any additional considerations.

Please check.
Thank you

**Comment by sdeleuze** [comment]
Merged a refined version via bb3ada4a673c689b9d5c854ec021b8e96e32c447, thanks!

**Pull request closed without merging**
