### PR TITLE
Reactor netty 0.6

### PR DESCRIPTION
**Pull request by smaldini**
Prepare for reactor-netty 0.6 updates

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@smaldini Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1239)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1239) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@smaldini Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1239)!

**Comment by smaldini** [comment]
Clean runs from integration testing point of view from spring-web-reactive, CF and reactor-netty

**Comment by rstoyanchev** [comment]
This is now merged. Thanks!

**Pull request closed without merging**
