### PR TITLE
SPR-14670 - Deprecating NativeJdbcExtractor in favor of java.sql.Connection.unwrap()

### PR DESCRIPTION
**Pull request by jmithmstr**

### CODE REVIEW

**Comment by jmithmstr** [comment]
Is this pull request blocked because I need to create a jira issue or because you need to create a jira issue? Or it is not blocked at all and you need to decide what to do?

**Comment by snicoll** [comment]
@jmithmstr it is not blocked, it is waiting for triage. Someone needs to have a deeper look to it. If you create an issue that would probably speed this up. Thanks.

**Comment by pivotal-issuemaster** [comment]
@jmithmstr Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1090)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1090) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by jhoeller** [comment]
See the JIRA issue: We're dropping the mechanism completely as of 5.0, without an intermediate deprecation step. Thanks for raising this!

**Pull request closed without merging**
