### PR TITLE
Use Collections.addAll() where feasible

### PR DESCRIPTION
**Pull request by ysc972**
I found that some code can be replaced with a lambda expression when using IDEA for inspect the code.so submit a PR here.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ysc972 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23481)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23481) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ysc972 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23481)!

**Review by mentallurg — CHANGES_REQUESTED** [review]
"update some thing" is not an acceptable commit message.
Change you commit messages and describe what you have changed.

**Review by sbrannen — CHANGES_REQUESTED** [review]
We do not make changes to the repackaged CBLIB classes in `spring-core`. So please revert all changes to classes in `org.springframework.cglib` and any of its subpackages.

For the remaining changes, please _amend_ your commit and supply an appropriate commit message.

**Comment by sbrannen** [comment]
@ysc972, are you planning on making the requested changes?

If not, please let us know anyway so that we can close this PR.

Thanks,

Sam

**Comment by sbrannen** [comment]
Closing due to lack of feedback

**Pull request closed without merging**
