### PR TITLE
Avoid getting objects that have not completed initialization

### PR DESCRIPTION
**Pull request by lijinxiong**
in org.springframework.beans.factory.support.DefaultSingletonBeanRegistry

```java
@Nullable
protected Object getSingleton(String beanName, boolean allowEarlyReference) {
// Quick check for existing instance without full singleton lock
Object singletonObject = this.singletonObjects.get(beanName);
if (singletonObject == null && isSingletonCurrentlyInCreation(beanName)) {
	singletonObject = this.earlySingletonObjects.get(beanName);
	if (singletonObject == null && allowEarlyReference) {
		synchronized (this.singletonObjects) {
			// Consistent creation of early reference within full singleton lock
			singletonObject = this.singletonObjects.get(beanName);
			if (singletonObject == null) {
				singletonObject = this.earlySingletonObjects.get(beanName);
				if (singletonObject == null) {
					ObjectFactory<?> singletonFactory = this.singletonFactories.get(beanName);
					if (singletonFactory != null) {
						singletonObject = singletonFactory.getObject();
						this.earlySingletonObjects.put(beanName, singletonObject);
						this.singletonFactories.remove(beanName);
					}
				}
			}
		}
	}
}
return singletonObject;
}
```

Unit test

```java
public class Father {

	private Son son;

	public Son getSon() {
		return son;
	}

	public void setSon(Son son) {
		this.son = son;
	}
}
```

```java
public class Son {

	private Father father;

	private Mother mother;

	public Father getFather() {
		return father;
	}

	public void setFather(Father father) {
		this.father = father;
	}

	public Mother getMother() {
		return mother;
	}

	public void setMother(Mother mother) {
		this.mother = mother;
	}
}
```

```java
public class Mother {

	public Mother() {

		// Simulation takes a long time、just for testing
		try {
			Thread.sleep(4 * 1000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

	}
}

```

```java
	@Test
	public void testGetLazySingleton() throws InterruptedException {
		testGetSingleton("father");
	}

	@Test
	public void testGetNonLazySingleton() throws InterruptedException {
		testGetSingleton("father-non-lazy");
	}

	private void testGetSingleton(String fatherBeanName) throws InterruptedException {

		CountDownLatch countDownLatch = new CountDownLatch(2);
		AtomicInteger occurExceptionCount = new AtomicInteger(0);
		DefaultListableBeanFactory beanFactory = new DefaultListableBeanFactory();
		XmlBeanDefinitionReader reader = new XmlBeanDefinitionReader(beanFactory);
		reader.loadBeanDefinitions(new ClassPathResource("DefaultSingletonBeanRegistryTests.xml", getClass()));

		// Just for testing, you should use a thread pool
		new Thread(() -> {
			Father father = beanFactory.getBean(fatherBeanName, Father.class);
			try {
				Assert.notNull(father, "father Shouldn't be null");
				Assert.notNull(father.getSon(), "son Shouldn't be null");
			} catch (Exception e) {
				occurExceptionCount.incrementAndGet();
				System.out.println(Thread.currentThread().getName());
				e.printStackTrace();
			}
			countDownLatch.countDown();
		}, "first-thread").start();

		Thread.sleep(1000);

		// Just for testing, you should use a thread pool
		new Thread(() -> {
			Father father = beanFactory.getBean(fatherBeanName, Father.class);
			try {
				Assert.notNull(father, "father Shouldn't be null");
				Assert.notNull(father.getSon(), "son Shouldn't be null");
			} catch (Exception e) {
				occurExceptionCount.incrementAndGet();
				System.out.println(Thread.currentThread().getName());
				e.printStackTrace();
			}
			countDownLatch.countDown();
		}, "second-thread").start();

		while (countDownLatch.getCount() != 0) {

		}
		Assert.isTrue(occurExceptionCount.get() == 0, "Throwing an exception in the sub-thread that gets the bean");
	}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xmlns="http://www.springframework.org/schema/beans"
	   xsi:schemaLocation="http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans-4.1.xsd">
	<bean id="mother" class="org.springframework.beans.testfixture.beans.Mother" lazy-init="true">
	</bean>
	<bean id="father" class="org.springframework.beans.testfixture.beans.Father" lazy-init="true">
		<property name="son" ref="son"/>
	</bean>
	<bean id="son" class="org.springframework.beans.testfixture.beans.Son" lazy-init="true">
		<property name="father" ref="father"/>
		<property name="mother" ref="mother"/>
	</bean>
  
	<bean id="mother-non-lazy" class="org.springframework.beans.testfixture.beans.Mother" lazy-init="false">
	</bean>
	<bean id="father-non-lazy" class="org.springframework.beans.testfixture.beans.Father" lazy-init="false">
		<property name="son" ref="son-non-lazy"/>
	</bean>
	<bean id="son-non-lazy" class="org.springframework.beans.testfixture.beans.Son" lazy-init="false">
		<property name="father" ref="father-non-lazy"/>
		<property name="mother" ref="mother-non-lazy"/>
	</bean>
</beans>
```

console log

```log
second-thread
java.lang.IllegalArgumentException: son Shouldn't be null
...........
...........
```

The code after my changes

```java
@Nullable
protected Object getSingleton(String beanName, boolean allowEarlyReference) {
  // Quick check for existing instance without full singleton lock
  Object singletonObject = this.singletonObjects.get(beanName);
  if (singletonObject == null && isSingletonCurrentlyInCreation(beanName)) {
	  synchronized (this.singletonObjects) {
		  singletonObject = this.singletonObjects.get(beanName);
		  if (singletonObject != null || !isSingletonCurrentlyInCreation(beanName)) {
			  return singletonObject;
		  }
		  singletonObject = this.earlySingletonObjects.get(beanName);
		  if (singletonObject == null && allowEarlyReference) {
			  ObjectFactory<?> singletonFactory = this.singletonFactories.get(beanName);
			  if (singletonFactory != null) {
				  singletonObject = singletonFactory.getObject();
				  this.earlySingletonObjects.put(beanName, singletonObject);
				  this.singletonFactories.remove(beanName);
			  }
		  }
	  }
  }
  return singletonObject;
}
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@lijinxiong Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26376)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26376) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by quaff** [comment]
Unit test is required.

**Comment by lijinxiong** [comment]
> Unit test is required.

after change？

**Comment by lijinxiong** [comment]
> Unit test is required.

**Comment by lijinxiong** [comment]
> Unit test is required.

The code is in the comments above

**Comment by sbrannen** [comment]
> > Unit test is required.
> 
> The code is in the comments above

@quaff is correct: when providing a PR to address an issue, you need to introduce a JUnit Jupiter based unit test that fails before the fix and passes after the fix.

**Comment by lijinxiong** [comment]
> > > Unit test is required.
> > 
> > 
> > The code is in the comments above
> 
> @quaff is correct: when providing a PR to address an issue, you need to introduce a JUnit Jupiter based unit test that fails before the fix and passes after the fix.
> 
> A Java class with a `main()` method that demonstrates the issue does not count as a test since a class with a `main()` method cannot be included in the Spring Framework test suite.

@sbrannen Do I need to submit code for unit tests?
Or just give it in the comments
Thanks！

**Comment by sbrannen** [comment]
> @sbrannen Do I need to submit code for unit tests?

Tests need to be submitted as part of the PR.

You will find existing tests under `src/test/java` in each module.

For example, for the class you have modified, you will find `org.springframework.beans.factory.support.DefaultSingletonBeanRegistryTests` in `spring-beans` module.

Note, however, that a pure unit test does not always suffice. In other words, you may need to create a dedicated integration test. For examples, feel free to browse the existing test suite. It often helps to search in the same package for related test classes.

**Comment by lijinxiong** [comment]
> > @sbrannen Do I need to submit code for unit tests?
> 
> Tests need to be submitted as part of the PR.
> 
> You will find existing tests under `src/test/java` in each module.
> 
> For example, for the class you have modified, you will find `org.springframework.beans.factory.support.DefaultSingletonBeanRegistryTests` in the `spring-beans` module.
> 
> Note, however, that a pure unit test does not always suffice. In other words, you may need to create a dedicated integration test. For examples, feel free to browse the existing test suite. It often helps to search in the same package for related test classes.

Thank you very much

**Comment by lijinxiong** [comment]
in org.springframework.beans.factory.support.DefaultSingletonBeanRegistry

```java
@Nullable
protected Object getSingleton(String beanName, boolean allowEarlyReference) {
// Quick check for existing instance without full singleton lock
Object singletonObject = this.singletonObjects.get(beanName);
if (singletonObject == null && isSingletonCurrentlyInCreation(beanName)) {
	singletonObject = this.earlySingletonObjects.get(beanName);
	if (singletonObject == null && allowEarlyReference) {
		synchronized (this.singletonObjects) {
			// Consistent creation of early reference within full singleton lock
			singletonObject = this.singletonObjects.get(beanName);
			if (singletonObject == null) {
				singletonObject = this.earlySingletonObjects.get(beanName);
				if (singletonObject == null) {
					ObjectFactory<?> singletonFactory = this.singletonFactories.get(beanName);
					if (singletonFactory != null) {
						singletonObject = singletonFactory.getObject();
						this.earlySingletonObjects.put(beanName, singletonObject);
						this.singletonFactories.remove(beanName);
					}
				}
			}
		}
	}
}
return singletonObject;
}
```

Unit test


```java
public class Father {

	private Son son;

	public Son getSon() {
		return son;
	}

	public void setSon(Son son) {
		this.son = son;
	}
}
```

```java
public class Son {

	private Father father;

	private Mother mother;

	public Father getFather() {
		return father;
	}

	public void setFather(Father father) {
		this.father = father;
	}

	public Mother getMother() {
		return mother;
	}

	public void setMother(Mother mother) {
		this.mother = mother;
	}
}
```

```java
public class Mother {

	public Mother() {

		// Simulation takes a long time、just for testing
		try {
			Thread.sleep(4 * 1000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

	}
}

```



```java
	@Test
	public void testGetLazySingleton() throws InterruptedException {
		testGetSingleton("father");
	}

	@Test
	public void testGetNonLazySingleton() throws InterruptedException {
		testGetSingleton("father-non-lazy");
	}

	private void testGetSingleton(String fatherBeanName) throws InterruptedException {

		CountDownLatch countDownLatch = new CountDownLatch(2);
		AtomicInteger occurExceptionCount = new AtomicInteger(0);
		DefaultListableBeanFactory beanFactory = new DefaultListableBeanFactory();
		XmlBeanDefinitionReader reader = new XmlBeanDefinitionReader(beanFactory);
		reader.loadBeanDefinitions(new ClassPathResource("DefaultSingletonBeanRegistryTests.xml", getClass()));

		// Just for testing, you should use a thread pool
		new Thread(() -> {
			Father father = beanFactory.getBean(fatherBeanName, Father.class);
			try {
				Assert.notNull(father, "father Shouldn't be null");
				Assert.notNull(father.getSon(), "son Shouldn't be null");
			} catch (Exception e) {
				occurExceptionCount.incrementAndGet();
				System.out.println(Thread.currentThread().getName());
				e.printStackTrace();
			}
			countDownLatch.countDown();
		}, "first-thread").start();

		Thread.sleep(1000);

		// Just for testing, you should use a thread pool
		new Thread(() -> {
			Father father = beanFactory.getBean(fatherBeanName, Father.class);
			try {
				Assert.notNull(father, "father Shouldn't be null");
				Assert.notNull(father.getSon(), "son Shouldn't be null");
			} catch (Exception e) {
				occurExceptionCount.incrementAndGet();
				System.out.println(Thread.currentThread().getName());
				e.printStackTrace();
			}
			countDownLatch.countDown();
		}, "second-thread").start();

		while (countDownLatch.getCount() != 0) {

		}
		Assert.isTrue(occurExceptionCount.get() == 0, "Throwing an exception in the sub-thread that gets the bean");
	}
```



```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xmlns="http://www.springframework.org/schema/beans"
	   xsi:schemaLocation="http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans-4.1.xsd">
	<bean id="mother" class="org.springframework.beans.testfixture.beans.Mother" lazy-init="true">
	</bean>
	<bean id="father" class="org.springframework.beans.testfixture.beans.Father" lazy-init="true">
		<property name="son" ref="son"/>
	</bean>
	<bean id="son" class="org.springframework.beans.testfixture.beans.Son" lazy-init="true">
		<property name="father" ref="father"/>
		<property name="mother" ref="mother"/>
	</bean>
  
	<bean id="mother-non-lazy" class="org.springframework.beans.testfixture.beans.Mother" lazy-init="false">
	</bean>
	<bean id="father-non-lazy" class="org.springframework.beans.testfixture.beans.Father" lazy-init="false">
		<property name="son" ref="son-non-lazy"/>
	</bean>
	<bean id="son-non-lazy" class="org.springframework.beans.testfixture.beans.Son" lazy-init="false">
		<property name="father" ref="father-non-lazy"/>
		<property name="mother" ref="mother-non-lazy"/>
	</bean>
</beans>
```



console log

```log
second-thread
java.lang.IllegalArgumentException: son Shouldn't be null
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistryTests.lambda$testGetSingleton$1(DefaultSingletonBeanRegistryTests.java:149)
	at java.lang.Thread.run(Thread.java:748)

Throwing an exception in the sub-thread that gets the bean
java.lang.IllegalArgumentException: Throwing an exception in the sub-thread that gets the bean
	at org.springframework.util.Assert.isTrue(Assert.java:121)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistryTests.testGetSingleton(DefaultSingletonBeanRegistryTests.java:161)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistryTests.testGetNonLazySingleton(DefaultSingletonBeanRegistryTests.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)

```



Use my modified code、Unit tests pass

**Comment by lijinxiong** [comment]
> > @sbrannen Do I need to submit code for unit tests?
> 
> Tests need to be submitted as part of the PR.
> 
> You will find existing tests under `src/test/java` in each module.
> 
> For example, for the class you have modified, you will find `org.springframework.beans.factory.support.DefaultSingletonBeanRegistryTests` in the `spring-beans` module.
> 
> Note, however, that a pure unit test does not always suffice. In other words, you may need to create a dedicated integration test. For examples, feel free to browse the existing test suite. It often helps to search in the same package for related test classes.

Unit tests already in pr
Thanks

**Comment by JackieGGu** [comment]
@lijinxiong I also found this problem recently, but from the previous issues [25667](https://github.com/spring-projects/spring-framework/issues/25667), It can be seen that Jhoeller is trying to solve 25667 thread deadlock, but the code in your PR will make Spring return to the thread deadlock problem again, Can you offer a better way to solve this problem?

**Comment by zhangdefu159** [comment]
if (singletonObject == null && allowEarlyReference)
-->
if ((singletonObject == null && allowEarlyReference) || this.singletonFactories.get(beanName) != null)

You can try changing the top line of code to the third line of code. Will this problem still occur

**Comment by zhangdefu159** [comment]
if (singletonObject == null && allowEarlyReference) 
-->
if(!((singletonObject != null && this.singletonFactories.get(beanName) == null) && (singletonObject == null && this.singletonFactories.get(beanName) != null)) && allowEarlyReference)


You can try changing the top line of code to the third line of code. Will this problem still occur

**Comment by zhangdefu159** [comment]
@lijinxiong 
if (singletonObject == null && allowEarlyReference)
-->
if(!((singletonObject != null && this.singletonFactories.get(beanName) == null) && (singletonObject == null && this.singletonFactories.get(beanName) != null)) && allowEarlyReference)

You can try changing the top line of code to the third line of code. Will this problem still occur

**Comment by jhoeller** [comment]
Completely removing the early singleton check like in this PR is not really a proper way out. If you'd like to avoid the circular reference problem completely, set your factory to `setAllowCircularReferences(false)` which will avoid any exposure to `earlySingletonObjects` to begin with, therefore reaching the same effect as dropping the early singleton check in the PR.

Note that we are considering to disallow circular references by default in a future Spring Framework generation. However, as long as we need to be able to resolve circular references, the current code still seems to be the best we can do there.

Also, please note that we generally recommend against concurrent bean initialization scenarios. In particular with respect to circular reference resolution, a single-threaded preInstantiateSingletons phase is the most reliable arrangement. If you need to initialize with multiple threads, at least apply `setAllowCircularReferences(false)` so that it becomes as reliable as possible.

**Pull request closed without merging**
