### PR TITLE
Protect getters consistently in AbstractRequestLoggingFilter

### PR DESCRIPTION
**Pull request by lwis**
Picked it up when writing some code in a Kotlin app.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@lwis Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1838)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1838) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@lwis Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1838)!

**Comment by jhoeller** [comment]
Good catch! Resolved through a slightly wider revision on master now, as noted on https://jira.spring.io/browse/SPR-16881. Thanks for the pull request, in any case...

**Comment by lwis** [comment]
@jhoeller np, thanks for fixing. 

Was great seeing you at Devoxx!

**Pull request closed without merging**
