### PR TITLE
Add missing unit tests for `SimpleAliasRegistry`

### PR DESCRIPTION
**Pull request by e-freni**
I've understood the purpose of that inversion (it took me a little while, to be honest :) ), so I've created a new pull request just for the code coverage. I hope everything is okay this time.

### CODE REVIEW

**Comment by fanta4715** [comment]
e

**Comment by sbrannen** [comment]
This has been merged into `main` in d507590abfbd1a42b750e70892c235c12a49a9fb and revised in 74fc8bd12db680e4fd9ce9a0a3d095704f4d4d75.

Thanks

**Comment by sbrannen** [comment]
> I've understood the purpose of that inversion (it took me a little while, to be honest :) ), 

Indeed, it's a bit tricky at first glance.

> I hope everything is okay this time.

It is... except that I determined that some of the tests involving Mockito are flaky. 🤔

@e-freni, since you submitted this PR, would you be interested in getting to the bottom of the flaky test you created?

- See #31353

**Comment by e-freni** [comment]
Sure, go ahead and assign me the issue

**Comment by sbrannen** [comment]
> @sbrannen sure, go ahead and assign me the issue

I unfortunately cannot _assign_ it to you; however, I've added a comment to make people aware that you plan to address it.

**Pull request closed without merging**
