### PR TITLE
Prevent instantiation of AnnotatedElementUtils

### PR DESCRIPTION
**Pull request by cheese10yun**
I think. The Util class should not be able to create objects.
So I added the abstract keyword to the AnnotatedElementUtils class

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cheese10yun Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1848)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1848) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@cheese10yun Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1848)!

**Review by nvnmandadhi — APPROVED** [review]

**Review by snicoll — APPROVED** [review]

**Comment by snicoll** [comment]
@cheese10yun thank you for your first contribution to Spring Framework. This is now merged in `master`.

**Comment by cheese10yun** [comment]
@snicoll I really appreciate your code being merged.

It is a very good experience.

**Pull request closed without merging**
