### PR TITLE
4.3.x

### PR DESCRIPTION
**Pull request by bungrudi**
I need to code custom SpringSessionContext and need to know the inside of TransactionSynchronizationManager.java.
However cannot seem to find spring-tx 4.3.13 source package.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bungrudi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1663)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1663) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by sdeleuze** [comment]
I guess you submitted this PR by mistake, please use https://stackoverflow.com/ if you have Spring related questions.

**Comment by rstoyanchev** [comment]
> However cannot seem to find spring-tx 4.3.13 source package.

It's under "Releases".

**Comment by rstoyanchev** [comment]
@snicoll regarding the 4.3.13 sources question, I don't see any tags after 4.3.10.

**Comment by snicoll** [comment]
Github tags you mean? There are there for me.

**Comment by rstoyanchev** [comment]
Hm, indeed I see it under https://github.com/spring-projects/spring-framework/tags, but not locally with `git tag`...

**Pull request closed without merging**
