### PR TITLE
Replace lambdas with method references

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by rstoyanchev** [comment]
I believe some of this intentional, i.e. lambda used only for functional interfaces.

**Comment by rstoyanchev** [comment]
Also note that multipart support is undergoing review with polish and refactoring throughout. It might be best to withdraw those parts from this PR.

**Comment by eddumelendez** [comment]
@rstoyanchev PR updated

**Comment by rstoyanchev** [comment]
Thanks

**Comment by rstoyanchev** [comment]
It looks like these were already resolved since the PR was raised.

**Pull request closed without merging**
