### PR TITLE
SPR-16627 - Address race condition within spring that causes about-to-be-created-bean exceptions

### PR DESCRIPTION
**Pull request by toaler**
See full details here:

https://jira.spring.io/browse/SPR-16627

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@toaler Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1750)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1750) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@toaler Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1750)!

**Comment by jhoeller** [comment]
Addressed along with SPR-16625 in a slightly revised fashion. Thanks for the PR, in any case!

**Comment by toaler** [comment]
@jhoeller what commit did you address this in?  I'd like to review.

**Comment by toaler** [comment]
@jhoeller nevermind, found it in 8d8e218b52274055d7b1854f3363c8c8c4bd71f2.

**Pull request closed without merging**
