### PR TITLE
Option to create Exception response to MockRestResponseCreators

### PR DESCRIPTION
**Pull request by chtompki**
Issue: [SPR-14458](https://jira.spring.io/browse/SPR-14458). This accommodates for a `SocketTimeoutException` happening during calling of the `RestTemplate` that has a `MockRestServiceServer` bound to it. The only other way that I could find to do this is by doing the following:

```java
RestTemplate restTemplate = new RestTemplate();
restTemplate.setInterceptors(Collections.singletonList(new MyWhackoPersonalInterceptor()));
SimpleClientHttpRequestFactory requestFactory = new SimpleClientHttpRequestFactory();
requestFactory.setConnectTimeout(1);
requestFactory.setReadTimeout(1);
restTemplate.setRequestFactory(requestFactory);
MockRestServiceServer mockServer = MockRestServiceServer.bindTo(restTemplate)
    .build();
mockServer.expect(requestTo("/something")).andRespond(
    request -> {
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {}
        return new MockClientHttpResponse("{}".getBytes(), HttpStatus.OK);
    }
);
 restTemplate.getForEntity("/something", String.class);
```

which would contain considerable redundancy between this declaration and potential future declarations. Do you have any thoughts on this change?

### CODE REVIEW

**Review by mukteshkrmishra — APPROVED** [review]
Liked it. LGTM

**Comment by chtompki** [comment]
Do let me know if I've gone through this change appropriately as I've not contributed to `spring-projects/spring-framework` before. I've only contributed to boot (and incidentally am on the apache-commons PMC).

**Comment by chtompki** [comment]
Nudge??

**Comment by snicoll** [comment]
@chtompki the issue has been assigned to `5.x backlog` (so not prioritized to a specific feature release). Spring Framework uses Jira to handle issues.

**Pull request closed without merging**
