### PR TITLE
fix bug: run "gradle eclipse" may cause NPE.

### PR DESCRIPTION
**Pull request by hall-wong**
fix bug: run "gradle eclipse" may cause NPE.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hall-wong Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1145)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1145) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by sbrannen** [comment]
@hall-wong, can you please let us know how you encountered the NPE -- for example, which exact commands did you execute?

By the way, running `gradle eclipse` on its own is not necessarily supported. Rather, you should execute the provided `import-into-eclipse.sh` or `import-into-eclipse.bat` script.

**Comment by hall-wong** [comment]
@sbrannen Well, here are steps to reproduce this error:
after I clone this repo, I import the project to Eclipse;
then I run `gradle eclipse`, and NPE is thrown;
This error occurred on my MacBook Pro, I don't have log now, I'll post it later.

And I run `import-into-eclipse` script on my PC(Windows 7, 64-bit), but it caused another error:

> Downloading https://services.gradle.org/distributions/gradle-3.0-bin.zip
> Exception in thread "main" java.net.SocketTimeoutException: Read timed out
>         at java.net.SocketInputStream.socketRead0(Native Method)
>         at java.net.SocketInputStream.socketRead(Unknown Source)
>         at java.net.SocketInputStream.read(Unknown Source)
>         at java.net.SocketInputStream.read(Unknown Source)
>         at sun.security.ssl.InputRecord.readFully(Unknown Source)
>         at sun.security.ssl.InputRecord.read(Unknown Source)

Should I upgrade Gradle to 3.0 manually(my Gradle's version is 2.14.1)?

**Comment by sbrannen** [comment]
> @sbrannen Well, here are steps to reproduce this error:
after I clone this repo, I import the project to Eclipse;
then I run gradle eclipse, and NPE is thrown;
This error occurred on my MacBook Pro, I don't have log now, I'll post it later.

Again, for this issue, please do not run `gradle eclipse` on its own. You should instead run the dedicated `import-into-eclipse` script **before** importing any projects into Eclipse. The `import-into-eclipse` script prints detailed instructions on the steps you need to take to properly import the projects into Eclipse.

**Comment by sbrannen** [comment]
> Downloading https://services.gradle.org/distributions/gradle-3.0-bin.zip
Exception in thread "main" java.net.SocketTimeoutException: Read timed out

That sounds like a network error.

Perhaps you have a local firewall or anti-virus software that prevent Gradle from connecting to the Internet. In that case, you'll need to allow Java/Gradle to open connections.

**Comment by hall-wong** [comment]
Well, I can't reproduce this error on my MacBook after I reboot it.
However, after I finish `gradle eclipse` command, I can import the sub-project correctly, everything seems fine.
Thanks for the guide.

**Comment by sbrannen** [comment]
Glad to hear it works for you, and thanks for letting us know.

**Pull request closed without merging**
