### PR TITLE
Simplify code for SimpleClientHttpRequestFactory.prepareConnection

### PR DESCRIPTION
**Pull request by rsvoboda**
Simplify code for SimpleClientHttpRequestFactory.prepareConnection

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rsvoboda Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25856)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25856) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rsvoboda Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25856)!

**Comment by rstoyanchev** [comment]
This is merged. Thanks for pull request.

**Comment by izeye** [comment]
Based on @rstoyanchev this seems to be supposed to be closed as a result of its merge.

**Comment by bclozel** [comment]
Thanks @izeye !

**Pull request closed without merging**
