### PR TITLE
Allow `BeanNameViewResolver` to optionally use a supplied `ApplicationContext`

### LINKED ISSUE #29383: Make `BeanNameViewResolver` use a supplied `ApplicationContext`
With the deprecation of the `XmlViewResolver` and `ResourceBundleViewResolver` it is harder to have multiple `ViewResolver` instances to resolve a view with the same name but for a different content-types. 

I thought of using the `BeanNameViewResolver` however as that is `ApplicationContextAware` it gets the `ApplicationContext` it runs in injected, resulting in an error. 

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pdfViewResolver' defined in class path resource [com/apress/spring6recipes/court/config/ViewResolverConfiguration.class]: Cannot reinitialize with different application context: current one is [org.springframework.context.support.GenericApplicationContext@61b718e, started on Tue Oct 25 17:31:00 GMT 2022], passed-in one is [WebApplicationContext for namespace 'dispatcher-servlet', started on Tue Oct 25 17:31:00 GMT 2022]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:606)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:931)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:916)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584)
        at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:699)
        at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:576)
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:530)
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:169)
        at jakarta.servlet.GenericServlet.init(GenericServlet.java:158)
        at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:140)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:995)
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:696)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:128)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.springframework.context.ApplicationContextException: Cannot reinitialize with different application context: current one is [org.springframework.context.support.GenericApplicationContext@61b718e, started on Tue Oct 25 17:31:00 GMT 2022], passed-in one is [WebApplicationContext for namespace 'dispatcher-servlet', started on Tue Oct 25 17:31:00 GMT 2022]
        at org.springframework.context.support.ApplicationObjectSupport.setApplicationContext(ApplicationObjectSupport.java:83)
        at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:109)
        at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:85)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:420)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
```

It would be nice if we could use the constructor to pass in an `ApplicationContext` to be used with the `BeanNameViewResolver` much like the `DispatcherServlet` does. This way you can have a small `ApplicationContext` with functional beans to resolve to views with the same name but for different content-types.

### PR DESCRIPTION
**Pull request by mdeinum**
With the`XmlViewResolver`/`ResourceBundleViewResolver` you could have multiple instances of it and provide and XML application context to configure the views. This comes in handy when allowing 1 controller to render 2 different things like an Excel or a PDF depending on the requested Content-Type. Those are now deprecated and there is no real replacement for this.

Prior to this commit the `BeanNameViewResolver` would always resolve the views from the configuration it was defined in. Passing in a pre-configured application context would result in an error at runtime. Now it is possible to pass in an application context through the constructor which will be used to resolve the views from. Making it possible to have multiple instances and have the functionality as with multiple `XmlViewResolver`/`ResourceBundleViewResolver` with a `ContentNegotiatingViewResolver`.

Closes: #29383

### CODE REVIEW

**Review by rstoyanchev — COMMENTED** [review]
@mdeinum thanks for the suggestion. 

We agree that this would be a useful change, but we have specific requirements for the implementation. The key goal is to to have a clear lifecycle of the child `ApplicationContext`, and if that's passed as a constructor argument, it's unclear who is responsible to manage it. By comparison, `XmlViewResolver` creates and manages the child context internally without exposing it, and applications instead only configure the location for config files.

A similar approach could apply here as well with the child `ApplicationContext` managed internally, and applications specifying configuration classes to use. `BeanNameViewResolver` itself can remain unaware of this, and only expose a protected method to create a custom context. A subclass would then use this to create and manage the child `ApplicationContext`, connect it to its parent, and so on. This also leaves room for alternative implementations for how a child context is created and managed.

I'm going to schedule this as 6.1 M1 work. Let is know if you plan evolve the PR along those lines? We are also happy to pick it up from here, in which case I'd close this and re-open the issue.

**Comment by mdeinum** [comment]
Instead of shoehorning this into the existing `BeanNameViewResolver` it might make sense to introduce a better variant of the `XmlViewResolver` but then for Java Configuration classes instead of XML. That would be a minor refactoring of the removed `XmlViewResolver` to work with Java based configuration. While still keeping the original `BeanNameViewResolver` else it might change the existing behavior or make it do 2 things instead of 1 it currently does.

**Comment by rstoyanchev** [comment]
Thanks for the thought. You're right that we are in effect creating an `XmlViewResolver` replacement but for Java config. That said we don't have to repeat the exact previous arrangement. I would argue, `BeanNameViewResolver` and `XmlViewResolver` were very close, both looking up a `View` bean, with `XmlViewResolver` being more specialized in terms the configuration it uses. Aside from that their actual lookup methods mirror each other, and this could have been a parent-child relationship from the start.

**Comment by rstoyanchev** [comment]
On further thought, the hierarchical approach isn't a strict goal. Re-imagining `XmlViewResolver` for Java config is a good place to start for continuity. We can decide on whether to turn it into a hierarchy.

**Comment by rstoyanchev** [comment]
Scheduled for 6.1 M1 if you decide to give it a try, and push an updated version.

**Comment by sbrannen** [comment]
@mdeinum, and updates on this?

**Comment by mdeinum** [comment]
Haven't done anything for this, swamped with work and personal stuff :(.

**Comment by sbrannen** [comment]
> Haven't done anything for this, swamped with work and personal stuff :(.

No problem.

Do you think you'll find time to include it in 6.1 M2?

If not, we can move this issue to a backlog.

**Comment by mdeinum** [comment]
I probably have some time on my hands before 6.1 M2 to polish this request.

**Comment by mdeinum** [comment]
Closed in favor of a new PR https://github.com/spring-projects/spring-framework/pull/30772

I managed to mess up the rebase (not sure how). It was quicker to create a new PR then to try to fix the rebase.

**Pull request closed without merging**
