### PR TITLE
Fix spring-orm tests with eclipselink and Java 18+

### PR DESCRIPTION
**Pull request by bdshadow**

### CODE REVIEW

**Comment by bdshadow** [comment]
@sdeleuze  it contains JPA update, because the issue reported by @sbrannen, which I fixed is about JPA: https://github.com/spring-projects/spring-framework/issues/30648

**Comment by bdshadow** [comment]
actually, that's why i made 2 commits. I can remove the one for kotlin fixes

**Comment by snicoll** [comment]
Let's have a look to the other commit indeed.

**Comment by snicoll** [comment]
Unfortunately, we can't change the dependency of Eclipselink like that as we need to build against 3.0 to match our JPA 3.0  / EE 9 baseline. We should probably see if we can change the dependency when the tests run with Java 21.

**Comment by snicoll** [comment]
However, @jhoeller pointed out that Eclipselink `3.0.4-RC1` was released this week and could be used instead.

**Pull request closed without merging**
