### PR TITLE
SPR-16956 - Propagate read-only status as FlushMode.MANUAL to Hibernate Session

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://jira.spring.io/browse/SPR-16956

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@vladmihalcea Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1861)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1861) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@vladmihalcea Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1861)!

**Comment by jhoeller** [comment]
As per our JIRA discussion, this has been rolled into master in a slightly extended fashion, only applying `setDefaultReadOnly(true)` to transaction-local resources... which means no side effects for later access, and no cleanup neessary. Thanks for the PR, in any case!

**Comment by jwgmeligmeyling** [comment]
@jhoeller was similar behaviour ever implemented for Hibernate 6?

**Comment by vladmihalcea** [comment]
@jwgmeligmeyling Yes, the optimizations work just fine with Hibernate 6 because they are applied by the `HibernateJpaDialect`.

Check out [this line](https://github.com/spring-projects/spring-framework/blob/main/spring-orm/src/main/java/org/springframework/orm/jpa/vendor/HibernateJpaDialect.java#L202) in the `HibernateJpaDialect` for more details.

**Pull request closed without merging**
