### PR TITLE
Add HeadMapping shortcut annotation for @RequestMapping(method = RequestMethod.HEAD)

### PR DESCRIPTION
**Pull request by SympathyForTheDev**
I have signed and agree to the terms of the Spring Individual Contributor License Agreement.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@DevWantJustHaveFun Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1207)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1207) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@DevWantJustHaveFun Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1207)!

**Comment by rstoyanchev** [comment]
@DevWantJustHaveFun as of 4.3 we have built-in support for HTTP HEAD and OPTIONS so that any GET mapped method should also support HEAD with no extra code. I'm wondering what your case is?

**Comment by DevWantJustHaveFun** [comment]
Hello, thanks for your response, in some projects, I have this kind of code 

` 
@RequestMapping(value = "/ping", method = RequestMethod.HEAD)
@ResponseStatus(value = HttpStatus.OK)
public void ping()
{
    // pong ....
}
` 
I use this with a load balancer (Haproxy), the goal of this method is to check the health of my springboot application.

I want just to add a new annotation shortcut like "@GetMapping"

` 
@HeadMapping(value = "/ping")
@ResponseStatus(value = HttpStatus.OK)
public void ping()
{
    // pong ....
}
` 

If you have a better syntax for my case, please tell me. 
Thanks,

**Comment by rstoyanchev** [comment]
This will work:
````java
@GetMapping("/ping")
public void ping()
{
// pong ....
}
````

**Comment by jhoeller** [comment]
I'm rather strongly opposed to adding an explicit HEAD mapping since we generally want HEAD to be handled through `@GetMapping` (considering HEAD simply as a bodyless GET variant), and since a custom HEAD mapping for special-purpose scenarios can be expressed through the general `@RequestMapping` annotation anyway.

**Comment by DevWantJustHaveFun** [comment]
Ok, I have tested your solution it's work (with @ResponseStatus(value = HttpStatus.OK))

but I have two points 

1/ it's not obvious  in the code, if I see that in an API, I will try to call the endpoint with a "GET" method not a "HEAD" 

2/ With my solution if you call the endpoint with a GET method you will get an error 405 "Method Not Allowed"


> curl -i -X HEAD http://localhost:8080/ping

> HTTP/1.1 200 OK
> Set-Cookie: JSESSIONID=KHbbUS4TsdPxBUbD6NUT0vJCuxwGuuJjWI2PjlTh; path=/
> Content-Length: 0
> Date: Mon, 17 Oct 2016 13:16:21 GMT
> Set-Cookie: SERVERID=; Expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/
> 

>  curl -i -X GET http://localhost:8080/ping

> HTTP/1.1 405 Method Not Allowed

**Comment by jhoeller** [comment]
Good points, those are indeed reasons to avoid `@GetMapping.` However, if you'd like such a custom tailored HEAD endpoint, what's wrong with `@RequestMapping(method=HEAD)`? The whole point of `@GetMapping` and co is a convenience for common cases, with `@RequestMapping` remaining as the common underlying mapping mechanism (that `@GetMapping` and co are literally composed from). I would argue that a custom ping endpoint does not qualify as such a common case, and that the common way of handling HEAD is indeed as a combined GET/HEAD endpoint along the lines of `@GetMapping.`

Also, you could easily compose a custom `@HeadMapping` annotation yourself, possibly even as a custom `@PingMapping` variant for your particular use case...

**Comment by DevWantJustHaveFun** [comment]
@jhoeller Thanks for your reponse.

Annotations  shorcut like `@GetMapping`  are cool because more readable and they reduce boilerplate.
They are more like annotations defined in the JSR-339, and the @HEAD annotation exist in the JSR-339.

I have no problem with the usage of @RequestMapping(method=HEAD) but I thought this method was forgotten in the Spring implementation of the `@RequestMapping` shortcut annotations

**Comment by rstoyanchev** [comment]
> With my solution if you call the endpoint with a GET method you will get an error 405 "Method Not Allowed" but not with the @GetMapping, for me it's look better because my "ping" method should be used only with "HEAD"

I think that only points to the fact that HTTP HEAD is perhaps not used for it's intended to do. The definition of HEAD is that it behaves exactly like GET minus the body. So I would ask why not use HTTP GET for the ping to begin with?

**Comment by DevWantJustHaveFun** [comment]
Ok, I will continue to use my custom annotations in my own project, you can decline the pull request, if it's not relevant for the framework.
Anyway thanks for your time.

**Pull request closed without merging**
