### PR TITLE
SPR-16324 - Added overloading methods to addPathPatterns and excludePathPatterns

### PR DESCRIPTION
**Pull request by rinorium**
I've decided to add these methods because it's inconvenient to add paths to method one by one, separating them by commas, if I want to include them to properties file, I'm forced to add them through cycle. This is an implementation of method that makes it possible to use the list of strings in a way that's more convenient.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Linolium Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1634)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1634) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
@Linolium thank you so much for your first contribution to Spring Framework. We need a Jira issue to discuss this change, can you please [create one](https://jira.spring.io/browse/SPR)?

**Comment by Linolium** [comment]
@snicoll sure, here is a [link on issue ](https://jira.spring.io/browse/SPR-16324)

**Comment by rstoyanchev** [comment]
Merged.

**Pull request closed without merging**
