### PR TITLE
`@Inject` cannot be used with Optional

### PR DESCRIPTION
**Pull request by destan**
fix a wrong statement about that

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@destan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1149)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1149) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@destan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1149)!

**Comment by snicoll** [comment]
@destan what's wrong with the statement exactly? `Inject` has no optional so if you want to inject a component that _might_ not be there you'd write the following:

```java
@Named
public class Foo {

    @Inject
    public Foo(Optional<Bar> bar) { ... }

}
```

**Comment by destan** [comment]
@snicoll sorry I misinterpret the feature.

**Pull request closed without merging**
