### PR TITLE
Add coroutine variant of `WebExceptionHandler`

### PR DESCRIPTION
**Pull request by earlgrey02**
As in the case of `CoWebFilter`, I added `CoWebExceptionHandler`, **a coroutine variant** of `WebExceptionHandler` used for global exception handling in Spring WebFlux.

### CODE REVIEW

**Comment by sdeleuze** [comment]
We need to be careful about not going too far in terms of Coroutines duplications of Reactive contrats, but I think I am in favor of that one for 2 reaons:
 - That seems indeed pretty close to `CoWebFilter` use cases which is pretty popular among Kotlin developers I think
 - This is not yet reflected in the PR, but `CoWebExceptionHandler` could introduced the same kind of Coroutines context management [as in `CoWebFilter`](https://github.com/spring-projects/spring-framework/blob/416eff1b0488076a5f7ff2f552e46714736df526/spring-web/src/main/kotlin/org/springframework/web/server/CoWebFilter.kt#L38-L45).

@rstoyanchev Would you be ok for that?

@earlgrey02 What about refining your PR to provide Coroutines context management like `CoWebFilter` does?

**Comment by rstoyanchev** [comment]
If `CoWebFilter` exists then yes a `CoWebExceptionHandler` next to it makes sense.

**Comment by earlgrey02** [comment]
> We need to be careful about not going too far in terms of Coroutines duplications of Reactive contrats, but I think I am in favor of that one for 2 reaons:
> 
> * That seems indeed pretty close to `CoWebFilter` use cases which is pretty popular among Kotlin developers I think
> * This is not yet reflected in the PR, but `CoWebExceptionHandler` could introduced the same kind of Coroutines context management [as in `CoWebFilter`](https://github.com/spring-projects/spring-framework/blob/416eff1b0488076a5f7ff2f552e46714736df526/spring-web/src/main/kotlin/org/springframework/web/server/CoWebFilter.kt#L38-L45).
> 
> @rstoyanchev Would you be ok for that?
> 
> @earlgrey02 What about refining your PR to provide Coroutines context management like `CoWebFilter` does?

Instead of creating a separate `COROUTINE_CONTEXT_ATTRIBUTE` for `CoWebExceptionHandler`, I reused the `COROUTINE_CONTEXT_ATTRIBUTE` used in the existing `CoWebFilter` and handler(`CoroutineContextAware HandlerFunction`).

**Comment by sdeleuze** [comment]
Merged and polished, thanks for your contribution.

**Pull request closed without merging**
