### PR TITLE
Update DefaultListableBeanFactory's determineHighestPriorityCandidate

### PR DESCRIPTION
**Pull request by ghost**
Update method determineHighestPriorityCandidate of DefaultListableBeanFactory. Runs define the same priority, but highestPriority.

### CODE REVIEW

**Comment by quaff** [comment]
I don't understand what problem you are trying to resolve.

**Comment by york-lee** [comment]
> I don't understand what problem you are trying to resolve.

As I understand it, the purpose of this method is to get the highest priority bean, so we just need to ensure that the highest priority is not repeated. There is no need to restrict other low-priority beans.

**Comment by quaff** [comment]
> > I don't understand what problem you are trying to resolve.
> 
> As I understand it, the purpose of this method is to get the highest priority bean, so we just need to ensure that the highest priority is not repeated. There is no need to restrict other low-priority beans. Or some other purpose That I don't understand？

Still not clear, are you fix a bug or improve code readability?

**Comment by york-lee** [comment]
> > > I don't understand what problem you are trying to resolve.
> > 
> > 
> > As I understand it, the purpose of this method is to get the highest priority bean, so we just need to ensure that the highest priority is not repeated. There is no need to restrict other low-priority beans. Or some other purpose That I don't understand？
> 
> Still not clear, are you fix a bug or improve code readability?

I think it's a bug.

**Comment by quaff** [comment]
> > > > I don't understand what problem you are trying to resolve.
> > > 
> > > 
> > > As I understand it, the purpose of this method is to get the highest priority bean, so we just need to ensure that the highest priority is not repeated. There is no need to restrict other low-priority beans. Or some other purpose That I don't understand？
> > 
> > 
> > Still not clear, are you fix a bug or improve code readability?
> 
> I think it's a bug.

Then you should include a test case in this PR.

**Comment by york-lee** [comment]
> > > > > I don't understand what problem you are trying to resolve.
> > > > 
> > > > 
> > > > As I understand it, the purpose of this method is to get the highest priority bean, so we just need to ensure that the highest priority is not repeated. There is no need to restrict other low-priority beans. Or some other purpose That I don't understand？
> > > 
> > > 
> > > Still not clear, are you fix a bug or improve code readability?
> > 
> > 
> > I think it's a bug.
> 
> Then you should include a test case in this PR.

OK, I will complete it.

**Comment by york-lee** [comment]
suspend

**Pull request closed without merging**
