### PR TITLE
Replace .equals("") with .isEmpty()

### PR DESCRIPTION
**Pull request by Laffini**
isEmpty is faster, has less byte code and is easier to read.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Laffini Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25723)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25723) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Laffini Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25723)!

**Comment by wind57** [comment]
the amount of byte-code is irrelevant; easier to read is subjective too. May I ask if you have specific proof of "faster"?

**Comment by Laffini** [comment]
Benchmarks can be found here: https://medium.com/javarevisited/micro-optimizations-in-java-string-equals-22be19fd8416

**Comment by jhoeller** [comment]
We generally updated the core framework codebase towards `isEmpty` usage where it matters already.

This PR only covers a test case and a javadoc entry, both of which are arguably fine in terms of readability the way they are. I'd rather leave this as-is. Thanks for raising it, in any case!

**Pull request closed without merging**
