### PR TITLE
SPR-15892 - Url parameter based version strategy support

### PR DESCRIPTION
**Pull request by zsoltii**
Prefix based version path strategy has a problem with css.

If css include any relative url, the server can not resolve relative url, because it has two version prefix in the url.

**Example**

The version: 1.0.0

The css url: http://localhost/application/1.0.0/css/test.css

Original css content
```
body {
    background-image: url("img/picture.jpg");
    background-size: cover;
}
```
Modified css content
```
body {
    background-image: url("1.0.0/img/picture.jpg");
    background-size: cover;
}
```
The picture.jpg url will be: http://localhost/application/1.0.0/css/1.0.0/img/picture.jpg but the expected is http://locahost/application/1.0.0/css/img/picture.jpg

**Solution**

We was make the UrlParameterFixedVersrionStrategy class.

The css url: http://localhost/application/css/test.css?v=1.0.0

Modified css content
```
body {
    background-image: url("img/picture.jpg?v=1.0.0");
    background-size: cover;
}
```
the picture.jpg url: http://localhost/application/css/img/picture.jpg?v=1.0.0

MvcConfig example
```
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import org.springframework.web.servlet.resource.AbstractVersionStrategy;
import org.springframework.web.servlet.resource.UrlParameterFixedVersionStrategy;
import org.springframework.web.servlet.resource.VersionResourceResolver;

@Configuration
@ComponentScan({"test.controller"})
public class MvcConfig extends WebMvcConfigurerAdapter {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        AbstractVersionStrategy fixedVersionStrategy = new UrlParameterFixedVersionStrategy("1.0.0");
        VersionResourceResolver versionResourceResolver = new VersionResourceResolver()
                .addVersionStrategy(fixedVersionStrategy, "/**");

        registry.addResourceHandler("/**")
                .addResourceLocations("classpath:/other-resources/")
                .resourceChain(true)
                .addResolver(versionResourceResolver);
    }

}
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@zsoltii Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1503)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1503) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@zsoltii Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1503)!

**Comment by snicoll** [comment]
@zsoltii please create a Jira issue for this change.

**Comment by zsoltii** [comment]
jira issue: https://jira.spring.io/browse/SPR-15892

**Pull request closed without merging**
