### PR TITLE
Avoid NoSuchMethodException generation

### PR DESCRIPTION
**Pull request by anavrotski**
In my application this exception is generated at rate ~2000 exceptions per one minute (it is generated inside spring-data-jpa, my application intensively interacts with database).

This change may help to avoid slow operation of creation exception and its stack trace.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@flintmail Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1492)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1492) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@flintmail Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1492)!

**Comment by FancyCoder0** [comment]
Dear flintmail,

We are working on identifying redundant development and duplicated pull requests. We have found there are pull requests: https://github.com/spring-projects/spring-framework/pull/1630 https://github.com/spring-projects/spring-framework/pull/1629 https://github.com/spring-projects/spring-framework/pull/1628 which might be potentially duplicated to this one. We would really appreciate if you could help us to validate and give us feedback.

Thank you very much for your time!

Sincerely,
Luyao

**Comment by bclozel** [comment]
Closing because of https://github.com/spring-projects/spring-framework/pull/1628#issuecomment-354589149

Thanks for your contribution

**Pull request closed without merging**
