### PR TITLE
SPR-17219 - Use completionService to replace of ExecutorService

### PR DESCRIPTION
**Pull request by qudh1**
modify the implement of submit method

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@qudh1 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1945)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1945) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
@qudh1 we need a Jira issue to discuss this change. Can you please [create  one](https://jira.spring.io/browse/SPR)?

**Comment by qudh1** [comment]
Sure, @snicoll, the jira issue is https://jira.spring.io/browse/SPR-17219. Thank you.

**Comment by muhammad-wasi-confiz** [comment]
How can you take advantage of CompletionService's **take** method? Don't you think **ExecutorService** is enough here?

**Comment by waasikhaan** [comment]
How can you take advantage of CompletionService's take method? Don't you think ExecutorService is enough here?

**Comment by waasikhaan** [comment]
@qudh1 

> A CompletionService that uses a supplied Executor to execute tasks. This class arranges that submitted tasks are, upon completion, placed on a queue accessible using take.

This is what the documentation said so IMO if you are not exposing the **ComplitionService** then you will not be able to take advantage of **ComplitionService**. Correct me if i am wrong here. :)

**Comment by snicoll** [comment]
Sorry it took us so long to process this. I agree with @waasikhaan and the method you've changed is really meant to invoke the same API on the underlying `ExecutorService`. Thanks for the PR, in any case.

**Pull request closed without merging**
