### PR TITLE
Use `private static` instead of `static private` for method declarations

### PR DESCRIPTION
**Pull request by XenoAmess**
as title

### CODE REVIEW

**Comment by sbrannen** [comment]
This has been merged into `master`.

Thanks

**Comment by izeye** [comment]
The title seems to be the opposite to what has been done.

**Comment by sbrannen** [comment]
> The title seems to be the opposite to what has been done.

Indeed. That was my mistake when I reworded this PR's title incorrectly. I'll fix it now, but the associated commit message will unfortunately remain misleading.

**Comment by XenoAmess** [comment]
> > The title seems to be the opposite to what has been done.
> 
> Indeed. That was my mistake when I reworded this PR's title incorrectly. I'll fix it now, but the associated commit message will unfortunately remain misleading.

@sbrannen @izeye 
Sorry for the mistake I made in commit message, and the delay of reply.

**Comment by sbrannen** [comment]
> > > The title seems to be the opposite to what has been done.
> > 
> > 
> > Indeed. That was my mistake when I reworded this PR's title incorrectly. I'll fix it now, but the associated commit message will unfortunately remain misleading.
> 
> @sbrannen @izeye
> Sorry for the mistake I made in commit message, and the delay of reply.

No worries. It was **I** who made the mistake in the commit message anyway. 😉

**Pull request merged**
