### PR TITLE
Skip setting hibernate.dialect for hibernate 6 or above

### LINKED ISSUE #30488: Error creating bean entityManagerFactory with spring boot 3.1.0-RC2. ClassNotFoundException: PostgreSQL95Dialect
**Affects:** spring boot 3.1.0-RC2
I tried to update spring boot 3.0.5 -> 3.1.0-RC2 and got the following error:
```
2023-05-15T12:11:38.518+06:00  INFO 49951 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-05-15T12:11:38.524+06:00 ERROR 49951 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: org/hibernate/dialect/PostgreSQL95Dialect
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1132) ~[spring-context-6.0.8.jar:6.0.8]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:907) ~[spring-context-6.0.8.jar:6.0.8]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.8.jar:6.0.8]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[spring-boot-3.1.0-RC2.jar:3.1.0-RC2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[spring-boot-3.1.0-RC2.jar:3.1.0-RC2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-3.1.0-RC2.jar:3.1.0-RC2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[spring-boot-3.1.0-RC2.jar:3.1.0-RC2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[spring-boot-3.1.0-RC2.jar:3.1.0-RC2]
	at com.arvgord.bankdemoserver.AppKt.main(App.kt:12) ~[main/:na]
Caused by: java.lang.NoClassDefFoundError: org/hibernate/dialect/PostgreSQL95Dialect
	at org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter.determineDatabaseDialectClass(HibernateJpaVendorAdapter.java:181) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter.buildJpaPropertyMap(HibernateJpaVendorAdapter.java:144) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter.getJpaPropertyMap(HibernateJpaVendorAdapter.java:128) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:365) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[spring-orm-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[spring-beans-6.0.8.jar:6.0.8]
	... 15 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.hibernate.dialect.PostgreSQL95Dialect
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 22 common frames omitted
```
I have the following application yaml:
```yaml
spring:
  profiles:
    active: 'prod'
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: ${POSTGRES_DRIVER:org.postgresql.Driver}
```
I see that the class PostgreSQL95Dialect no longer exists in Hibernate 6.2.2.Final but spring tries to load it **even though I use PostgreSQLDialect**
изображение

Issue moved from https://github.com/spring-projects/spring-data-jpa/issues/2952

### PR DESCRIPTION
**Pull request by quaff**
Versioned dialects are replaced with an unified dialect since 6.0 and removed since 6.2
This commit fix ClassNotFoundException for hibernate 6.2
Fix GH-30488

### CODE REVIEW

**Comment by mdeinum** [comment]
I doubt not setting it for 6.2 is the actual solution, but rather select the different class for 6.2 would be better imho (this would probably require some additional dynamic trickery for determining which class to use, due to classloading etc.).

**Comment by quaff** [comment]
> I doubt not setting it for 6.2 is the actual solution, but rather select the different class for 6.2 would be better imho (this would probably require some additional dynamic trickery for determining which class to use, due to classloading etc.).

Hibernate's automatic dialect resolution is more sophisticated than `HibernateJpaVendorAdapter.determineDatabaseDialectClass()`, I can't understand why spring do that, maybe it's workaround for old versions, we should rethink it now.

**Comment by mdeinum** [comment]
It will only do that if `spring.jpa.database` is set, if not set it won't do anything nor set anything. Next to that there are situations in which the `hibernate.dialect` is required else it won't even startup (there are many StackOverflow questions regarding this).

**Comment by snicoll** [comment]
Thanks both. Given that this only apply if we set the property, I am not keen to merge this. Just don't set these and Hibernate's defaults will apply. I wondered about deprecating those properties though but it looks like we're not there yet.

**Pull request closed without merging**
