### PR TITLE
Fix typo in Javadoc for AbstractJdbcCall

### PR DESCRIPTION
**Pull request by Alexscari7**
Fix typo in Javadoc for AbstractJdbcCall

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Alexscari7 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26254)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26254) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Alexscari7 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26254)!

**Comment by Alexscari7** [comment]
Fix typo in Javadoc for AbstractJdbcCall

**Comment by sbrannen** [comment]
This has been merged into `master`.

Thanks

**Pull request merged**
