### PR TITLE
marshalXmlStreamWriter  need respect StaxDriver

### PR DESCRIPTION
**Pull request by qxo**
fix namespace issue

### CODE REVIEW

**Comment by snicoll** [comment]
@qxo can you add a tes that reproduces the bug you're experiencing?

**Comment by qxo** [comment]
XStreamMarshaller.setStreamDriver with StaxDriver  and default namespace , then invoke the method see the issue: not respect the default namespce!
```
	QNameMap qmap = new QNameMap();
			qmap.setDefaultNamespace("http://mycompany.com/sample-spring-ws");
			qmap.setDefaultPrefix("ns1");
			StaxDriver staxDriver = new StaxDriver(qmap);
		...	
             setStreamDriver(staxDriver);			
```

**Comment by snicoll** [comment]
@qxo that's not what I am asking. Can you please push an update to your PR with a `@Test` that reproduces the issue.

**Comment by poutsma** [comment]
Merged in e8eeb99ac894dde7896d080c0bcb18335e49ee78

Thank you for leaving a PR, and sorry for taking this long to resolve it.

**Pull request closed without merging**
