### PR TITLE
Switch to spring-asciidoctor-backends

### PR DESCRIPTION
**Pull request by Buzzardo**
to get the new look and feel and new functionality. A side effect is a simpler docs.gradle file.

### CODE REVIEW

**Comment by sbrannen** [comment]
Thanks for the PR, @Buzzardo!

We'll give it a try before 6.0 RC1 to make sure that no links within or into the documentation are broken before merging.

**Comment by sbrannen** [comment]
@Buzzardo, are you aware of any potential changes to links, anchors, etc.?

Did you perform any such testing before and after switching the backend?

**Comment by bclozel** [comment]
Thanks @Buzzardo !
I've checked that resources are generated in the same place as before, code snippets are rendered properly (including the Java/Kotlin variant selectors), anchors are not broken and internal links are still working.

**Comment by bclozel** [comment]
Reopening as several things are broken after the deploy.

**Comment by bclozel** [comment]
Closed with 3e41d7f

**Pull request closed without merging**
