### PR TITLE
SPR-14496 - getDeclared

### PR DESCRIPTION
**Pull request by xenoterracide**
Having a problem with this method because it's not finding my inner class constructor

here's my test

```
    @Test
    public void testInstantiate() {

        Constructor<MyClassBar> ctor = ClassUtils.getConstructorIfAvailable( MyClassBar.class, MyInterface.class );
        assertThat( ctor, notNullValue() );
        }

private interface MyInterface {

    }

    private static class MyClassFoo implements MyInterface {

    }

    private static class MyClassBar {

        private final MyInterface myInterface;

        MyClassBar( final MyInterface myInterface )
        {
            this.myInterface = myInterface;
        }

        MyInterface getMyInterface()
        {
            return myInterface;
        }
    }
```

I can work put more work into this if desired.

### CODE REVIEW

**Comment by cmx1** [comment]
oh ,my god ,so good !!

**Comment by bclozel** [comment]
Thank you for the PR! Could you please create an issue for this pull request in the [Spring Framework issue tracker](https://jira.spring.io/browse/SPR). When you do, please make sure to fill the `Reference URL` with the link to this PR. Thanks!

**Comment by xenoterracide** [comment]
https://jira.spring.io/browse/SPR-14496

**Comment by snicoll** [comment]
The issue has been resolved, see the Jira issue for more details.

**Pull request closed without merging**
