### PR TITLE
Upgrade to Gradle 4.6

### PR DESCRIPTION
**Pull request by rognan**
Issue: [SPR-16475](https://jira.spring.io/browse/SPR-16475)

This required a change in spring-beans.gradle due to a change in Gradle. 

The commit where Gradle changed the field ```values``` to ```mutableValues``` and ```immutableValues``` can be [found here](https://github.com/gradle/gradle/commit/12ef6b4fb67d6a1fe4a1957b07b35971765ab9b0#diff-f23ae203a040e535b062a9ea165a12b9).

The commit where Gradle changed the method ```getValues``` to ```getMutableValues``` can be [found here](https://github.com/gradle/gradle/commit/e80043aaebf4e9416f9c62a0a01107c2d957f1f3#diff-f23ae203a040e535b062a9ea165a12b9)

### CODE REVIEW

**Comment by sbrannen** [comment]
Thanks for the PR.

Please note, however, that processing of this PR will have to wait until `master` has been switched from 5.0.x to 5.1.

**Comment by rognan** [comment]
Happy to help out, and so noted :)

**Comment by AsinRay** [comment]
Why not use io.spring as the Springframe package name?

**Comment by sbrannen** [comment]
@AsinRay, please note that this PR is solely about upgrading the version of Gradle used in the build.

In any case, if you are suggesting that the Spring Framework change the name of its base package, that is simply impossible.

**Comment by sbrannen** [comment]
Update: I'm currently trying out this PR locally since we just switched `master` to 5.1.

**Comment by sbrannen** [comment]
This has been merged into `master` in commit 17c16eaa9efac10d04db8c61146c2c93dcdd2ee1.

**Pull request closed without merging**
