### PR TITLE
SPR-17486 Fix NPE in ClientRequest

### PR DESCRIPTION
**Pull request by joaoe**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@joaoe Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2014)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2014) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@joaoe Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2014)!

**Comment by joaoe** [comment]
Quick link to bug report https://jira.spring.io/browse/SPR-17486

**Comment by jhoeller** [comment]
A fix for this is already in master, including a corresponding unit test, as per the resolution of SPR-17486. Sorry if I've been too quick there ;-) Thanks for the pull request, in any case!

**Comment by joaoe** [comment]
Even better. Thanks ! :)

**Pull request closed without merging**
