### PR TITLE
Fixed exception logging in AbstractApplicationContext

### PR DESCRIPTION
**Pull request by artaban**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@artaban Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1821)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1821) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by GleyderC** [comment]
Hello,

trigger@ifttt.com has been retired. Use trigger@applet.ifttt.com to trigger your Email Channel Applets.

—The IFTTT Team

**Comment by pivotal-issuemaster** [comment]
@artaban Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1821)!

**Comment by jhoeller** [comment]
This is intentional since we're only really logging the cancellation at that point, referring to the exception that triggered it. The exception itself bubbles up the call stack and will be logged by whoever triggered the refresh() call in the first place... This will typically end up in the same log stream but might in some scenarios also end up in a different log file, so our warn message also serves as a reminder there.

**Pull request closed without merging**
