### PR TITLE
Fix SPR-11759, added support of List<String> injection from YAML propert...

### PR DESCRIPTION
**Pull request by cooniur**
Related to this issue: https://jira.spring.io/browse/SPR-11759
Also related to this discussion: https://github.com/spring-projects/spring-boot/issues/501

### CODE REVIEW

**Comment by snicoll** [comment]
It's not that easy. You just broke collection injection (which is excercised by the test you had to change).

**Comment by cooniur** [comment]
I'd like to do more test. Thanks!

On Friday, February 27, 2015, Stéphane Nicoll <notifications@github.com>
wrote:

> It's not that easy. You just broke collection injection (which is
> excercised by the test you had to change).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-projects/spring-framework/pull/747#issuecomment-76382452>
> .
>


-- 
Sent from Gmail Mobile

**Comment by cooniur** [comment]
@snicoll 
Thanks for pointing this out! I'll try to find another solution.

**Comment by rubesMN** [comment]
Did this ever get in?

**Comment by cooniur** [comment]
@rubesMN 
No, it hasn't happen yet.

**Pull request closed without merging**
