### PR TITLE
ClientRequest show mutable ,because HttpMessageWriter need add a head…

### PR DESCRIPTION
**Pull request by qinarmy-zoro**
…er(eg: xxx-signatureOfBody)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kosmosimonyi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23732)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23732) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by kosmosimonyi** [comment]
please consider this advince

**Comment by sbrannen** [comment]
@kosmosimonyi, please do not open multiple PRs for the same change. You should instead rework your original PR if you wish to modify your PR.

However, in light of the fact that you have opened #23733, I am closing this PR as a duplicate.

**Comment by kosmosimonyi** [comment]
all client request message need add a header xxx-signature-body ,this signature for body bytes,I cannot add in original PR, I shouldn't add in in original PR, because duplicate me .

**Comment by kosmosimonyi** [comment]
eg: `
 assertEnvironmentMatch(message);

        MediaType contentType = updateContentType(message, mediaType);

        Flux<DataBuffer> body = this.encoder.encode(
                inputStream, message.bufferFactory(), elementType, contentType, hints);

        final SignatureWrapper signatureWrapper = createSignature(message, hints);

        // do signature of body
        body = body.map(dataBuffer -> doSignature(signatureWrapper, dataBuffer))
                .collectList()
                .doOnNext(dataBuffers -> appendSignatureHeader(message, signatureWrapper))
                .flatMapMany(Flux::fromIterable)
        ;

        // Response is not committed until the first signal...
        if (inputStream instanceof Mono) {
            HttpHeaders headers = message.getHeaders();
            if (headers.getContentLength() < 0 && !headers.containsKey(HttpHeaders.TRANSFER_ENCODING)) {
                body = body.doOnNext(data -> headers.setContentLength(data.readableByteCount()));
            }
        }
        return (isStreamingMediaType(contentType) ?
                message.writeAndFlushWith(body.map(Flux::just)) : message.writeWith(body));

`

**Comment by kosmosimonyi** [comment]
@sbrannen

**Pull request closed without merging**
