### PR TITLE
Expand acronyms `FQN` and `FQCN`

### PR DESCRIPTION
**Pull request by quaff**
We should insist on using either one to keep consistency, `FQCN` is more common in the Java ecosystem.

### CODE REVIEW

**Review by sbrannen — CHANGES_REQUESTED** [review]
I'd argue that we should follow best practices for technical writing by avoiding the use of undefined acronyms.

In other words, we should never use either FQN or FQCN without first defining what is meant by the acronym used, and if we are not going to use the term or acronym multiple times in the same paragraph/section/Javadoc, we should just omit the use of the acronym altogether.

Would you like to revise this PR accordingly?

**Comment by quaff** [comment]
> we should follow best practices for technical writing by avoiding the use of undefined acronyms.

Agreed totally.

> Would you like to revise this PR accordingly?

I'd like to, do you mean replacing all `FQCN` with `fully-qualified class name` ?

**Comment by sbrannen** [comment]
> I'd like to, 

👍 

> do you mean replacing all `FQCN` with `fully-qualified class name` ?

Yes, when it's used in text/Javadoc/comments.

When it's used in a code/syntax example, I usually go with something like `<fully-qualified class name>.<method-name>` instead of `FQN.methodName`.

**Comment by quaff** [comment]
> > I'd like to,
> 
> 👍
> 
> > do you mean replacing all `FQCN` with `fully-qualified class name` ?
> 
> Yes, when it's used in text/Javadoc/comments.
> 
> When it's used in a code/syntax example, I usually go with something like `<fully-qualified class name>.<method-name>` instead of `FQN.methodName`.

@sbrannen done.

**Comment by sbrannen** [comment]
This has been merged into `main` in 019c0b1d4e59c6f158c16b7fc6f7cecd6e96e89d and polished in 717b972f88c13ad774e533d1571a5668971d779f.

Thanks

**Pull request merged**
