### PR TITLE
Adding Kotlin code examples to Testing documentation.

### PR DESCRIPTION
**Pull request by kohlmu-pivotal**
Adding Kotlin code examples to Testing documentation.
See - gh-21778

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kohlmu-pivotal Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23545)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23545) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kohlmu-pivotal Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23545)!

**Review by sbrannen — CHANGES_REQUESTED** [review]
Please revert all lines that add a `public` modifier in Java test code examples, since that effectively undoes the work performed in 53f523001e4df6b84a2ff7e9c3ae360308bc32fa.

**Comment by sdeleuze** [comment]
Merged via a completely reworked commit via https://github.com/spring-projects/spring-framework/commit/b20a8c9d98a9d9cf655033249978aeec01208eb7.

**Pull request closed without merging**
