### PR TITLE
odata uses MERGE method for updating Entity

### PR DESCRIPTION
**Pull request by met-pub**
If we dont add MERGE HttpMethod here, then [preflight request with asking MERGE method will be rejected](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java#L117).

https://www.odata.org/documentation/odata-version-2-0/operations/
2. Operations
The OData service interface has a fixed number of operations that have uniform meaning across all the resources it can act on. These operations are retrieve, create, update and delete and they map to the GET, POST, PUT/MERGE and DELETE HTTP methods.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bianbian-org Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24429)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24429) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bianbian-org Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24429)!

**Review by rstoyanchev — CHANGES_REQUESTED** [review]
To add `MERGE` to the `HttpMethod` enum would imply support for it, but we don't actually support it nor any other custom HTTP methods, which I believe `MERGE` to b e. It's not clear whether that change alone would be sufficient either but regardless I don't think adding it to the enum is the way to go.

I see that `DefaultCorsProcessor` calls `HttpRequest` which has a `getMethodValue()` method and likewise `HttpHeaders` could be used to get the header value without turning it into `HttpMethod`. Perhaps you can start by trying to change `DefaultCorsProcessor` to use that method instead and see if that gets you far enough.

**Comment by bianbian-org** [comment]
OK. Finally I changed odata client to send PUT method.
[seems PUT/MERGE apply equally](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-odata/59d5abd3-7b12-490a-a0e2-9d9324b91893)

**Pull request closed without merging**
