### PR TITLE
Fix infinite loop bug in AnnotationScanner

### PR DESCRIPTION
**Pull request by yilianhuaixiao**
The original code
`isFiltered(source, context, classFilter)` when true,
 would cause  dead circle.
Maybe new code is right.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@yilianhuaixiao Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25429)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25429) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by sbrannen** [comment]
Have you encountered an exception or some form of infinite loop in your code regarding your proposed change?

If so, please elaborate.

In any case, please add a test to this PR that fails before the proposed change and passes after the proposed change.

Thanks

**Comment by yilianhuaixiao** [comment]
I add the testcase.
Before the bugfix, the testcase would cause infinite loop. After, the testcase could be passed.

**Comment by yilianhuaixiao** [comment]
@sbrannen Thanks for your advice

**Comment by sbrannen** [comment]
> I add the testcase.
> Before the bugfix, the testcase would cause infinite loop. After, the testcase could be passed.

Thanks!

We'll look into it.

**Comment by sbrannen** [comment]
Tentatively slated for 5.3 M2 for investigation.

**Comment by sbrannen** [comment]
This has been merged into `master` in 650cbeee1433aa38619691946c316d9d03a6512d and revised in 5442d8779aa6ae3d5495255853ef7be8a14ca6da.

Thanks!

----

@yilianhuaixiao, out of curiosity, since this code path is not executed in production code, how did you notice this bug?

**Comment by sbrannen** [comment]
See also #25477

**Comment by yilianhuaixiao** [comment]
@sbrannen  I am learning the spring-core  source codes rencently.

**Pull request closed without merging**
