### PR TITLE
Refactor of small pieces of code to java 8 for better readability

### PR DESCRIPTION
**Pull request by tminussi**
#I have decided to refactor some of Spring's code to Java 8 since Spring Framework 5 onwards must be Java 8 compatible, allowing legacy code to be refactored. I personally love lambda and streams, so if this PR is approved I will surely keep refactoring small chunks of code little by little.

I am not sure if I am compliant to Spring Guideline, so, please, let me know if I have done anything wrong so I can make it right next time.

PS: No behavior has been changed, so tests pass normally.

Thanks!

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tminussi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1493)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1493) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tminussi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1493)!

**Comment by tminussi** [comment]
Hello.
I am sure you guys have been pretty busy, but do you have any word on this?
Thanks,

Thales

**Comment by snicoll** [comment]
@tminussi sorry for the late reply. Thanks for submitting your first pull request! Unfortunately, please note that we're not usually doing such code style refinements via pull requests. If you'd like to provide further pull requests, please focus on feature tickets. For code style issues, you might simply create a JIRA task pointing out the refinement (or a whole range of refinements), with us sorting it out on our end and no pull request needed.

**Pull request closed without merging**
