### PR TITLE
Debug logging for WebSocket lifecycle in WebSocketStompClient

### PR DESCRIPTION
**Pull request by alexandrumm**
@pivotal-issuemaster This is an Obvious Fix

### CODE REVIEW

**Comment by rstoyanchev** [comment]
I think this should be done by decorating the WebSocketHandler (i.e. `WebSocketTcpConnectionHandlerAdapter`) with `LoggingWebSocketHandlerDecorator` consistent with what we do in other places like `WebSocketConnectionManager` and `WebSocketHttpRequestHandler`.

**Comment by alexandrumm** [comment]
Hello, @rstoyanchev. 
First of all thanks for responding and taking care of this PR. 
I have a question with regards to your suggestion, `WebSocketTcpConnectionHandlerAdapter` it is also implementing the interface `ListenableFutureCallback` and the `LoggingWebSocketHandlerDecorator` does not expect or suppose, I think, to cover this type of handler, so could you please give me a hint here on how to proceed?

Thanks in advance!

**Comment by rstoyanchev** [comment]
This should be fine:
```java
WebSocketTcpConnectionHandlerAdapter adapter =  new WebSocketTcpConnectionHandlerAdapter(session);
getWebSocketClient()
        .doHandshake(new LoggingWebSocketHandlerDecorator(adapter), handshakeHeaders, url)
        .addCallback(adapter);
```

**Comment by alexandrumm** [comment]
Right, I missed the obvious solution there. Thanks a lot! :)

**Pull request closed without merging**
