### PR TITLE
Remove redundant escapes in regular expressions

### PR DESCRIPTION
**Pull request by hyeonisism**
Remove redundant character escape in RegExp

### CODE REVIEW

**Comment by sbrannen** [comment]
Technically, those escape sequences for closing braces are not _redundant_ but rather _unnecessary_.

As for whether or not it makes sense to remove them is (in my opinion) a matter of taste. In other words, it's technically correct to omit the escaping for a closing brace (and more concise), but many people are accustomed to escaping all special characters (opening and closing).

In any case, was there a reason you did not remove all such unnecessary escaping in the `GLOB_PATTERN`?

**Comment by hyeonisism** [comment]
@sbrannen 
When I revised the code, there was an unnecessary RegExp and I deleted it.
But listening to your opinion, I seem to have tried to break down the style that many have.
However, I think there is progress if technological pursuit of correct. What is your opinion?

Apart from the earlier story, `GLOD_PATTERN` part is a mistake I missed.

Thank you for sharing good idea.

**Comment by rstoyanchev** [comment]
Other classes where this exists:

AbstractHttpSendingTransportHandler
ClassPathResourceTests
CustomizableTraceInterceptor
MessageBrokerBeanDefinitionParserTests
RedirectView
RegexPathElement
TestContextResourceUtils
UriComponents
UriComponentsBuilder
WebSocketMessageBrokerConfigurationSupportTests

**Comment by hyeonisism** [comment]
@rstoyanchev 
You mean If I wanted to, I have to apply this whole thing?
 I'd like to. Can I proceed from this Branch?

**Comment by rstoyanchev** [comment]
Yes if you'd like to, please go ahead and make those updates in this branch. I'll update the PR title accordingly to reflect the expanded scope.

**Comment by rstoyanchev** [comment]
Thanks, I think the commits can be squashed. Logically it's one change applied everywhere.

**Pull request closed without merging**
