### PR TITLE
fixed issue where expired timestamp on cookie.toString method produce…

### PR DESCRIPTION
**Pull request by baskuis**
The expires date is not correctly generated.
The max age duration as seconds is added to the system time in millis.

@rstoyanchev - not sure if you already caught this ?

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@baskuis Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1857)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1857) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@baskuis Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1857)!

**Comment by rstoyanchev** [comment]
@baskuis, thanks but could you create a ticket in https://jira.spring.io/browse/SPR, please?

**Comment by rstoyanchev** [comment]
I've created https://jira.spring.io/browse/SPR-16940.

**Comment by baskuis** [comment]
@rstoyanchev - will do next time! (sorry don't know the process) :-)

**Comment by rstoyanchev** [comment]
No worries, it's important for tracking purposes, also for priority and fix versions. I've gone ahead and fixed this all around, including the max-age value and tests. Thanks for the report.

**Pull request closed without merging**
