### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by hasheniuk**
Obvious Fix
Fix broken navigation links.

### CODE REVIEW

**Comment by hasheniuk** [comment]
@snicoll  When I'm clicking "create a ticket" link, it does not navigate me somewhere. I expected it will navigate me to "Create a Ticket" chapter.
You can ensure by opening below links in the different tabs of your browser. Do you see the same?
https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#Create-a-Ticket
https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#create-a-ticket

**Comment by snicoll** [comment]
@hasheniuk what browser are you using? The link in the page works for me (which is https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#create-a-ticket and it does jump to the section). I am using Chrome.

**Comment by hasheniuk** [comment]
@snicoll Chrome, Firefox and Safari
broken-link

**Comment by snicoll** [comment]
Oh, I know what is going on now: I am an idiot.

I was looking at another link :(

**Comment by snicoll** [comment]
@hasheniuk thanks for bearing with me. This is now merged

**Pull request closed without merging**
