### PR TITLE
Improve tests and Javadoc on binding to a property of type javax.servlet.Part

### PR DESCRIPTION
**Pull request by binchoo**
When a controller obtains files from multipart requests,
there is an inconsistency when `jakarta.servlet.http.Part` type is an attribute of an object or an argument of a handler method.

If a method has an object argument, and expects files to be saved to attributes of that argument, the attribute type should not be `Part`, but it would rather be `MultipartFile`.

This is because `StandardMultipartHttpServletRequest` wraps its `Part`s, whose filename exists, with `StandardMultipartFile`.
`StandardMultipartFile` is an private class that implements `MultipartFile` class. So `Part` type attributes generate conversion errors.

In contrast, if the method has an argument type of `Part`, it can normally receive multipart files from the framework.

My idea is simply modifying `StandardMultipartFile` class to implement both `MultipartFile` and `Part`, so preventing conversion issues. Likewise I added new `MockStandardMultipartFile` class that replaces `MockMultipartFile` class. 

**Issues:** https://github.com/spring-projects/spring-framework/issues/27819

### CODE REVIEW

**Comment by rstoyanchev** [comment]
In the description, you refer to scenario 7 from #15220, but that issue and those scenarios specifically were addressed with PR #370. There is a test class [WebRequestDataBinderIntegrationTests](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/test/java/org/springframework/web/bind/support/WebRequestDataBinderIntegrationTests.java) for those scenarios. I'm wondering what is the difference between that and what you're running into?

**Comment by rstoyanchev** [comment]
Thanks for elaborating.

We do support `Part` for data binding, but only in fallback mode, when there is no `MultipartResolver` (this is in `ServletRequestDataBinder`). If you don't want to use `MultipartFile` you need to make sure that a `MultipartResolver` is not declared.

**Comment by binchoo** [comment]
@rstoyanchev 
Thanks! Your comment gave me a lot of hints to deep-dive into multipart bindings.

As I reviewed,
- DispatcherServlet::checkMultipart
- ServletRequestDataBinder::bind

when a request is a `MultipartRequest` that has been resolved by `MultipartResolver`, then
- `Part` in this request can be resolved for arguments type of `Part` and `MultipartFile`.
- `Part` in this request can be bound to attributes that are `MultipartFile` only.

So I concluded that `MockMultipartHttpServletRequestBuilder` is doing ok because it is a mock for `MultipartRequest` and follows the rules above.

> If you don't want to use MultipartFile you need to make sure that a MultipartResolver is not declared.

Yes I could test this by registering a multipart resolver that purposely returns false in `isMultiPart()`. 
```java
@Bean
MyMultipartResolver multipartResolver() {
    return new MyMultipartResolver();
}

class MyMultipartResolver extends StandardServletMultipartResolver {
    @Override
    public boolean isMultipart(HttpServletRequest request) {
        return false;
    }
}
```

**Comment by binchoo** [comment]
c3ea427 Added tests covering these behaviors.

> When a request is a MultipartRequest that has been resolved by MultipartResolver, then
> - Part in this request can be resolved for arguments type of Part and MultipartFile.
> - Part in this request can be bound to attributes that are MultipartFile only.

**Comment by rstoyanchev** [comment]
Thanks for the updates. I'll process this. 

Note that if you're in Boot application you can use `spring.servlet.multipart.enabled=false` to turn off the `MultipartResolver` config and then declare a bean of type `javax.servlet.MultipartConfigElement` which enables multipart support at the Servlet container level.

**Pull request closed without merging**
