### PR TITLE
SPR-17535 - Remove fragment from URL before passing it to resource provider

### PR DESCRIPTION
**Pull request by neVERberleRfellerER**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@neVERberleRfellerER Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2025)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2025) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@neVERberleRfellerER Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2025)!

**Comment by neVERberleRfellerER** [comment]
Code quality issue is probably spurious because my code contains assert and tool detects same issue with older tests too.

**Comment by rstoyanchev** [comment]
I've merged this but updated the algorithm a bit mostly for consistency with similar logic in `UriUtils`.

**Pull request closed without merging**
