### PR TITLE
spring-jdk9-hello-world

### PR DESCRIPTION
**Pull request by Arxemond777**
An example "Hello world" was added.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Arxemond777 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1556)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1556) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Arxemond777 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1556)!

**Review by lqjack — COMMENTED** [review]
great

**Comment by bclozel** [comment]
The Spring Framework repository does not contain sample applications.

**Pull request closed without merging**
