### PR TITLE
add dropwizard metrics to spring-web http client

### PR DESCRIPTION
**Pull request by xiaoshuang-lu**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@xiaoshuang-lu Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1610)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1610) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@xiaoshuang-lu Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1610)!

**Comment by bclozel** [comment]
Thanks for the PR, but we can't accept this change for several reasons, because this is:
* adding a mandatory dependency on DW Metrics to all Spring Framework projects
* already taken care of by Micrometer support in Spring Boot

**Comment by xiaoshuang-lu** [comment]
@bclozel thanks for your comments. I placed metric stuff in a `ClientHttpRequestInterceptor` class finally.

**Pull request closed without merging**
