### PR TITLE
modify constructor of class CustomNumberEditor

### PR DESCRIPTION
**Pull request by 0xarcher**
if numberClass is a subclass of Number, then the constructor determines that the Number subclass is not required.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@stormmaybin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1882)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1882) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@stormmaybin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1882)!

**Comment by stormmaybin** [comment]
finshed

**Comment by jhoeller** [comment]
While that isAssignableFrom assertion is rather old and dates back to the times before generics, it still doesn't hurt to check this upfront since - due to runtime type erasure - the passed-in Class may still be of a different kind. A not-null assertion doesn't really help since the incoming argument is declared to be non-null to begin with, and we have strict validation through nullability annotations in place now.

**Pull request closed without merging**
