### PR TITLE
Added a method to ignore null values when copying bean properties.

### PR DESCRIPTION
**Pull request by gauravat16**
Added a method to ignore null values when copying bean properties

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gauravat16 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25356)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25356) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gauravat16 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=25356)!

**Comment by gauravat16** [comment]
@spring-issuemaster Fixed the merge conflicts

**Comment by snicoll** [comment]
Thanks for the PR but `BeanUtils` is primarily for our own use within the framework and we're not keen to extend the surface API for something we don't need ourselves.

**Pull request closed without merging**
