### PR TITLE
Introduce mockAutowired() in ReflectionTestUtils

### LINKED ISSUE #20902: It's very boring to mock a lot of autowired fields in a complex service when writing a test case. [SPR-16355]
**[YushanGao](https://jira.spring.io/secure/ViewProfile.jspa?name=boroborome)** opened **[SPR-16355](https://jira.spring.io/browse/SPR-16355?redirect=false)** and commented

When write a unit test case for a service, we have to write code like this to mock every depend services:

ReflectionTestUtils.setField(targetService, "dependService1", dependService1Mock);
ReflectionTestUtils.setField(targetService, "dependService2", dependService2Mock);
ReflectionTestUtils.setField(targetService, "dependService3", dependService3Mock);
....

There will be many code like this in a complex service, we need an easy way to replace this code.

---

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1613

### PR DESCRIPTION
**Pull request by boroborome**
Add method mockAutowired and getBean to auto mock Autowired fields, then it will be easy when mock some complex server with many Autowired fields.It's a new feature.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@boroborome Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1613)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1613) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@boroborome Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1613)!

**Comment by snicoll** [comment]
@boroborome please create a Jira issue for this change.

**Comment by boroborome** [comment]
@snicoll I don't known where to create a issue.please give me a link?

**Comment by snicoll** [comment]
Sure, [here](https://jira.spring.io/browse/SPR)?

**Comment by boroborome** [comment]
This is the issue number : SPR-16355

**Comment by sbrannen** [comment]
Hi @boroborome,

Thanks for submitting your first PR to the Spring Framework, and sorry for taking so long to get back to you.

After reviewing your proposal, the team has decided not to introduce this support in `ReflectionTestUtils`.

In general, we recommend that `@Autowired` dependencies be injected via constructors or setter methods. This allows the dependencies to be supplied in tests without the need for `ReflectionTestUtils`.

For unit tests, if you wish to mock those dependencies easily, you may find the `@Mock` and `@InjectMocks` annotations from Mockito useful.

For integration tests with Spring Boot, you may find the `@MockBean` and `@SpyBean` annotations useful.

In light of the above, we are closing this PR.

**Pull request closed without merging**
