### PR TITLE
Support Optional<Principal> argument in @MessageMapping

### PR DESCRIPTION
**Pull request by KateVasovski**
Add method argument resolver to Optional<Principal>

@MessageMapping can use Optional<Principal> as a  method argument, which allows to work with or without authentication and to avoid error message org.springframework.messaging.simp.annotation.support.MissingSessionUserException: No "user" header in message

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@KateVasovski Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23612)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23612) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@KateVasovski Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23612)!

**Comment by rstoyanchev** [comment]
Thanks for the PR. I think this should be done in `PrincipalMethodArgumentResolver` instead of in an entirely new resolver. The `MethodParameter` has support for checking the parameter type in `Optional` arguments, like it's [done here](https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/handler/annotation/support/AbstractNamedValueMethodArgumentResolver.java#L88).

**Comment by rstoyanchev** [comment]
This has been merged. I've squashed the commits into one. There is no reason for the prior incarnation to remain in history.

**Pull request closed without merging**
