### PR TITLE
Fix for issue SPR-15906

### PR DESCRIPTION
**Pull request by Buzzardo**
I corrected the instructions for generating the documentation. I also made the file conform to the guidelines by wrapping at 90 characters or less.

### CODE REVIEW

**Comment by snicoll** [comment]
@Buzzardo unfortunately that fix has already been applied. (SPR-15906 is already resolved). The rest of the changes look good, thanks!

**Comment by Buzzardo** [comment]
I see that you didn't pull in the other changes I made (capitalization and so on). Should I make another update and pull request for those?

**Comment by snicoll** [comment]
The pull request is still open and will be processed. I am just informing you that SPR-15906 was already fixed when you pushed the code.

**Comment by sbrannen** [comment]
Please note as well that I performed a bit of _polishing_ in 9dd3a1cae7c7d65579117e51aca00959d4ea588c that will cause conflicts with the content of this pull request.

I'd therefore recommend that this PR be rebased (or, preferably, completely redone) on `master`.

**Comment by snicoll** [comment]
@sbrannen I already mentioned that in my first comment. I'll make sure to rebase that work on master. Thanks @Buzzardo!

**Pull request closed without merging**
