### PR TITLE
fix MutablePropertySources concurrent modify error

### PR DESCRIPTION
**Pull request by jxxiangwen**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jxxiangwen Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2067)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2067) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jxxiangwen Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2067)!

**Comment by jxxiangwen** [comment]
although the propertySourceList is CopyOnWriteArrayList, but the modify function is not atomic, for examples, the get function
`public PropertySource<?> get(String name) {
		int index = this.propertySourceList.indexOf(PropertySource.named(name));
		return (index != -1 ? this.propertySourceList.get(index) : null);//the element of index maybe has been changed
	}
`

**Comment by jhoeller** [comment]
`MutablePropertySources` is not meant to be fully guarded towards concurrent modification, just allowing concurrent read access while a single other thread is modifying. Full synchronization does not seem to be necessary for that purpose. Thanks for the suggestion, in any case!

**Pull request closed without merging**
