### PR TITLE
SPR-16417 - Support varargs for expectations in MockMvc

### PR DESCRIPTION
**Pull request by neonailol**
The current way of writing multiple expect statements is kinda verbose:

```java
 mockMvc.perform(get("/person/1"))
   .andExpect(status().isOk())
   .andExpect(content().contentType(MediaType.APPLICATION_JSON))
   .andExpect(jsonPath("$.person.name").value("Jason"));
```

I propose vararg method that can do the same in a slightly cleaner way using default interface method:

```java
 mockMvc.perform(get("/person/1"))
   .andExpect(
     status().isOk(),
     content().contentType(MediaType.APPLICATION_JSON),
     jsonPath("$.person.name").value("Jason")
   );
```

### CODE REVIEW

**Comment by sbrannen** [comment]
Hi @neonailol,

Thanks for the PR.

Please open a [JIRA issue](https://jira.spring.io/secure/CreateIssue!default.jspa) for this enhancement request and post a link to the JIRA issue back here.

**Comment by sbrannen** [comment]
FYI: I updated the title to more succinctly describe the enhancement request.

**Comment by neonailol** [comment]
I created an issues corresponding this pull request [SPR-16417](https://jira.spring.io/browse/SPR-16417)

**Comment by rstoyanchev** [comment]
Resolved in a slightly different way, by adding `ResultMatcher#matchAll`.

**Pull request closed without merging**
