### PR TITLE
Add title to SockJS iFrames for accessibility compliance

### PR DESCRIPTION
**Pull request by Aashay-Chapatwala**
Adding title tag for Accessibility compliance issue

### CODE REVIEW

**Comment by sbrannen** [comment]
Hi @Aashay-Chapatwala,

Congratulations on submitting your first PR for the Spring Framework! 👍 

I believe this should be performed for `HtmlFileTransportHandler` as well, so I'll take care of that when merging.

**Comment by sbrannen** [comment]
@rstoyanchev, do you think this should be performed for the prelude in `HtmlFileTransportHandler` as well?

**Comment by sbrannen** [comment]
This has been merged into `main` in 650875468cf37cd334dfac5e7d2e732cd9f8ffdb and revised in 6e5dd64025774e57502ee587b456169dcef5027a and 164141a63e93c5ad326f41441fc475e5ebaf6cdb.

In the future, please make sure you run a full local build before submitting a PR to ensure that the changes do not break existing tests.

Thanks

**Comment by Aashay-Chapatwala** [comment]
@sbrannen Is it possible to merge this as a hotfix in 5.2.13.RELEASE version onwards as well? e.g. 5.2.23.RELEASE

**Pull request closed without merging**
