### PR TITLE
LinkedMultiValueMap.getFirst - check that values is not empty

### PR DESCRIPTION
**Pull request by olszewskimichal**
To avoid situation when values is Empty and we trying get first element without checking that this element exists

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@olszewskimichal Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22421)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22421) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@olszewskimichal Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22421)!

**Comment by neoumenon** [comment]
Rookie question here...if values is not null but is empty, is returning null still applicable? As opposed to returning the empty list?  

return (values != null && !values.isEmpty() ? values.get(0) : null);

**Comment by snicoll** [comment]
@neoumenon please ask questions on StackOverfow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.

**Comment by neoumenon** [comment]
> @neoumenon please ask questions on StackOverfow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.

This question was specifically regarding the code being checked in, not a random question. But I'll take it to the stackoverflow channel for discussion. Thanks

**Comment by jhoeller** [comment]
This is indeed worth revisiting since a `LinkedMultiValueMap` may get constructed or populated with user-provided `List` instances which may be empty, even if for regular operations its internal Lists will always have an entry.

**Pull request merged**
