### PR TITLE
Support the meta annotation at @NumberFormat

### PR DESCRIPTION
**Pull request by kazuki43zoo**
Issue: SPR-12743

I support the meta annotation mechanism at the `@NumberFormat` as same with the `@DateTimeForamt`.
For detail, refer to https://jira.spring.io/browse/SPR-12743.

I have signed and agree to the terms of the Spring Individual Contributor License Agreement.

### CODE REVIEW

**Comment by kazuki43zoo** [comment]
@sbrannen 

I rebased.

**Comment by sbrannen** [comment]
Thanks

**Comment by sbrannen** [comment]
This has been merged into master.

**Comment by kazuki43zoo** [comment]
Thank you for merging.

**Pull request closed without merging**
