### PR TITLE
Documentation updated with instructions for STOMP Client

### PR DESCRIPTION
**Pull request by xixingya**
Hello, this pr may update the issue https://github.com/spring-projects/spring-framework/issues/28409

### CODE REVIEW

**Comment by linghengqian** [comment]
An additional topic is, should we point to another client being maintained?

**Comment by xixingya** [comment]
> An additional topic is, should we point to another client being maintained?

sure,but I am not found another client,if you find,Welcome to point out

**Comment by linghengqian** [comment]
> > An additional topic is, should we point to another client being maintained?
> 
> sure,but I am not found another client,if you find,Welcome to point out
> 

- I revisited https://stomp.github.io/implementations.html and noticed `stomp-js/rx-stomp` (refer to https://github.com/stomp-js/rx-stomp/ ) and `stomp-js/stompjs` (refer to https://github.com/stomp-js/stompjs/ ) is actively maintained under the same org. 

- I'm not really sure what `RxJS` means, but if it's the same context as `RxJava`, then obviously `stomp-js/stompjs` is not as well maintained as `stomp-js/rx-stomp`.

**Comment by snicoll** [comment]
@xixingya thanks for the PR but we'd prefer to revisit this part of the doc in more details.

**Pull request closed without merging**
