### PR TITLE
Reduce redundant cycles in PostProcessorRegistrationDelegate

### PR DESCRIPTION
**Pull request by huifer**
reduce redundant cycles in `org.springframework.context.support.PostProcessorRegistrationDelegate#invokeBeanFactoryPostProcessors(org.springframework.beans.factory.config.ConfigurableListableBeanFactory, java.util.List<org.springframework.beans.factory.config.BeanFactoryPostProcessor>)` 

```java
// Separate between BeanFactoryPostProcessors that implement PriorityOrdered,
		// Ordered, and the rest.
		List<BeanFactoryPostProcessor> priorityOrderedPostProcessors = new ArrayList<>();
		List<String> orderedPostProcessorNames = new ArrayList<>();
		List<String> nonOrderedPostProcessorNames = new ArrayList<>();
		for (String ppName : postProcessorNames) {
			if (processedBeans.contains(ppName)) {
				// skip - already processed in first phase above
			}
			else if (beanFactory.isTypeMatch(ppName, PriorityOrdered.class)) {
				priorityOrderedPostProcessors.add(beanFactory.getBean(ppName, BeanFactoryPostProcessor.class));
			}
			else if (beanFactory.isTypeMatch(ppName, Ordered.class)) {
				orderedPostProcessorNames.add(ppName);
			}
			else {
				nonOrderedPostProcessorNames.add(ppName);
			}
		}

		// First, invoke the BeanFactoryPostProcessors that implement PriorityOrdered.
		sortPostProcessors(priorityOrderedPostProcessors, beanFactory);
		invokeBeanFactoryPostProcessors(priorityOrderedPostProcessors, beanFactory);

		// Next, invoke the BeanFactoryPostProcessors that implement Ordered.
		List<BeanFactoryPostProcessor> orderedPostProcessors = new ArrayList<>(orderedPostProcessorNames.size());
		for (String postProcessorName : orderedPostProcessorNames) {
			orderedPostProcessors.add(beanFactory.getBean(postProcessorName, BeanFactoryPostProcessor.class));
		}
		sortPostProcessors(orderedPostProcessors, beanFactory);
		invokeBeanFactoryPostProcessors(orderedPostProcessors, beanFactory);

		// Finally, invoke all other BeanFactoryPostProcessors.
		List<BeanFactoryPostProcessor> nonOrderedPostProcessors = new ArrayList<>(nonOrderedPostProcessorNames.size());
		for (String postProcessorName : nonOrderedPostProcessorNames) {
			nonOrderedPostProcessors.add(beanFactory.getBean(postProcessorName, BeanFactoryPostProcessor.class));
		}
		invokeBeanFactoryPostProcessors(nonOrderedPostProcessors, beanFactory);
```

- I think the latter two cycles can be done ahead of time to avoid multiple cycles . 
  - `orderedPostProcessorNames`
  - `nonOrderedPostProcessorNames`

### CODE REVIEW

**Comment by quaff** [comment]
Files changed 101, serious?

**Comment by huifer** [comment]
> Files changed 101, serious?

Some of the changed files were submitted after merging the 5.2. X branch into my local area

**Comment by quaff** [comment]
> > Files changed 101, serious?
> 
> Some of the changed files were submitted after merging the 5.2. X branch into my local area

Create new branch for every PR, rebase on `master` branch before submit PR.

**Comment by huifer** [comment]
> > > Files changed 101, serious?
> > 
> > 
> > Some of the changed files were submitted after merging the 5.2. X branch into my local area
> 
> Create new branch for every PR, rebase on `master` branch before submit PR.

ok , i know . i close this issues . thank you .

**Pull request closed without merging**
