### PR TITLE
Object comparisons between all wrapper classes should use equals

### PR DESCRIPTION
**Pull request by ghost**
Object comparisons between all wrapper classes should use equals

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@thenx-wei Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24433)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24433) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@thenx-wei Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24433)!

**Comment by rstoyanchev** [comment]
It is actually fine the way it is, and the compiler understands to unbox `Boolean.True` and compare the values. The test that proves it [is here](https://github.com/spring-projects/spring-framework/blob/c1218615dfe67d672de2fcb6a44ea1f1ec8ffadc/spring-web/src/test/java/org/springframework/web/cors/CorsConfigurationTests.java#L214-L225). Further, `allowCredentials` is a nullable field and this way of comparing protects against NPE.

The changes to ContentDisposition appear to be unrelated and inconsistent with our code style.

**Comment by PascalSchumacher** [comment]
I guess this should be removed from the ` 5.2.4 ` milestone as it is invalid?

**Comment by sbrannen** [comment]
> I guess this should be removed from the `5.2.4` milestone as it is invalid?

Indeed. Done. Thanks.

**Pull request closed without merging**
