### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by neo01124**
Typo on the front page

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@neo01124 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1351)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1351) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@neo01124 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1351)!

**Comment by snicoll** [comment]
@pivotal-issuemaster this is an obvious change

**Comment by snicoll** [comment]
Thanks for the PR!

**Pull request closed without merging**
