### PR TITLE
Implementation for https://jira.springsource.org/browse/SPR-9585

### PR DESCRIPTION
**Pull request by samion**
Implemented wildcard support for profile selection.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@samion Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=107)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=107) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@samion Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=107)!

**Comment by izeye** [comment]
[SPR-9585](https://github.com/spring-projects/spring-framework/issues/14219) which this PR targets has been bulk-closed, so the state of this issue seems confusing.

**Comment by sbrannen** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by GumanPratapFinzly** [comment]
Hi @samion , can you reopen this and can we get this support ?

**Pull request closed without merging**
