### PR TITLE
Add a way to disable SSL verification

### PR DESCRIPTION
**Pull request by selkhateeb**
This is similiar to curl --insecure (-k) where sometimes you don't want ssl verification.

### CODE REVIEW

**Comment by bclozel** [comment]
Hi @selkhateeb - looks interesting!
Could you create an issue on jira.spring.io for this? (project Spring Framework, component "Web:client")?

Also, I think adding this directly on the RestTemplate won't fit with all our supported clients (netty, okhttp, etc). This could be done only on the `SimpleClientHttpRequestFactory`, as there are already some configurations facilities.

**Comment by pivotal-issuemaster** [comment]
@selkhateeb Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1008)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1008) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by ahrytsiuk** [comment]
Hello @selkhateeb, @bclozel as I see this issue is not resolved yet, and this PR looks abandoned. I can propose my help. 

@bclozel can you please guide me? Should I create a Jira ticket first?

**Comment by bclozel** [comment]
Hi @ahrytsiuk 

After checking this PR once more, it doesn't seem to be the right approach.

First, `RestTemplate` is now in maintenance mode so we're not adding new features to it. Also, this is a feature that really belongs at the request factory level - and this really depends on the underlying client library. You should be able to achieve the same by configuring an SSL context on the client/factory that fits your need.

As a result, I'm closing this PR.

**Comment by ahrytsiuk** [comment]
@bclozel I see your concern. 

Maybe it's a good idea to add some autoconfiguration into Spring Boot project which can handle this functionality depends on underlying HTTP library?

**Comment by bclozel** [comment]
I think you can already configure that on the client using the `RestTemplateBuilder`.

**Pull request closed without merging**
