### PR TITLE
added HttpHeaders.CONTENT_ID

### PR DESCRIPTION
**Pull request by alan-czajkowski**
Added HTTP Header `Content-ID` as per [RFC 2392](https://tools.ietf.org/html/rfc2392)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@alan-czajkowski Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24661)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24661) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@alan-czajkowski Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24661)!

**Comment by rstoyanchev** [comment]
@alan-czajkowski thanks for the pull request but we don't aim to include every possible header name in `HttpHeaders`.

**Comment by alan-czajkowski** [comment]
@rstoyanchev this is a pretty important addition to the `Content-*` list of headers

**Comment by rstoyanchev** [comment]
I'm not arguing the header is unimportant but rather that we use a different rational by including constants for headers that we actually use in framework code. Create your own constant for other headers you need.

**Pull request closed without merging**
