### PR TITLE
SPR-14488 - FastOutputStreamWriter to improve tps of http response and save memory

### PR DESCRIPTION
**Pull request by niaoge**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@niaoge Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1117)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1117) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@niaoge Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1117)!

**Comment by snicoll** [comment]
@niaoge could you please create an issue for this pull request in the [Spring Framework issue tracker](https://jira.spring.io/browse/SPR). When you do, please make sure to fill the `Reference URL` with the link to this pull request. Thanks!

**Comment by niaoge** [comment]
jiar issue created ,and ref url filled ,https://jira.spring.io/browse/SPR-14488

**Comment by bclozel** [comment]
Closing as a duplicate of #19061 - this PR mixes several concerns and performance claims are not backed up by any JMH benchmark. We've done significant performance improvements since. Closing.

**Pull request closed without merging**
