### PR TITLE
Avoid duplicate registration of @ControllerAdvice implementing both RequestBodyAdvice and ResponseBodyAdvice

### PR DESCRIPTION
**Pull request by liquanchen9**
fixbug: duplicate add on ControllerAdvice both RequestBodyAdvice and ResponseBodyAdvice

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@liquanchen9 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22638)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22638) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@liquanchen9 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22638)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22638) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by sbrannen** [comment]
Good catch. I'm not sure how often people implement `RequestBodyAdvice` and `ResponseBodyAdvice` in the same class, but it's certainly possible.

If you could sign the CLA and submit a test that was failing before the change that would be greatly appreciated.

**Comment by sbrannen** [comment]
Since this is a trivial change, @liquanchen9, we have decided to forgo the requirement to sign the CLA.

Thanks for your contribution!

**Comment by pivotal-issuemaster** [comment]
@liquanchen9 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=22638)!

**Pull request closed without merging**
