### PR TITLE
Apply instanceof pattern matching in `RootBeanDefinition`

### PR DESCRIPTION
**Pull request by FelixDes**
This pull request applies the instanceof pattern matching in the RootBeanDefinition class. This enhancement will improve code readability.

### CODE REVIEW

**Comment by sbrannen** [comment]
Hi @FelixDes,

Thanks for the PR.

Unfortunately, these are ASM classes, and the following is our policy on such classes.

Please refrain from modifying classes under `org.springframework.asm`, `org.springframework.cglib`, and `org.springframework.objenesis`. Those include repackaged forks of the third-party libraries ASM, CGLIB, and Objenesis. Any refactoring to those classes should take place upstream in the originating repository. The Spring Framework will then pick up the changes when syncing with official updates of the forked third-party libraries.

**Comment by sbrannen** [comment]
Hi @FelixDes,

In the future, please do your best to collect multiple related changes in a PR, since we generally do not like to merge PRs that effectively change a single line of code for style-related reasons.

**Comment by sbrannen** [comment]
This has been merged into `main`.

Thanks

**Comment by FelixDes** [comment]
Thanks a lot for your advice. I'm very glad to see that my PR has been accepted.

**Pull request closed without merging**
