### PR TITLE
SPR-15504 - UriComponentsBuilder's fromHttpRequest uses server port as host port when handling the Forwarded header

### PR DESCRIPTION
**Pull request by gvdenbro**
The UriComponentsBuilder's adaptFromForwardedHeaders method doesn't handle the host port of the Forwarded header correctly, which means that the URI generated through the fromHttpRequest method will append the server port to the host (of the Forwarded header), instead of just using the port (if any) defined in the host part of the Forwarded header.
This pull request will try to parse the port of the host of the Forwarded header, and configure the builder accordingly.
According to the RFC https://tools.ietf.org/html/rfc7239#section-5.3 and https://tools.ietf.org/html/rfc7230#section-5.4 the host part of the Forwarded header "provides the host and port information from the target URI", and as such should be handled in the adaptFromForwardedHeaders method.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gvdenbro Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1413)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1413) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gvdenbro Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1413)!

**Comment by snicoll** [comment]
@gvdenbro we need a Jira issue for this change. Can you please [create one](https://jira.spring.io/browse/SPR)?

**Comment by gvdenbro** [comment]
@snicoll I've created the following Jira ticket: https://jira.spring.io/browse/SPR-15504

**Comment by rstoyanchev** [comment]
Thanks for the pull request. How about not using another regex here and instead handle it as we do `"X-Forwarded-Host"` just a few lines below?

**Comment by gvdenbro** [comment]
@rstoyanchev I've adapted the code in order to remove the regex and it uses the same style as for the x-forwarded-host. it introduces a bit of code duplication though.

**Comment by rstoyanchev** [comment]
This is now merged with a shared method for the duplicated code. Thanks!

**Pull request closed without merging**
