### PR TITLE
Fixes bad grammar in reference document

### PR DESCRIPTION
**Pull request by kazuki43zoo**
Issue: SPR-12981

For details, please refer to the [SPR-12981](https://jira.spring.io/browse/SPR-12981).
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

### CODE REVIEW

**Comment by sbrannen** [comment]
This has been merged into master. Thanks!

**Comment by kazuki43zoo** [comment]
Thank you for merging!

I want to backport to 4.1.x. is OK ?

**Comment by sbrannen** [comment]
Since this is such a minor documentation issue, I think it is sufficient to apply the update only to master (i.e., for Spring Framework 4.2).

**Comment by kazuki43zoo** [comment]
I agree. thank you!

**Pull request merged**
