### PR TITLE
use lambda to refact the code

### PR DESCRIPTION
**Pull request by diguage**

### CODE REVIEW

**Comment by diguage** [comment]
I create an issue at JIRA: [[SPR-15637] Use lambda to refact the code - Spring JIRA](https://jira.spring.io/browse/SPR-15637)

**Comment by diguage** [comment]
I only refact the interfaces which are added the `@FunctionalInterface` annotation. And, I do not refact the test classes. 

@snicoll  I submit all the refactor.  Please review and merge. Thanks.

**Comment by snicoll** [comment]
@diguage thanks for the PR but please stop amending it because it makes it harder for me to review it. There are a lot of changes to review here already.

**Comment by diguage** [comment]
@snicoll 
I'm sorry. I just send PRs to Spring. I am exploring the proper way of cooperation. Please feel free to point out the problem and give some suggestions.

**Comment by snicoll** [comment]
No need to be sorry :)

The ideal situation for me would be that you squash all your commit in a single one (since I'll have to do it anyway) and rebase on master. You can do so by squashing your commit in your branch and push force it.

I haven't got the time to review the PR but if you keep adding commits it's not compelling for me to get on it, that's all I tried to say. Let's keep it as it is for now (no new changes), we can always work on another PR if you find more code to change. Also, the bigger a PR is, the more time is likely to be necessary to review it.

**Review by snicoll — APPROVED** [review]

**Pull request closed without merging**
