### PR TITLE
Cross reference additional Aware interfaces from BeanFactory Javadoc

### PR DESCRIPTION
**Pull request by Beca-se**
Add BeanFactory comment

### CODE REVIEW

**Comment by snicoll** [comment]
@Beca-se did you mean to open this PR? The title doesn't match the commit.

**Comment by Beca-se** [comment]
> @Beca-se did you mean to open this PR? The title doesn't match the commit.

@snicoll This is my PR. Can you help me to updated this then open this PR.

**Comment by snicoll** [comment]
Sorry for some reasons I read those as imports. More coffee needed here, I guess.

Can you share why you think those two `@see` references are warranted?

**Comment by Beca-se** [comment]
> Sorry for some reasons I read those as imports. More coffee needed here, I guess.
> 
> Can you share why you think those two `@see` references are warranted?

image

**Comment by sbrannen** [comment]
> Can you share why you think those two `@see` references are warranted?

The class-level Javadoc for `BeanFactory` contains a section that lists the "full set of initialization methods and their standard order". These two methods are listed there but are not cross referenced with `@see` tags like the others in the list.

**Comment by sbrannen** [comment]
This has been merged into `main`.

Thanks

**Pull request closed without merging**
