### PR TITLE
fix inefficient use of keySet operators in messaging classes

### PR DESCRIPTION
**Pull request by alexander-riss**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@alexander-riss Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1394)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1394) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@alexander-riss Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1394)!

**Comment by alexander-riss** [comment]
any comments on this?

**Comment by jhoeller** [comment]
Sorry, this fell through the cracks here. Could you please create a JIRA issue at https://jira.spring.io/browse/SPR, which is what we're using for tracking...

**Comment by jhoeller** [comment]
The changes themselves look fine to me. Just one small note: We usually don't import `Entry` like that but rather declare `Map.Entry` within the loops. Could you revise your PR accordingly and rebase it on current master please, then I'd be happy to merge it right away...

**Comment by alexander-riss** [comment]
issue created: SPR-15553 and commit updated

**Pull request merged**
