### PR TITLE
Apply "instanceof pattern matching" in additional locations

### PR DESCRIPTION
**Pull request by xixingya**
Add Feature Pattern Matching for instanceof

### CODE REVIEW

**Comment by sbrannen** [comment]
Thanks for the PR.

Please note that your changes break the build: https://ci.spring.io/builds/170984

So, please fix your changes and push them to this PR.

**Comment by xixingya** [comment]
> Thanks for the PR.
> 
> Please note that your changes break the build: https://ci.spring.io/builds/170984
> 
> So, please fix your changes and push them to this PR.

hello,I have fix changes can you help me to reviewed it?

**Comment by xixingya** [comment]
> Thanks for the PR.
> 
> Please note that your changes break the build: https://ci.spring.io/builds/170984
> 
> So, please fix your changes and push them to this PR.

I have no idea why this error occur 

TimedTransactionalSpringExtensionTests > springTransactionsWorkWithJUnitJupiterTimeouts() FAILED
    org.gradle.internal.exceptions.DefaultMultiCauseException at TimedTransactionalSpringExtensionTests.java:64
        Caused by: org.opentest4j.AssertionFailedError at TimedTransactionalSpringExtensionTests.java:64

**Comment by xixingya** [comment]
image
I have just run in my local it just build pass

**Comment by sbrannen** [comment]
> I have no idea why this error occur

That's a "flaky" test that fails from time to time.

You can safely ignore it.

Sorry for the false negative.

**Comment by xixingya** [comment]
> > I have no idea why this error occur
> 
> That's a "flaky" test that fails from time to time.
> 
> You can safely ignore it.
> 
> Sorry for the false negative.

Thank you for using your precious time to review my code.

**Comment by sbrannen** [comment]
Regarding the changes to `ClassReader` and `Enhancer`, please note the following policy.

> Please refrain from modifying classes under `org.springframework.asm`, `org.springframework.cglib`, and `org.springframework.objenesis`. Those include repackaged forks of the third-party libraries ASM, CGLIB, and Objenesis. Any refactoring to those classes should take place upstream in the originating repository. The Spring Framework will then pick up the changes when syncing with official updates of the forked third-party libraries.

But there's no need to modify this pull request. I'll simply ignore those changes when merging.

**Pull request closed without merging**
