### PR TITLE
Optimize `BeanMap#entrySet`

### PR DESCRIPTION
**Pull request by gudrb33333**
Hello, I have been learning a lot while analyzing this open source project recently. During my analysis, I noticed a TODO message and came up with an simple idea.

- Enhancing memory efficiency by setting the initial capacity of a HashMap.

I have read the contributor guidelines in detail, but there may still be some mistakes.

### CODE REVIEW

**Comment by sdeleuze** [comment]
I see a remaining `TODO: optimize` on `BeanMap#entrySet`, couldn't we directly use `Collections.unmodifiableSet()` with a `Set` where we define the initial capacity and remove this TODO?

**Comment by gudrb33333** [comment]
I’m not sure if I fully understood it correctly since my English isn’t very strong, but I didn’t remove the TODO because it’s just a simple idea, and I think there may still be room for further optimization.

**Comment by gudrb33333** [comment]
Do you mean using a Set directly without copying it into a HashMap?

**Comment by sdeleuze** [comment]
Yes

**Comment by gudrb33333** [comment]
I researched and discovered SimpleImmutableEntry, then modified the code to directly use Collections.unmodifiableSet().

**Comment by sdeleuze** [comment]
Thanks, make sense, but I initially missed those changes were done on the CGLIB fork that is included in Spring Framework, and we prefer avoiding doing such refinement on the fork, so I will decline. Thanks for your understanding.

**Comment by gudrb33333** [comment]
Thank you for the review! It was very motivating for me.

**Pull request closed without merging**
