### PR TITLE
Polish LinkedCaseInsensitiveMap

### PR DESCRIPTION
**Pull request by izeye**
This PR polishes `LinkedCaseInsensitiveMap`.

### CODE REVIEW

**Comment by jhoeller** [comment]
Following up on #22821, this would indeed benefit from some further polishing. However, those lazy key/value/entry are really meant to be published in a thread-safe fashion, preserving the notion of multi-threaded exposure for read-only purposes... so those fields should be declared volatile, in which case the current initialization pattern makes sense for thread-safe publication purposes.

I'll do a custom commit for the volatile declarations, also picking up your EntryIterator refactoring in it. Thanks for the PR, in any case!

**Comment by izeye** [comment]
@jhoeller Thanks for the quick feedback!

> in which case the current initialization pattern makes sense for thread-safe publication purposes.

If "the current initialization pattern" means [having a local variable](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/util/LinkedCaseInsensitiveMap.java#L240-L268), I'd like to understand that removing the local variable causes any problem. Could you please explain on this?

**Comment by jhoeller** [comment]
It's just a defensive coding pattern where the local copy of a volatile field can be reliably checked against (in case of multiple checks, it's a single consistent value which is not going to reflect concurrent changes from other threads), and where we're optimizing access to the volatile field to begin with (one read attempt only). We're using a similar pattern in other places.

**Comment by izeye** [comment]
@jhoeller Thanks for clarification :+1:

**Pull request closed without merging**
