### PR TITLE
Update WebSocketMessageBrokerStats.java

### PR DESCRIPTION
**Pull request by Niconal**
add missing [ in toString()

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Niconal Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2068)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=2068) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
@pivotal-issuemaster this is an obvious fix

**Comment by pivotal-issuemaster** [comment]
@Niconal This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by snicoll** [comment]
@Niconal thank you for making your first contribution to Spring Framework.

**Pull request closed without merging**
