### PR TITLE
Refactor with String#isEmpty()

### PR DESCRIPTION
**Pull request by stonio**
Polish few classes with `.isEmpty()` instead of `.length() == 0`.

### CODE REVIEW

**Comment by snicoll** [comment]
@stonio thanks for the PR, we prefer a single commit rather than small atomic commits. Can you please squash all that and push force your branch?

**Comment by stonio** [comment]
@snicoll All my commits squashed into a single commit.
May be backported to 4.3.x branch.

**Review by lqjack — COMMENTED** [review]
does the String (empty()) better then String (.length())?

**Comment by snicoll** [comment]
Thanks, we'll backport it to `4.3.x` later today.

**Pull request closed without merging**
