### PR TITLE
Make use of Stream API in AnnotationBeanUtils

### PR DESCRIPTION
**Pull request by pkostrzewa**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pkostrzewa Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1664)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1664) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@pkostrzewa Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1664)!

**Comment by sbrannen** [comment]
@pkostrzewa, what is the rationale behind this PR?

**Comment by pkostrzewa** [comment]
@sbrannen, improves readability. As this is my first contribution to open source I'd rather not make breaking changes for now.

**Comment by sbrannen** [comment]
> improves readability.

Well, we don't normally switch to stream-based approaches merely for the sake of readability because doing so can result in an unnecessary performance hit in core infrastructural code.

In any case, we will discuss it within the team and get back to you.

> As this is my first contribution to open source I'd rather not make breaking changes for now.

Sure. Hopefully you wouldn't want to make breaking changes in a subsequent contribution either. 😉

**Comment by sbrannen** [comment]
Hi @pkostrzewa,

We discussed it within the team, and although your proposal is certainly easier to read, we have chosen to leave the code as is.

I am therefore closing this PR.

Cheers,

Sam

**Pull request closed without merging**
