### PR TITLE
Update AnnotationUtils.java

### PR DESCRIPTION
**Pull request by jonathanborenstein**
https://jira.spring.io/browse/SPR-15287

### CODE REVIEW

**Comment by jhoeller** [comment]
See my comment on JIRA: I've adopted a different variant, using `getDeclaredAnnotation` instead.

**Comment by jonathanborenstein** [comment]
Did you do something like this instead?

if (clazz.getDeclaredAnnotation(annotationType) != null){
				return true;
			}

**Comment by jhoeller** [comment]
Indeed, and similar `getDeclaredAnnotation` calls returning the annotation found (if any) in other places. This seems to be the most efficient variant for our purposes, in particular when called against a `Class`.

I'll push this later tonight, along with a few other commits.

**Comment by jonathanborenstein** [comment]
https://github.com/spring-projects/spring-framework/pull/1338 - I updated the patch2 with the getDeclaredAnnotation method for the findAnnotation methods where the first parameter is an AnnotatedElement and for when the first parameter is a class. Also for the isAnnotationDeclaredLocally method.

I should have made this one pull-request/JIRA issue to begin with.

**Comment by jonathanborenstein** [comment]
https://github.com/spring-projects/spring-framework/pull/1338/files

That's the change I just made. It appears an Annotation array does not even need to be instantiated for both the findAnnotation methods I've updated.

**Pull request closed without merging**
