### PR TITLE
Use for-each instead of counting loop when iterating arrays

### PR DESCRIPTION
**Pull request by stsypanov**
subj

### CODE REVIEW

**Comment by snicoll** [comment]
Duplicate of #22315

**Comment by stsypanov** [comment]
yes, but this one mistakenly includes unrelated commit. This is why I closed this one.

**Comment by snicoll** [comment]
You can push force on an existing branch and it will update an existing PR, you shouldn't have to create another one.

**Comment by stsypanov** [comment]
Good, I'll keep this in mind for future!

**Pull request closed without merging**
