### PR TITLE
Make getters public in NamedParameterJdbcTemplate and ParsedSql

### PR DESCRIPTION
**Pull request by garydgregory**
Make getters public in two public classes.

### CODE REVIEW

**Comment by sbrannen** [comment]
Can you please provide the rationale and a concrete use case for the proposed changes?

**Comment by garydgregory** [comment]
Hi @sbrannen ,

I work on a proprietary product that uses Spring Batch as an ETL component in a suite. This ETL component has a custom copy of `org.springframework.batch.item.database.JdbcBatchItemWriter` as well as a subclass. This does all sorts of magic specific to our product. This code needs access to various bits and pieces of the Spring object tree which is currently achieved via reflection (nasty) which would be better served via public and protected APIs (nice.) I hope this helps clarify things.

Thank you,
Gary

**Comment by quaff** [comment]
+1 https://github.com/spring-projects/spring-framework/issues/20759

**Comment by snicoll** [comment]
Thanks for the PR but we're not keen to expose APIs like that, see https://github.com/spring-projects/spring-framework/pull/23766#issuecomment-1257728214

**Pull request closed without merging**
