### PR TITLE
Fixed reference

### PR DESCRIPTION
**Pull request by diguage**
Can not find the `NonNull`. I think it is `Nullable`.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@diguage Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1444)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1444) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
@pivotal-issuemaster this is an obvious fix

**Comment by pivotal-issuemaster** [comment]
@diguage This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by snicoll** [comment]
Merged, thanks!

**Pull request merged**
