### PR TITLE
Refact iterator of Map with Java 8 forEach

### PR DESCRIPTION
**Pull request by diguage**

### CODE REVIEW

**Comment by diguage** [comment]
I'm sorry. 
I rebase `master` to the PR branch: `diguage@java8-map$ git rebase master`. I may break the commit log.  
**Need I fix the log? How to fix?**

**Review by lqjack — COMMENTED** [review]
please use stream.collect(Collectors.toMap) instead of inserting the items using forEach.

thanks

**Comment by diguage** [comment]
@lqjack I send a email to you. Let's talk about your comment. Thanks.

**Comment by rstoyanchev** [comment]
I'm closing this PR since the commit looks looks wrong. Please re-submit with correct commits. It's hard to tell what exactly happened. I would suggest starting on a fresh branch and try to cherry-pick the commits that you actually want to submit. 

As a general comment don't worry too much about always rebasing on top of the latest in master. It is a moving target so there is bound to be some extra commits after yours, which is okay. We will rebase when processing the PR.

**Comment by diguage** [comment]
@rstoyanchev I resubmit the changes.  #1451

**Pull request closed without merging**
