### PR TITLE
Document that Spring Boot will auto-configure `RestClient.Builder` beans with the observation registry

### PR DESCRIPTION
**Pull request by quaff**
See https://github.com/spring-projects/spring-boot/issues/38500

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the suggestion but if this needs to be described, it should be in the Spring Boot reference doc.

**Comment by snicoll** [comment]
@bclozel see the above for context. I am reopening to get some more feedback as they are other places within our ref doc that have such references.

**Comment by bclozel** [comment]
While we always work towards consistency, I find this PR very frustrating to deal with. The former sentence came from an actual discussion with a library maintainer in #29904. I don't think dedicating our time to discussing this is time well spent.

**Comment by quaff** [comment]
One of this PR and #33866 should be merged to keep consistency. @bclozel

**Pull request closed without merging**
