### PR TITLE
Refactor concurrency within `DefaultSingletonBeanRegistry`

### PR DESCRIPTION
**Pull request by lmagyar89**
Issue: SPR-16620

### CODE REVIEW

**Comment by jhoeller** [comment]
Applied with different tradeoffs but addressing the same concerns. Thanks for raising this!

**Comment by bnbakp0582** [comment]
`	public String[] getDependentBeans(String beanName) {
		Set<String> dependentBeans = this.dependentBeanMap.get(beanName);
		if (dependentBeans == null) {
			return new String[0];
		}
		synchronized (this.dependentBeanMap) {
			return StringUtils.toStringArray(dependentBeans);
		}
	}`
	Can anyone tell me the reason for adding synchronized here?

**Comment by sbrannen** [comment]
> Can anyone tell me the reason for adding synchronized here?

@bnbakp0582, this is explained in the linked issue: https://github.com/spring-projects/spring-framework/issues/21161#issuecomment-453469217

In addition, please do not post screenshots of code in issues in this repository.

**Comment by bnbakp0582** [comment]
> > Can anyone tell me the reason for adding synchronized here?
> 
> @bnbakp0582, this is explained in the linked issue: [#21161 (comment)](https://github.com/spring-projects/spring-framework/issues/21161#issuecomment-453469217)
> 
> In addition, please do not post screenshots of code in issues in this repository.

No problem, thank you!

**Pull request closed without merging**
