### PR TITLE
Use io.spring.javadoc-aggregate

### LINKED ISSUE #24653: Experiment with aggregateJavadoc task in Spring Javadoc plugin
Experiment with the [`aggregateJavadoc` Gradle task](https://github.com/spring-gradle-plugins/javadoc-plugin) by @rwinch and provide feedback.

### PR DESCRIPTION
**Pull request by rwinch**
Closes gh-24653

### CODE REVIEW

**Comment by sbrannen** [comment]
Holding off on making this change to the build until we branch for `5.3`.

**Comment by sbrannen** [comment]
I tried out the PR against `master`, and I ran into the following.

```shell
> Task :dokka FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dokka'.
> Guice provision errors:

  1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://docs.spring.io/spring-framework/docs/5.3.0-SNAPSHOT/javadoc-api/, packageListUrl=file:/Users/sbrannen/source/spring-framework/build/docs/javadoc/package-list)
    at org.jetbrains.dokka.PackageListProvider.<init>(ExternalDocumentationLinkResolver.kt:35)
    at org.jetbrains.dokka.PackageListProvider.class(ExternalDocumentationLinkResolver.kt:35)
    while locating org.jetbrains.dokka.PackageListProvider
      for parameter 4 at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:204)
    while locating org.jetbrains.dokka.ExternalDocumentationLinkResolver
      for parameter 4 at org.jetbrains.dokka.DeclarationLinkResolver.<init>(DeclarationLinkResolver.kt:10)
    while locating org.jetbrains.dokka.DeclarationLinkResolver
      for parameter 0 at org.jetbrains.dokka.PackageDocs.<init>(PackageDocs.kt:20)
    at org.jetbrains.dokka.PackageDocs.class(PackageDocs.kt:19)
    while locating org.jetbrains.dokka.PackageDocs

  1 error
```

You can check out the build scan here: https://ge.spring.io/s/i25wgqhuanxzk

@rwinch, can you please look into this?

**Comment by rwinch** [comment]
There seem to have been some changes that broke the build. I have rebased and updated the pull request and it now appears to execute, but with classpath warnings due to missing optional dependencies. I created https://github.com/spring-gradle-plugins/javadoc-plugin/issues/13

At the moment we are waiting on figuring out how to best address that issue.

**Comment by sbrannen** [comment]
Since the [`io.spring.javadoc-aggregate`](https://github.com/spring-gradle-plugins/javadoc-plugin) plugin no longer appears to be actively developed and only has a 0.0.1 release, I am closing this PR.

**Pull request closed without merging**
